### ISSUE TITLE
Facility & responses page

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#1000]
Get columns from Survey settings.

**Comment by SamMousa** [comment]
@luna404 I'm working on showing customizable columns in the list of facilities for a workspace.
Are these columns coming from the data survey, admin survey, or both?

What I've done for now is add a checkbox in the survey designer to indicate that a question should be shown as a column in that list. But I'm not sure we need data from both surveys and want to check before I build it.

**Comment by luna404** [comment]
It would be useful to have the latest status of the HF displayed in the list of facilities for a workspace. This would mean we need some information from the response survey as well.

**Comment by SamMousa** [comment]
Follow up question, do you need to able to decide the order of columns?

**Comment by luna404** [comment]
For an initial version no, long-term would be a nice to have.

**Comment by SamMousa** [comment]
Use numeric fields with priority for ordering.
Add an extra field; use 1 for HF level and 1 for response list level.

**Comment by SamMousa** [comment]
Implemented.
