### ISSUE TITLE
HF admin / data updates without changes

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#1006]
Should we store or fully ignore updates without changes?

Since we have a date question as part of the survey it seems reasonable to assume that a survey without any changes does not certify anything.
An update that just changes the date of update field could be seen as a new certification / confirmation of the situation at the HF.

**Comment by SamMousa** [comment]
@luna404 thoughts?

**Comment by luna404** [comment]
1. Would this only be for edits or also for adding a new response?
2. I'm leaning towards ignoring changes without any updates but how would this work in practice? Right now we force users to add a new date of update if they add a new response. Would this mean users can no longer add two responses with the same date? (I would actually be in favor of this one) 
3. Another point to consider is introducing "draft" response to be validated by a workspace owner. This is something we'd like to implement moving forward as a way for selected users to request updating specific questions based on field observations they have done. We can't use the date of update to validate these responses as they would need a date of update (i.e., the date of the observation) themselves.

**Comment by SamMousa** [comment]
Superseded by:  https://github.com/HeRAMS-WHO/herams-backlog/issues/33
