### ISSUE TITLE
weblate not sending emails

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#1011]
There's still an issue with system emails from weblate not being received by users. We've tried creating an account, inviting a user, and resetting passwords. We do get the message from weblate that the email has been sent but we're not getting the email itself.

**Comment by SamMousa** [comment]
Emails are being sent but sometimes blocked. This is because we're on a shared IP plan for Sendgrid.
Have users add support@herams.org to their trusted sender list.

**Comment by SamMousa** [comment]
Resolved for real now.
