### ISSUE TITLE
Non unique subject_id in export with a date

### ISSUE THREAD

**Issue by mhabets** [HeRAMS-WHO/herams-backend#1015]
When doing the export for a specific date from dirty data coming from one of the projects, we got non unique `subject_id`. Is it ok or not?
It looks like the WS is also used somehow so that if the WS is different but the `subject_id` are the same then 2 records are exported with the same `subject_id` (but different WSs).

Example of an (incorrect?) export for a specific date:
```
subject_id | worspace_id | ...
5127Hh     | ws_name1    | ...
5127Hh     | ws_name2    | ...
```

**Comment by luna404** [comment]
I thought it was not possible to have the same subject_id in two different workspaces, but we actually have some use cases where this would be useful. 

Is this from Mali? If yes, have you made any changes to it? Both records have the same token so this might just be a sync issue. We created new workspaces for all ASC so it's possible that one record wasn't synced correctly after reimporting the data.

**Comment by mhabets** [comment]
Was in Mali project indeed. For the details at that time see [here](https://worldhealthorg.sharepoint.com/:i:/r/sites/HeRAMS/Shared%20Documents/AFRO/countries/MLI/data/cleaning/mli_subject_id_duplicates_2022-10-03.png?csf=1&web=1&e=kd3Ekk) or MLI_export_20220930_code.zip.

Note: the issue is no more present in the current data as I made the cleaning in coordination with the country FP.

**Comment by matof-who** [comment]
Not relevant anymore, as Survey JS export is build with a different structure
