### ISSUE TITLE
Deploy surveyjs-parser preview branch somewhere

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#1024]

**Comment by SamMousa** [comment]
Notes
- Deploy now works
- Api doesn't work yet, need custom nginx config

Todo:

- [ ] Build separate API container that runs php (and nginx?)

**Comment by SamMousa** [comment]
This is now working. The username is `admin@user.com`

**Comment by matof-who** [comment]
Hi @SamMousa 
What's the URL of the surveyJS migration environment ?

**Comment by SamMousa** [comment]
Here: you can see it in the PR 

> Preview environment created at: https://surveyjs-parser.herams-staging.org/
