### ISSUE TITLE
Map / Leaflet - improve the sensitivity of points to mouseover (sometimes hard to pick points currently)

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#141]

**Comment by SamMousa** [comment]
We can make the points larger, I've added a configuration setting `markerRadius`:
```json
{
    "code": "MoSD3",
    "colors": [
        "rgb(218, 223, 225)",
        "rgb(248, 148, 6)",
        "rgb(248, 148, 6)",
        "rgb(255, 203, 5)",
        "rgb(107, 185, 240)",
        "rgb(89, 171, 227)",
        "rgb(52, 73, 94)",
        "rgb(1, 50, 67)"
    ],
    "markerRadius": 25
}
```

Default value is 2. This is a screenshot of using 25:
![image](https://user-images.githubusercontent.com/547021/59259040-52b30800-8c39-11e9-9797-d6ce4307dbe8.png)

This is with 10:
![image](https://user-images.githubusercontent.com/547021/59259100-6fe7d680-8c39-11e9-90ab-0afeeaf1859f.png)



Let me know what you think the default should be after you've experimented a bit!

**Comment by SamuelPetragallo** [comment]
Current default is actually really good visually - is there anything like an extended/invisible select area around the visible part of the dot vs. increasing dot size?

**Comment by SamMousa** [comment]
Not that I can find; note that this would make it really hard to click dots that have overlapping invisible areas... What we could do is have something like a small dot, with a wide border, and then make the border semi transparent... This is something we should test in many iterations, better to do when I'm in Geneva.

**Comment by SamuelPetragallo** [comment]
Still pending - let's here if Caroline has something to suggest here ;)

**Comment by luna404** [comment]
If I understand the issue correctly, points are too small at low resolution making it difficult to select individual points. However, if the size is increased, they overlap and you can no longer select individual points. This is a fairly common issue with interactive maps and there is no perfect solution for it (unfortunately).

From a mapping point of few there are two ways to prevent dots from overlapping:

**Option 1: Change the icon size based on zoom level** 
Here is an example from [esri](https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=renderer_size_scale) illustrating how this would look like. The same should be possible with leaflet. It's not a perfect solution as the icon sizes would have to be hard coded. Thus, overlaps would still be possible. However, the advantage of this options is that we could keep the attribute information associated with the point. 

Here are some results from a quick google search on how to change the marker size based on zoom levels in leaflet
[exp 1](https://stackoverflow.com/questions/17382012/is-there-a-way-to-resize-marker-icons-depending-on-zoom-level-in-leaflet)
[exp 2](https://stackoverflow.com/questions/39696033/leaflet-changing-icon-based-on-zoom-level)

**Option 2: Aggregate points** 
The more traditional approach would be to aggregate the points at low resolution. 
Here's an [http://www.digital-geography.com/how-to-create-clustered-points-in-leaflet/](example) how this would look like. Although this is a very popular solution, by aggregating the points, we would lose the information of the attribute displayed. 

While there are ways to aggregated stratified by attribute (at least using esri), I would advise to not use this. If you look at [example ](http://ekenes.github.io/esri-js-samples/3/visualization/clustering/) here you can see that the map change dramatically depending on the zoom level which can easily result in misinterpretation of the data. 

There is a plugin in leaflet that aim to overcome the aggregation challenge using pie charts. It's a little more complicated to implement than the other solutions, but it would permit to keep the attribute information in the aggregated state. Here's an [example](http://bl.ocks.org/gisminister/10001728).

**Comment by SamuelPetragallo** [comment]
@sam on this can we go for option #1 with the example/code provided above for leaflet?

**Comment by SamMousa** [comment]
@SamuelPetragallo is this still relevant now that we have clustering?

**Comment by luna404** [comment]
Clustering has only been implemented for the world map not for dashboard maps.

@SamuelPetragallo are we exploring the pie chart clustering (http://bl.ocks.org/gisminister/10001728)?

**Comment by SamuelPetragallo** [comment]
Yes, maybe a combination of clustering and (when singled out) bigger points is the way to go.

I guess, when thinking at the use case again, that the best approach to this (in the end, after we've implemented the HF layer in HeRAMS) wil be the possibility to access/filter the HF list (and depending on permissions, go to the WS and Edit, export the HF report, etc. How about that? :p

**Comment by luna404** [comment]
> I guess, when thinking at the use case again, that the best approach to this (in the end, after we've implemented the HF layer in HeRAMS) wil be the possibility to access/filter the HF list (and depending on permissions, go to the WS and Edit, export the HF report, etc. How about that? 📦

I think this part will be addressed with the pop-up #408. 

As actionable items.
- Let's explore the implementation of the marker cluster pie charts.
- Depending on whether this is working as expected, we can then adjust the size of un-cluster points or see if a scale based zoom would make more sense.

@jeremiehelme I guess it's over to you. Let us know if you face any issues with the implementation of the marker cluster pie charts or if you have other concerns with the proposed solution.

**Comment by SamuelPetragallo** [comment]
Just a thought: could clusters per response value be a solution too?

**Comment by luna404** [comment]
< Just a thought: could clusters per response value be a solution too?

As far as I know, this would mean we would have to create individual layer for each category. Which in itself wouldn't be a bad approach as it would give us an opportunity to define the order in which layers are drawn. Right now we sometimes have categories that are hidden behind other values. We could visually improve this by always drawing the smallest layer last. 

Also, keep in mind that if there are only few records of a given category, these might not cluster. This means we would still have the issue of the point sizes and would need to implement zoom based scale (which I think would be good practice anyways).

**Comment by SamuelPetragallo** [comment]
I feel this would work out better than pies actually @luna404  - but the only way to know is to try out. Is that something you could implement on staging Jeremie so we can check the result?

**Comment by jeremiehelme** [comment]
There is two solutions, clusters per responses and cluster pie charts. I’ll try the first one.

**Comment by jeremiehelme** [comment]
@SamuelPetragallo @luna404 Can we discuss the two solutions together ?

**Comment by luna404** [comment]
As mentioned somewhere in the comments above, I think it comes down to trying the different solutions to see which one works best. I would suggest that I create a sample map outside of HeRAMS that illustrates the different approaches outlined above. Once we decided on the best approach, @jeremiehelme  you can try and see if it is possible to recreate this in HeRAMS. Would this work you?

**Comment by luna404** [comment]
@SamuelPetragallo and @jeremiehelme I create an example for each of the two solutions proposed using a subset of the Nigeria data.

**Option 1**: Donut chart clusters ([link](https://drive.google.com/file/d/17WLh0jmxMUR_B5fyoHf7VZ9ylHk-udtT/view?usp=sharing))

**Option 2**: Clusters by category ([link](https://drive.google.com/file/d/10_G2gr5gfq1jN9wJ8kiuuuGQCuIYSUHD/view?usp=sharing))


I prefer the pie chart clusters. The clustering by category doesn't fully solve the issue with points being hidden. Also the fact that each layer clusters independently sometime creates misleading clusters. 

PS: You'll have to download the files and open them in your browser. I can't find a better why to share an HTML doc.

**Comment by jeremiehelme** [comment]
I pushed the cluster option on staging

<img width="1680" alt="Capture d’écran 2020-09-25 à 08 34 14" src="https://user-images.githubusercontent.com/2345926/94234525-2264ab00-ff0a-11ea-9535-04947012be12.png">

Clicking on a legend item disable the clusters and hide / show the clicked item
The toggle button at the bottom of the legend switch between clusters and points

**Comment by luna404** [comment]
This great! Well done with the toggle button.

I noticed the size of the markers is much bigger than previously and the radius size set by the user doesn't seem to work. Have you explored using zoom based marker sizes?

**Comment by jeremiehelme** [comment]
Yes they are a bit bigger, 
They should be smaller at a higher zoom, and bigger when we zoom in ?

**Comment by luna404** [comment]
Exactly

**Comment by jeremiehelme** [comment]
Added back the possibility to choose the dots radius, and optimized the size of the dots at higher zoom

**Comment by luna404** [comment]
Can you make the markers a little smaller? This is with radius =1 

![image](https://user-images.githubusercontent.com/18245059/96688883-f65e0d80-1381-11eb-801a-f4d6686e2f54.png)


https://herams-staging.org/project/24?page_id=278

**Comment by jeremiehelme** [comment]
I adapted the size of the dots : 
- 1 : small but still clickable (default value)
- 6 : a good size
- 15 : starting to be too big
