### ISSUE TITLE
Ability to filter Geo1 by admin 1 and admin 2

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#189]
If users apply filters on the dashboards they currently have to select each drop-down item individually. In the case of the Geo1 variable, the drop-down values combine multiple administrative levels (e.g. Region 1 / District 1, Region 1 / District 2, etc.). It would therefore be desirable if an option exists that allows users to select all drop-down items of a region (e.g. all districts of region 1).

**Comment by SamMousa** [comment]
What about using a widget like this for nested data?

https://wwwendt.de/tech/fancytree/demo/#sample-ext-glyph-awesome5.html

@SamuelPetragallo

**Comment by SamuelPetragallo** [comment]
That's perfect with me - thoughts anyone else?
