### ISSUE TITLE
HeRAMS External Evaluation Report Feedbacks

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#204]
Consolidation of comments and suggestions for the HeRAMS External Evaluation Report

**Comment by JeffDotingco** [comment]
[Comments_for_evaluation report_JBD.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3555644/Comments_for_evaluation.report_JBD.docx)

**Comment by JeffDotingco** [comment]
1. _"In Sudan and Philippines MOHs have requested for it to be expanded across the whole country"_ (Page 18)

- In the past, the implementation was WHO-driven in PHL. A unit (Health Emergency Management Bureau) has just recently approved that HeRAMS be implemented but still needs approval from senior management (i.e undersecretary). So it is still premature to say that PHL MOH has requested for HeRAMS to be expanded across the country.

2. _"Stakeholders consider HeRAMS relevant in key stages of the Humanitarian Programme Cycle and in the achievement of its founding objectives"_ (Page 20)

- The result of relevance should be explained more highlighting the link of HeRAMS to the phases of the Humanitarian Programme Cycle (including preparedness) as depicted in Figure 5 (Relevance Scores).

3. _"Complements existing standards such as in Yemen where HeRAMS has been based on the Minimum Service Package"_ (Page 21)

- The health service indicators of HeRAMS are used in the World Bank MSP project for Yemen by level of care. HeRAMS indicators were not based from the the MSP of YEMEN. The indicators were used to create the MSP.

4. _”Discrepancy of data and reality, [it is] embarrassing [for] advocacy and engaging with Donors. [We] recently visited facilities to rehabilitate but then discovered others had already intervened.” (Yemen KII, 06/06/2019)"_ (Page 23)

- **Please delete this statement. The resource person who said this statement is unaware that Health Cluster implementing partners are also responsible of renovating health facilities that they are assigned as part of their programs under the Health Cluster (HC), even without the knowledge of WHO Country Office. It is one of the indicators that needs to be accomplished if the funding comes from the Health Cluster.**



[Comments_for_evaluation report_JBD.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3556250/Comments_for_evaluation.report_JBD.docx)

**Comment by SamuelPetragallo** [comment]
Jeff agree with that and will share. Would just nuance the last point: If I get that correctly, I think it boils down to our ability to have effective monitoring in place, i.e. data WAS correct but situation change not reported/detected - is that correct? or is there something else I missed? Please confirm and I'll integrate as I have FINALLY completed my reading feedback :)

**Comment by JeffDotingco** [comment]
Hi @SamuelPetragallo, "discrepancy of data and reality" should be changed to "lack of coordination among health actors" in terms of health facility rehabilitation. Some HFs reported to be damaged might have already been renovated by a health partner/s, but the rehabilitation has not been reflected in HeRAMS by district health officer in charge of that HF renovated. Therefore, the need to link HeRAMS as a monitoring tool of HF damage or functionality status among health actors (Health Cluster, MOH and World Bank) is highly essential in Yemen through robust coordination. :) FYI: the evaluation team is good at using "flowery" words, so they can rephrase the former statement into a more positive one.:P

**Comment by FatmaGiha** [comment]
The team feedback is consolidated and incorporated in this version: 
General comments:

- To maintain consistency of the text (i.e., using British English, hyphenated text like decision-maker, MOH vs MoH….)
- To carefully using the health cluster vs. health sector
- The Conclusions/Recommendations – pg.31 to 34 -  are to be aligned to the core text - previously revised sections. 

[HeRAMS_Evaluation_FinalReport_Draft_V1.2_FG_JBD.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3844920/HeRAMS_Evaluation_FinalReport_Draft_V1.2_FG_JBD.docx)

**Comment by JeffDotingco** [comment]
And consistency of using HeRAMS (Page 18 of the doc used HERAMS).

**Comment by SamuelPetragallo** [comment]
Hoping to read again/consolidate by tomorrow COB then share with Stéphane and Karl for "endorsment"

**Comment by JeffDotingco** [comment]
The "HERAMS" text that should be corrected was already edited by @FatmaGiha.
