### ISSUE TITLE
Standardisation of standard variable colors in the dashboard  

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#206]
These are the colors I used for HeRAMS NGA for discussion with the HEX codes and Decimal Codes using from the link: https://www.rapidtables.com/web/color/RGB_Color.html

**Comment by luna404** [comment]
I thought I put together a few standard rules on the use of colors in charts and maps. Most of them are already adhered to in the dashboards, but it might be a could reminder when we work on standardizing the colors. 

1.	As a rule of thumb, it is generally said that the human eye is not capable to distinguish more than five shades of a color. Thus, in cases where we have more than five categories (e.g. HF type) we should make sure that colors are easily distinguishable. 

2.	Continuous colors should not be use for categorical values as users might wrongfully perceive them as a degree of severity. Always keep in mind that the first 20sec a user spends on a page are the most important. Thus, they won’t read the legends before looking at a chart. In the example below, if you just look at the chart you get the impression that darker the color the more severe the cause of unavailability is. 
 
![image](https://user-images.githubusercontent.com/18245059/64101387-0bd33b00-cd6e-11e9-9fde-4fcb2a53951c.png)

Similarly, the example below gives the illusion that categories in green/blue are related, which is not the case.
 
![image](https://user-images.githubusercontent.com/18245059/64101395-1097ef00-cd6e-11e9-9f8d-f1420ec32ae8.png)

Thus, a categorical color scale should always be used in these cases. 
 
![image](https://user-images.githubusercontent.com/18245059/64101403-142b7600-cd6e-11e9-99cd-f9e383506aa4.png)

3.	We should try to make sure that a color is only used once on a page. For example, red (rgb:255,0,0) always means not functional. This allows a user to understand a chart/map without having to read the legend. A good example for this is used in the BA page in Nigeria. The same shade of red always indicates not available.

![image](https://user-images.githubusercontent.com/18245059/64101430-21486500-cd6e-11e9-8e61-ae4424e68021.png)

4.	Similar to point 1, the more color used on page, the more difficult they are to read. The above example is rather busy and takes a moment to understand. Although the example below violates point number 1, it is (in my opinion) easier on the eye.
 
![image](https://user-images.githubusercontent.com/18245059/64101443-29080980-cd6e-11e9-8962-34c0fcfe7032.png)

5.	The traffic light color scheme (red to green) should only be use for question which go from “bad” to “good”. We should also make sure that all question using the traffic light method use the same shades. In the example below, the green should be the same shade.
   
![image](https://user-images.githubusercontent.com/18245059/64101454-2d342700-cd6e-11e9-89b3-b7988e397b5e.png)
![image](https://user-images.githubusercontent.com/18245059/64101456-302f1780-cd6e-11e9-8686-99c759558ad0.png)

Here are some resources to create color nice color schemes 
[Color picker for data](http://tristen.ca/hcl-picker)
[ColorBrewer](http://colorbrewer2.org)
[Adobe Color Wheel](https://color.adobe.com/create)

**Comment by JeffDotingco** [comment]
Thanks @luna404, agree with items 2 and 3. Can you send the HEX Codes / Decimal codes of colors you used for reasons of nonfunctionality?

**Comment by luna404** [comment]
Here are the rgb codes I used.  They are not the best colors though, so if you have a better color scheme I'm happy to change mine.

Lack of health staff: rgb(246, 146, 135)
Lack of medical supplies: rgb(138, 208, 230)
Lack of finances: rgb(233, 228, 119)
Lack of training of health staff: rgb(222, 169, 210)
Lack of medical equipment: rgb(136, 230, 176)

As we don't always have the same number of answer option, it might be better to define the color scheme/gradient used rather than the exact colors. There are some common color palates (e.g. used in R or ColorBrewer). For example we could say we use [Set2](http://colorbrewer2.org/#type=qualitative&scheme=Set2&n=7) for reasons of non-functionality and [RdYlGn](http://colorbrewer2.org/#type=diverging&scheme=RdYlGn&n=7) for availability and functionality. 

Here is a list of common color schemes
![image](https://user-images.githubusercontent.com/18245059/64103752-2c51c400-cd73-11e9-89a5-76b2186e1b04.png)

**Comment by JeffDotingco** [comment]
@luna404, I think "Set2" will be nice for reasons of non-functionality / non-accessibility / service non-availability reasons

**Comment by JeffDotingco** [comment]
I used the colors again in the production stage of HeRAMS NGA but made some modifications on basic amenities (e.g. if there is no water source, it is red). For health facility type, I attached the HeRAMS YEM HF type HEX color codes used for reference (tertiary / secondary level in shades of blue, primary level in shades of orange).

[HeRAMS NGA HEX Codes.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3566964/HeRAMS.NGA.HEX.Codes.docx)
[HeRAMS YEM HEX Codes.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3566966/HeRAMS.YEM.HEX.Codes.docx)

**Comment by SamMousa** [comment]
https://github.com/WorldHealthOrganization/herams-backend/issues/35

**Comment by luna404** [comment]
Here are some ideas to help standardize the colors used in the dashboards 

1. **Diverging colors**: We should use the same color scheme for all diverging questions (e.g. HFACC1, CONDE, CONDB, HFFUNCT, all questions related to sufficiency and availability). For ease of reading, the outer limits of the color scheme should always remain the same. 
![image](https://user-images.githubusercontent.com/18245059/64187231-88e6d900-ce70-11e9-9be5-72f6dc2ec868.png)

2. **Colorblind safe alternatives**: I fully agree with the point made by @SamMousa. Here are some example for colorblind safe alternatives for diverging color schemes. For more examples have a look at [ColorBrewer](http://colorbrewer2.org/#type=diverging&scheme=PiYG&n=5).
![image](https://user-images.githubusercontent.com/18245059/64187365-ca778400-ce70-11e9-9b11-b282718d25ac.png)

3. **Grey Scales**: Grey scale colors are useful as background colors (i.e. answer options that are of lower priority). In the example below, users will automatically pay more attention to the colors.
![image](https://user-images.githubusercontent.com/18245059/64187491-feeb4000-ce70-11e9-9e42-0b648d9e27f3.png)

4. **Reasons of unavailability** should always use the same qualitative colors scale. Below are some examples of popular qualitative color schemes. As we already have bright colors for the service availability questions, choosing a lighter color palette such as Pastel (see first chart) would make the whole page less busy.
![image](https://user-images.githubusercontent.com/18245059/64188219-46260080-ce72-11e9-8055-0e5ac18c8e32.png)

5. **Basic Amenities**: The challenge with this page is to avoid it from becoming too busy while still being able to clearly distinguish the different questions. If we stick to the rule of using different qualitative color schemes for each question, the page becomes very busy. 
![image](https://user-images.githubusercontent.com/18245059/64188745-407cea80-ce73-11e9-8527-20ed3cffe510.png)
However, if use the same colors for each *source* questions, we create the illusion of a relationship between the questions. 
![image](https://user-images.githubusercontent.com/18245059/64188796-55f21480-ce73-11e9-91b0-4e50e14ab264.png)
One potential solution might be to use continuous color palettes for the *source* questions. 
![image](https://user-images.githubusercontent.com/18245059/64188835-7326e300-ce73-11e9-923b-f04b066ac039.png)

Here are some examples of continuous color schemes. 
![image](https://user-images.githubusercontent.com/18245059/64189079-e9c3e080-ce73-11e9-80d1-fe29e9958538.png)

6. **Continuous color scales**:  For continuous scales, the order matters. In the example below the darker color appears “more important”. We can use this to give emphasis either to the clean water source (left) or the Unimproved water source (right).
![image](https://user-images.githubusercontent.com/18245059/64189003-c436d700-ce73-11e9-8821-f18bd734dc1f.png)

Have a look the [Chroma Color Picker](#http://tristen.ca/hcl-picker/#/hlc/5/1/744A63/EF8370) and the related [article ](https://www.vis4.net/blog/2011/12/avoid-equidistant-hsv-colors/). It's a great resource to rapidly generate nice colors for charts and maps.

**Comment by JeffDotingco** [comment]
Thanks a lot @luna404 for this! :) I agree of using the continuous color scheme for basic amenities, example will be the water source with continuous color (left chart, darker color emphasis on clean water source). 

For reasons of unavailability, the color scheme used in first and second chart (outpatient services and minor trauma) are fine with me.

**Comment by luna404** [comment]
@JeffDotingco  thanks for the feedback. 

What does everyone think of switching the standard green to red scale to something more colorblind friendly. 

For the HF type, what do you think of a default colors for each level and the different shades in case you need to further distinguish the different HF types?

![image](https://user-images.githubusercontent.com/18245059/64235714-39002480-cef9-11e9-86a8-509242b36eba.png)

**Comment by luna404** [comment]
Here's example of a page using colorblind friendly diverging colors

![image](https://user-images.githubusercontent.com/18245059/64236237-45d14800-cefa-11e9-9849-8b175e1772de.png)

**Comment by JeffDotingco** [comment]
I agree with the HF type default color scheme. 

For the standard (green, orange, red) for functionality, damage status etc., I still would like to keep this because you know exactly the status of HFs.

**Comment by luna404** [comment]
@JeffDotingco I understand your point with the red to green color scale. However, we should also take into account that approximately 1 in 12 men (8%) is color blind. Do you think any of the color scales below would be easy enough to understand?

![image](https://user-images.githubusercontent.com/18245059/64244839-09a5e380-cf0a-11e9-9260-b29fcaef2245.png)

**Comment by SamMousa** [comment]
> For the standard (green, orange, red) for functionality, damage status etc., I still would like to keep this because you know exactly the status of HFs.

Besides color blindness; `green => good` is a cultural thing. There are cultures where `red => good`.
