### ISSUE TITLE
Project Summary Popups sizing

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#208]
Project summary popups are likely to get a lot of "views".

Realized that with longer project name, the "Details" button (access to the project dashboard) no longer shows immediately (need to scroll down):

![image](https://user-images.githubusercontent.com/15345099/64180901-d90c6e00-ce65-11e9-83fa-938b90296d9b.png)

More generally, would be good to fix some of there elements in those popups to ensure they display nicely.

**Comment by SamMousa** [comment]
Given that we now have this information available more efficiently (local data storage) and given that we will get a front end dev soon we can rework these to not use iframes. and have improved dynamic sizing.

**Comment by SamuelPetragallo** [comment]
Noted sounds good - let's file that for when the frontend dev is on board

**Comment by luna404** [comment]
This is still an issue

**Comment by jeremiehelme** [comment]
That's a good Idea
@SamMousa How do you see that ? the iFrame allowed to load datas asynchronously
Do we have a way to get the datas with javascript ? Can we call the API for example ?
We would need 
- Health facilities count
- "Contributors" count
- Types, Functionalities and service availability percentages

**Comment by SamuelPetragallo** [comment]
> Noted sounds good - let's file that for when the frontend dev is on board

Welcome @jeremiehelme and thanks @luna404 for verifying the stale bot!

**Comment by SamMousa** [comment]
@jeremiehelme we have these counts available within the same query result so we could just preload all the data.

The API already has facility count & contributor count and is still quite fast.
All we would need to add is the 3 metrics and we should be able to do it in just 1 page load.

**Comment by SamMousa** [comment]
@jeremiehelme I have updated the code to use a fetch and get the information as JSON.

You should be able to build whatever markup you want from this. Let me know if you have questions.

**Comment by SamMousa** [comment]
Loader: https://github.com/HeRAMS-WHO/herams-backend/blob/master/protected/widgets/map/Map.php#L56

Popup content: https://github.com/HeRAMS-WHO/herams-backend/blob/master/protected/widgets/map/Map.php#L140

FYI:

- The content is loaded just the first time the popup is shown
- There is no error handling yet, so if the fetch fails the errorhandler is show indefinitely (you can use this for testing the loader by going offline in browser developer tools)

**Comment by jeremiehelme** [comment]
#384 @SamuelPetragallo Let's discuss that here 


<img width="1680" alt="77674526-064c7500-6f8c-11ea-812c-136e02309f93" src="https://user-images.githubusercontent.com/2345926/77742516-dd24f680-7016-11ea-9379-ad3b8cf80f51.png">


Samuel :
"Looks good - the challenge here is keeping the charts (and the 3 metrics) in equal proportions. That means standardizing/limiting the legend for the "Type" (functionality and service availability are already standard). We had already discussed that, not sure why we have not implemented. If there's no other issue, let's try to regroup all under Tertiary, Secondary, Primary and Others. I suggest removing unknowns: this data is mostly to "give a sense" of what is available through the dashboards and will never be used as such for analysis or decision making, so "visual" can take over "rigor" here"

If I summarize

- having the charts and metrics in equal proportions (Same number of metrics ?)
- Type should have 4 metrics : Tertiary, Secondary, Primary and Others
- Don't display "Unknowns"

This is a bit confusing, because then there would be 3 metrics for Services, and 4 for Types ?

**Comment by SamuelPetragallo** [comment]
@JeffDotingco @luna404 @fatma I suggest we standardize those 3 metrics for all projects so we can get the layout squeaky clean. These are just "apetizers" anyway.

Suggestion is to have (and only) the following:
1. Type: Tertiary / Secondary / Primary / Others
2. Functionality: Fully functional / Partially functional / Not functional
3. Service Availability: Fully available / Partially available / Not available / Not normally provided

In doing so we purposly exclude answers for which there are no values that sometimes come in as "unknown". Again, these metrics are apetizers, the detail comes with the dashboards

Let me know if you all agree (and if I've missed something) so Jeremie and Sam can move ahead for next release, thanks!

**Comment by JeffDotingco** [comment]
Hi @SamuelPetragallo, for HF Type, can this be done through responses from an equation? This was done already by Caroline from the request of WCO YEM and already working.

**Comment by SamMousa** [comment]
@JeffDotingco HF type can be mapped via project settings.

**Comment by JeffDotingco** [comment]
> @JeffDotingco HF type can be mapped via project settings.

Okay @SamMousa

**Comment by SamuelPetragallo** [comment]
Yes we can map it in project settings. That way we have standard/comparable data at his level across projects and can have a solid layout

**Comment by jeremiehelme** [comment]
@SamuelPetragallo @SamMousa  What's the decision finally ?

Also, do you want to display percentage ?

**Comment by SamuelPetragallo** [comment]
@SamMousa we've standardized values. We still want to exclude "unknown". Is there something needed from your end there to do that? Or @jeremiehelme can do it?

**Comment by luna404** [comment]
> @JeffDotingco @luna404 @fatma I suggest we standardize those 3 metrics for all projects so we can get the layout squeaky clean. These are just "apetizers" anyway.
> 
> Suggestion is to have (and only) the following:
> 
> 1. Type: Tertiary / Secondary / Primary / Others
> 2. Functionality: Fully functional / Partially functional / Not functional
> 3. Service Availability: Fully available / Partially available / Not available / Not normally provided
> 
> In doing so we purposly exclude answers for which there are no values that sometimes come in as "unknown". Again, these metrics are apetizers, the detail comes with the dashboards
> 
> Let me know if you all agree (and if I've missed something) so Jeremie and Sam can move ahead for next release, thanks!

I agree with the standardization of the categories. Can we also standardize the order? Currently the order is based on the order of the answer code. In the example below, it would be preferable if `others` were listed on the bottom. 

![image](https://user-images.githubusercontent.com/18245059/78005073-56845800-733b-11ea-9807-af9ff90e57c9.png)


Also, I think it would look nicer if the legends are left aligned rather than centered.

**Comment by jeremiehelme** [comment]
@luna404 @SamuelPetragallo @JeffDotingco @luna404 @fatma, here it is, with the legend aligned left

![Capture d’écran 2020-04-01 à 10 10 59](https://user-images.githubusercontent.com/2345926/78114169-1edfe380-7401-11ea-85e7-6035b1a1ef00.png)

About the order, it seems good on my side, I have to check on staging

**Do you want percentages or the normal values in the legend ?**

**Comment by SamuelPetragallo** [comment]
Note that values here are different than what we discussed (but I guess it's just a mockup here - would need to look at staging).

Regarding your question, I'd prefer % here (again, high level info nothing operationnal)

**Comment by jeremiehelme** [comment]
Great, yes it's just the values I have on my side.

![Capture d’écran 2020-04-01 à 11 28 08](https://user-images.githubusercontent.com/2345926/78121632-e8f42c80-740b-11ea-86f5-c74f14aefae1.png)

@luna404 about standardizing the order, Its not easy to do it when displaying the datas. I don't know in advance what datas I'll have (Full, Partial... or Tertiary, Secondary...), so I would have to do it "manually" for each case, saying for example : if I have Tertiary then it goes first, Secondary should be second...

**Comment by SamuelPetragallo** [comment]
I think we need to always display those values in the legend and always in the same order - and manage cases where the data is not there or incomplete: e.g. using "-" instead of missing values

**Comment by jeremiehelme** [comment]
@SamuelPetragallo What I understand is that I can expect to always receive the same labels :
Full, Partial and None for Functionality and Service Availability
Primaire, Secondaire, Tertiaire and Other for Type
So I can order them, and fill the value with "-" if there is none

**Comment by SamuelPetragallo** [comment]
Exact

**Comment by jeremiehelme** [comment]
Ok perfect,
Let's see how it works on staging

**Comment by jeremiehelme** [comment]
Some countries have labels in french rather than english on staging.
I expect Primary, Secondary, Tertiary and Other

**Comment by SamMousa** [comment]
This has some loading issues, try switching between popups and you'll see that you get blank popups.

**Comment by jeremiehelme** [comment]
Adapting project popup legends 
- custom labels
- ordering
- adding -- if no value
- adding <1% if under 1%

![Capture d’écran 2020-04-08 à 16 05 41](https://user-images.githubusercontent.com/2345926/78794061-8672d180-79b3-11ea-96d2-3676f27de8a6.png)

**Comment by luna404** [comment]
@jeremiehelme can we hide the `Dashboard` button for projects who do not have a dashboard yet e.g. Palestine?

**Comment by luna404** [comment]
@jeremiehelme, initially the idea was to use different colors for the project dots on the world map. However, we're not using these at the moment. I think for now, you can ignore the project status for the popups.

**Comment by jeremiehelme** [comment]
@luna404 About the workspaces button, should we hide it on certain conditions too ?

**Comment by luna404** [comment]
That's a good question... Right now, any user that has access to a dashboard should also have access to the list of workspaces. (This the logic we use in the permissions)

@SamuelPetragallo I can't think of any scenario where a user would have access to the dashboard but should not see the list of workspaces. Do you agree?
I do wonder about the inverse though. Theoretically, a project admin could remove access to the dashboard but a user could still have access to a workspace, therefore needing access to the workspaces from the popup 🤔

**Comment by luna404** [comment]
> @luna404 About the workspaces button, should we hide it on certain conditions too ?

I just noticed that we do have projects with no workspaces (e.g. Syria). I think it would make sense if the workspace button only shows if there is at least 1 workspace available. Would this be possible to implement?

**Comment by SamuelPetragallo** [comment]
> That's a good question... Right now, any user that has access to a dashboard should also have access to the list of workspaces. (This the logic we use in the permissions)
> 
> @SamuelPetragallo I can't think of any scenario where a user would have access to the dashboard but should not see the list of workspaces. Do you agree?
> I do wonder about the inverse though. Theoretically, a project admin could remove access to the dashboard but a user could still have access to a workspace, therefore needing access to the workspaces from the popup 🤔

Yes, agree: the only case would be if there are no WSs (essentially during project setup, so quite anecdotal), other than that we want users to see what's available (and potentially request access as required)

The inverse case is a strange one: I think that ideally, as long as a user has access to a WS he should also have access to Dahboards: by "principle" we do not want to promote a model whereby users are asked to contribute to the community but can't benefit from contributions from others essentially

**Comment by jeremiehelme** [comment]
Here is what we said during the meeting :

We keep two status : on going and emergency specific
- On going for most of the project
- Emergency specific for special projects, like Covid related project

To be discussed later
- different colors for dots depending on project status, and a legend
- or only one dot but a different layout for the popup to show both projects infos

**Comment by jeremiehelme** [comment]
Adding an error message if the popup doesn't load correctly
![Capture d’écran 2020-04-22 à 10 23 15](https://user-images.githubusercontent.com/2345926/79958815-a7dbbf00-8483-11ea-885c-592a51b1ed76.png)

Adding a message if the project has no HF and no contributors
![Capture d’écran 2020-04-22 à 10 23 26](https://user-images.githubusercontent.com/2345926/79958840-ac07dc80-8483-11ea-953d-0115ea084cd2.png)

**Comment by jeremiehelme** [comment]
Popup title is not displaying on staging

**Comment by luna404** [comment]
Other than the missing title, looks really great. I'll remove the label for now until the title is fixed.

**Comment by SamuelPetragallo** [comment]
Great stuff! Just suggest we rework the messages a bit.

**Comment by jeremiehelme** [comment]
Sure, here are the different messages :

**Loading Failed :**
In Progress
Datas for this project are being collected. When it becomes active this popup will show key metrics and allow access to the project dashboard.


**Target Project :**
In Progress
This project is in the process of being set up. When it becomes active this popup will show key metrics and allow access to the project dashboard.
        
**Ongoing Project without datas** 
In Progress
Datas for this project are being collected. When it becomes active this popup will show key metrics

**Comment by jeremiehelme** [comment]
@SamuelPetragallo I've opened a new issue to discuss these messages 
I'll add it to this milestone if we have time to discuss it before the release

**Comment by jeremiehelme** [comment]
Closing in favor of #422
