### ISSUE TITLE
HeRAMS Sudan conditioning of health services per HFs types 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#228]
Fatma and I had a discussion on the HeRAMS Sudan conditioning of health services per HFs types. From the meeting notes, the following solutions were proposed: 
1. colour code footnotes referring to HF type for each service
2. related service at different levels reordered in sequence
3. nnp as a default answer for each service

Attached screenshots are questions for laboratory services for PHL as an example. I just highlighted the questions with yellow for primary, orange for secondary and red for tertiary for example. And the questions are not yet reordered in sequence. 
<img width="1680" alt="Screen Shot 2019-09-23 at 7 14 59 PM" src="https://user-images.githubusercontent.com/50957748/65424508-506a6780-de3e-11e9-93ca-6a97c0398c2a.png">
<img width="1680" alt="Screen Shot 2019-09-23 at 7 15 05 PM" src="https://user-images.githubusercontent.com/50957748/65424542-5fe9b080-de3e-11e9-97e9-4d31e27de9ec.png">
<img width="1680" alt="Screen Shot 2019-09-23 at 7 15 10 PM" src="https://user-images.githubusercontent.com/50957748/65424560-6a0baf00-de3e-11e9-973f-63f172e9d2c3.png">

**Comment by SamuelPetragallo** [comment]
Thanks for progressing on this and for the hand on tweaking Jeff!

That's the idea, but as a general rule, we should never use formatting in the question text (otherwise we'll break all the labels on frontend) - I suggest we use the "help" field instead as in the example here:

![image](https://user-images.githubusercontent.com/15345099/65428673-1173ec00-de15-11e9-96a4-cfff2d3d058e.png)

**Comment by JeffDotingco** [comment]
Thanks, copy on the suggestion! Is there a need to arrange the questions with related services at different levels reordered in sequence @SamuelPetragallo. Fatma already prepared the list of questions with related services:
<img width="597" alt="Screen Shot 2019-09-23 at 11 13 09 PM" src="https://user-images.githubusercontent.com/50957748/65438283-d0e99200-de57-11e9-9a56-9c9059a33bf2.png">
