### ISSUE TITLE
Multi-language support for platform

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#236]
- [x] Translate platform texts
- [x] Retrieve correct language from LS, with a fallback.
- [x] Solve multi-lingual titles
- [ ] Add support for translating mail templates

**Comment by SamMousa** [comment]
@SamuelPetragallo how do you want to handle things like project & workspace titles? Can we leave these in 1 language?

**Comment by SamMousa** [comment]
This needs testing for identifying strings that are not going through the translation engine.

Test procedure:

1. Go to your account settings
2. Change your language to **Dutch**
3. Since we have no Dutch translations all texts should show as missing.

**Comment by luna404** [comment]
I did some French translations yesterday but when I switch the language to French I all text elements still show as `missing`. Is this expected behavior?

If we have text that should be marked as `missing translations` but is not, how should we report these.

**Comment by luna404** [comment]
Also, we should maybe review some of the base language. There are a lot of similar text strings like `Health facility` and `Health Facility` that should be cleaned up to make translation easier.

**Comment by SamMousa** [comment]
> I did some French translations yesterday but when I switch the language to French I all text elements still show as `missing`. Is this expected behavior?

Yes, translations need to be pulled in manually for now. 

> 
> If we have text that should be marked as `missing translations` but is not, how should we report these.

Create an issue with a link to the page as well as the text, that should allow me to identify which string it is easily. 
Ideally separate issues, but feel free to keep it very short:
```
Title: Missing translatio
Content:
Url: abc
Text: def
```

**Comment by SamuelPetragallo** [comment]
@luna404 I reassign that to you for now for follow-up. I'm of course happy to keep on contributing translation as needed

**Comment by luna404** [comment]
<@SamuelPetragallo how do you want to handle things like project & workspace titles? Can we leave these in 1 language?

Yes, at least for now. Might be something to explore are at a later stage for Arabic/English projects though.

**Comment by SamuelPetragallo** [comment]
I guess project name would be easy and useful to have in other languages (also provided this is the level at which additional languages will be determined). WS less so for now, but yes in the longer run

**Comment by SamMousa** [comment]
Only mail templates are left. Creating a new issue for this.
