### ISSUE TITLE
Text search for Geo1 dashboard filter only searches first level

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#238]
In the dashboard filters, if you search the Geo1 variable, the system currently only searches the first level. For example, if you search for Maiduguri in the Nigeria dashboard it doesn't find any value even though there is a drop-down value "Borno / Maiduguri"

![image](https://user-images.githubusercontent.com/18245059/66579313-f0cdc500-eb7c-11e9-9657-f121b483351c.png)

**Comment by luna404** [comment]
Issue still persists

![image](https://user-images.githubusercontent.com/18245059/82877436-78184f00-9f3a-11ea-880d-7af31dbd69ae.png)

![image](https://user-images.githubusercontent.com/18245059/82877478-84041100-9f3a-11ea-80c5-5840807613a5.png)

**Comment by SamMousa** [comment]
This should work as soon as the commit listed above here shows a green checkmark
