### ISSUE TITLE
Aggregate causes by health facilities

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#246]
I'm putting this here so we don't forget :) (Does not require immediate action)

Causes of non-functionality (i.e all ranking questions) are currently displayed as percentage of total causes reported. This is not ideal as it does not permit to draw direct conclusions on the number of facilities that reported a given cause as an issue.
![image](https://user-images.githubusercontent.com/18245059/68115351-82b8bb80-fef8-11e9-901f-6eaba617e55a.png)

In comparison if causes are aggregated by HF, it allows to draw simple conclusions. (E.g. 42% of HF reported "manque d'intrants" as a cause of non-functionality). 

![Rplot01](https://user-images.githubusercontent.com/18245059/68115257-44bb9780-fef8-11e9-9294-d4fd02bee4c3.png)

**Comment by SamuelPetragallo** [comment]
Fully agree with that. Lets look into this when we've solved more pressing issues together with the "availability score" we ad discussed in our team meeting earlier this year
