### ISSUE TITLE
Delete/replace projects/surveys

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#270]
Issue arose during the Yemen migration, but was also experienced previously (e.g. Nigeria).

As it is no longer possible to change the survey id of a project in HeRAMS, we have been creating new projects when we created new surveys in LS. However, as tokens require to be unique, we have been running into the challenge that workspaces have to be manually removed before they can be imported into the new project. As this is extremely time consuming, other solutions have been proposed below. 

Solutions discussed so far.
1. Enable option to replace surveys again
2. Change uniqueness constraints for tokens (tokens should only be  unique within a project)
3. Avoid using the same tokens when recreating a project. 
4. Add option to batch delete all workspaces of a project. 
5. Change survey id in LS.

**Comment by SamMousa** [comment]
2 will be implemented on staging today.

**Comment by SamMousa** [comment]
Note that this might not be the full fix; it might make sense to take more measures than just having weaker uniqueness constraints.

**Comment by SamMousa** [comment]
On staging you can now delete projects with workspaces; the workspaces will automatically be deleted.

**Comment by luna404** [comment]
I tried it for two projects and I got an error for both of them 

https://herams-staging.org/project/19/delete
https://herams-staging.org/project/18/delete

![image](https://user-images.githubusercontent.com/18245059/73644287-5cc8c180-4675-11ea-8ce1-736981611345.png)

**Comment by SamMousa** [comment]
Ah, that's a different issue: pages, they are not automatically deleted.
Do you want them to be? --> note that this could risk losing valuable configuration.

2 possible fixes:
1. I remove the delete button as long as there are still pages
2. I silently remove the pages just as I do with workspaces

**Comment by luna404** [comment]
Yes, pages should be removed like workspaces.

I still get an error though when trying to remove a project without a dashboard.

https://herams-staging.org/project/32/delete

**Comment by SamMousa** [comment]
Try it again now, I've already deleted project 32.

**Comment by luna404** [comment]
It only works for me if the project has no dashboard. Can dashboards be included in the delete?

**Comment by SamMousa** [comment]
They should be; could still be broken. I'll check

**Comment by SamMousa** [comment]
Ah wait, I didn't implement the dashboard part yet. Are you sure this is wanted? If users accidentally delete it there will be no way to recover the dashboard configuration.

**Comment by luna404** [comment]
@SamuelPetragallo what's your opinion on this? I think deleting a project should delete all dependencies including the dashboard. As it's only global admins who have the permissions to delete projects they should be responsible enough to not deleted it before making a back-up :)

If deleting dashboard pages is not included in the delete, I think we would need at least a warning message why it's not possible to delete a project and an option to delete all dashboard pages at once.
