### ISSUE TITLE
Expand question types available for dashboards

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#271]
The dashboards currently only support single choice and ranking questions. Would it be possible to expand this to also include multiple choice and calculated (equation) questions?

**Comment by SamMousa** [comment]
Ranking questions are currently interpreted as multiple choice, multiple choice is fairly easy to implement.
Equations are harder because we will not know the range of values they can have..

**Comment by SamMousa** [comment]
We already support multiple choice questions, but they are interpret as multiple yes/no questions; that's probably not really useful.
Implementing support for multiple choice is a big thing.

**Comment by SamMousa** [comment]
Need separate issue for each desired question type so that we can discuss implementation details

**Comment by luna404** [comment]
Closing this as separated issues (#471, #472) were created.
