### ISSUE TITLE
Filtering list of workspaces not returning all workspaces

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#275]
Project id = 31

There is a workspace called **Hauts-Bassins / Houet / Do**. If  you filter the list of workspaces by **Do**, said district will not show. However, if you filter **space+Do** it appears.

https://herams.org/project/31/workspaces?Workspace%5Btitle%5D=Do&project-data-provider-page=5&project-data-provider-per-page=10

![image](https://user-images.githubusercontent.com/18245059/72600124-53202980-3913-11ea-9dff-82b8a804dbc1.png)

https://herams.org/project/31/workspaces?Workspace%5Btitle%5D=%20Do&project-data-provider-page=5&project-data-provider-per-page=10

![image](https://user-images.githubusercontent.com/18245059/72600093-426fb380-3913-11ea-9ca9-b5321d0d637a.png)

As users are expected to search for their workspace using the district name (i.e. Do), is there a way you can change the filter behavior?

**Comment by SamMousa** [comment]
Please test this on staging and if it doesn't work there add links to those cases instead.
