### ISSUE TITLE
Validation rule for GPS coordinates in LS

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#284]
This is not an issue!

I was asked by Burkina Faso to implement a validation rule for GPS coordinates to reduce the risk of user errors. As i think this would be useful for other countries as well, I thought I post it here.

Rules implemented:
1. Assure that both Latitude and Longitude are entered
2. Limit latitude to a specific range
3. Limit longitude to a specific range. 
4. Makes sure latitude and longitude value contain at least 4 decimal places. 

![image](https://user-images.githubusercontent.com/18245059/72906175-177dc900-3d32-11ea-9330-035c7e19f63f.png)

Question validation equation: 
`(is_empty(MoSDGPS_SQ001) and is_empty(MoSDGPS_SQ002)) or ((MoSDGPS_SQ001>=lat_min and MoSDGPS_SQ001<=lat_max) and (MoSDGPS_SQ002>=long_min and MoSDGPS_SQ002<=long_max) and regexMatch('/^([-+]?)([\d]{1,3})(\.)(\d{4,})$/',MoSDGPS_SQ001) and regexMatch('/^([-+]?)([\d]{1,3})(\.)(\d{4,})$/',MoSDGPS_SQ002))`

Question validation tip: 
en:
`{if((is_empty(MoSDGPS_SQ002) and !is_empty(MoSDGPS_SQ001)) or  (is_empty(MoSDGPS_SQ001) and !is_empty(MoSDGPS_SQ002)), 'Please enter a valid Latitude and Longitude.<br>','')}
{if((is_empty(MoSDGPS_SQ001) or(MoSDGPS_SQ001>=lat_min  and MoSDGPS_SQ001<=lat_max)), '','Latitude entered is not valid.<br>')}
{if((is_empty(MoSDGPS_SQ002) or(MoSDGPS_SQ002>=long_min and MoSDGPS_SQ002<=long_max
)), '','Longitude entered is not valid.<br>')}
{if(is_empty(MoSDGPS_SQ001) or regexMatch('/^([-+]?)([\d]{1,3})(\.)(\d{4,})$/',MoSDGPS_SQ001),'','Latitude requires at least <b>4</b> decimal places')}
{if(is_empty(MoSDGPS_SQ002) or regexMatch('/^([-+]?)([\d]{1,3})(\.)(\d{4,})$/',MoSDGPS_SQ002),'','Latitude requires at least <b>4</b> decimal places')}`

fr:
`{if((is_empty(MoSDGPS_SQ002) and !is_empty(MoSDGPS_SQ001)) or  (is_empty(MoSDGPS_SQ001) and !is_empty(MoSDGPS_SQ002)), 'Veillez à saisir  une valeur pour la latitude et la longitude.<br>','')}
{if((is_empty(MoSDGPS_SQ001) or(MoSDGPS_SQ001>=lat_min and MoSDGPS_SQ001<=lat_max)), '',"La latitude saisie n'est pas valable.<br>")}
{if((is_empty(MoSDGPS_SQ002) or(MoSDGPS_SQ002>=long_min and MoSDGPS_SQ002<=long_max)), '',"La longitude saisie n'est pas valable.<br>")}
{if(is_empty(MoSDGPS_SQ001) or regexMatch('/^([-+]?)([\d]{1,3})(\.)(\d{4,})$/',MoSDGPS_SQ001),'','La latitude nécessite au moins <b>4</b> décimales.<br>')}
{if(is_empty(MoSDGPS_SQ002) or regexMatch('/^([-+]?)([\d]{1,3})(\.)(\d{4,})$/',MoSDGPS_SQ002),'','La longitude nécessite au moins <b>4</b> décimales<br>.')}
`

**Comment by SamuelPetragallo** [comment]
Great to enforce min/max for coordinates! Was that not possible through the advanced parameters?
