### ISSUE TITLE
Content disappearing behind vertical scrollbar

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#285]
![image](https://user-images.githubusercontent.com/547021/72908521-ddaec180-3d35-11ea-8e91-f112d848a5c6.png)

https://www.herams-staging.org/project/index

We can fix this by using padding, but it might make more sense to put the scrollbar in the content area...
That way we also keep the sidebar menu footer visible at all times.

**Comment by jeremiehelme** [comment]
Pushed in #388
