### ISSUE TITLE
Dashboard management permissions

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#297]
> Project level write access (edit properties) should be split from edit rights to the dashboard. Users should be able to edit the dashboard without having access to the project settings. 

Would this just be one permission to manage dashboards for a project? It will be a lot of work management wise if you want to do permissions on individual pages / charts.

I propose one permission that allows the user to manage dashboards (create / import / export / delete / update) for pages & elements.

**Comment by luna404** [comment]
One permission (incl. create, edit, delete, update) is fine.

I tried assigning the new option "Manage dashboards in the project" to a user, but it doesn't seem to be granting the user access to modify the project just yet.

**Comment by SamMousa** [comment]
Ah wait, it wont allow the user to modify project properties, so while they are allowed to create pages they can't get to the link :)

**Comment by SamMousa** [comment]
Have created a separate icon (paint-brush) that will show and take you to a page where you can manage the dashboard.

**Comment by luna404** [comment]
It works for me as an admin, but when I assign the permission to manage the dashboard to another user, that user is getting an error (You are not allowed to perform this action).

**Comment by SamMousa** [comment]
This should be fixed now.

**Comment by luna404** [comment]
There is an other issue here. Users with permission to manage dashboards can create new elements but they cannot edit existing elements (forbidden error).

**Comment by SamMousa** [comment]
Should be fixed now!

**Comment by luna404** [comment]
It's possible to edit an element but the preview is only working for admins. For others it shows a forbidden error.
![image](https://user-images.githubusercontent.com/18245059/73947549-eb4c7580-48f7-11ea-8cee-8e915373f487.png)

Similarly, the option to edit an element from the dashboard is only available to global admins.

**Comment by SamMousa** [comment]
@luna404 you can test the 2 points you mentioned now.

Next time if something doesn't work make sure you remove the label otherwise I won't know I'm supposed to work on it.
