### ISSUE TITLE
Workspaces - integration

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#303]
Here is the page I called Workspaces during the meeting :

<img width="1680" alt="workspace" src="https://user-images.githubusercontent.com/2345926/73752191-c2de4300-4760-11ea-8072-91507d93cc5f.png">

And this is what the mockup for this page looks like :
![3 HeRAMs_admin_Project](https://user-images.githubusercontent.com/2345926/73751876-3cc1fc80-4760-11ea-8df1-57725cc9d86f.jpg)

We discussed with Caroline about the changes made in the new mockup here :
[Google doc](https://drive.google.com/file/d/1EqaOZsxMpYqVdHYYeXC6v063fLuuqdt0/view)

Could we discuss first which changes should be prioritized, and then how to proceed to implement them ?

**Comment by SamMousa** [comment]
I have no input on priorities, when you want my specific feedback for each page create an issue for it.
Regarding the mockup shown above, it misses a lot of stuff and uses some unknown definitions:
- Where do actions go?
- Do we need bulk actions? (The checkboxes seem to indicate this) If so, this is a technical feature that is outside of the scope of design, so we'd need another issue for that where I first implement the functional side before we revert back here to discuss the visual part.
- What is `default` in the context of a workspace?
- What does the icon in front of Unicef mean? if it is just there to when it's the default it seems a bit redundant.
- What are the interactive elements? The image shows a highlight suggesting something happens when you click, but we need to define what.


In case you just want to add a column or change the column order tell me what you need me to change and I'll implement it; ordering is simple, adding columns is simple if the data is "simple".
Note that the above mock up hides the ID which I strongly recommend against, it is prettier but makes supporting users way harder.

**Comment by jeremiehelme** [comment]
According to me, here are the functionalities we could add first :

**Menu**
- back button at the top
- administration button under the logo

**Layout**
- having a white bar at the top, as on the project pages. It could contain the buttons, and a search bar if needed. Having this principle for all admin pages would allow user to understand what he can more easily


**List**
- Regrouping actions buttons in a small popover would be a good first step


**About your questions**
_Do we need bulk actions?_ 
- I don't know if bulk action is a priority. We should discuss that with Caroline / Samuel

_What is default in the context of a workspace?_
It is not important for now

_What are the interactive elements? The image shows a highlight suggesting something happens when you click_
I agree, it's not clear.

**Comment by luna404** [comment]
Adding the word document that might help clarify some of the issues surrounding the proposed new layouts for the workspace page. 
[doc](https://drive.google.com/open?id=1EqaOZsxMpYqVdHYYeXC6v063fLuuqdt0)

**Comment by jeremiehelme** [comment]
Here is the current screen, to compare with the mockup

<img width="1678" alt="Capture d’écran 2020-07-07 à 10 35 44" src="https://user-images.githubusercontent.com/2345926/86749592-a90d9880-c03d-11ea-9ecb-d9638b1aaf46.png">

**Comment by jeremiehelme** [comment]
@luna404 The mockup is still very different from the site, can we discuss what should / can be done ?

**Comment by luna404** [comment]
@jeremiehelme I think we discussed this yesterday. Please look at the word document and focus on the points that can be achieved without or with minimal involvement of @SamMousa.

**Comment by jeremiehelme** [comment]
Added a top bar to the workspace screen, with the actions buttons and a return to dashboard

Will add the number of health facilities, and (if possible) a search bar

<img width="1680" alt="Capture d’écran 2020-07-31 à 16 23 38" src="https://user-images.githubusercontent.com/2345926/89045964-a5271a80-d34c-11ea-9781-93cfa8c9bd22.png">

**Comment by jeremiehelme** [comment]
Moved the links from the workspaces pages top bar to the menu, and moved the statistics back on the left

![Capture d’écran 2020-09-30 à 15 12 11](https://user-images.githubusercontent.com/2345926/94691863-23467400-0332-11eb-91cb-a7d0be871a7c.png)

@SamMousa I created a /view route for the workspaces
https://herams-staging.org/workspace/5530/view 

For now it's a copy of /limesurvey, but we may need it later if we want to display other informations

**Comment by jeremiehelme** [comment]
Here is the mockup

- moved the dashboard link closer to the project name, as it is what it is related to
- added a back button in the left menu, next to the workspace name

- clicking on the project name leads to the workspace list for this project, as well as clicking on the back button

![HeRAMs_nav](https://user-images.githubusercontent.com/2345926/95837117-84157980-0d40-11eb-8270-2ad7e02284ec.jpg)

**Comment by jeremiehelme** [comment]
Here are the mockups for the admin part, without the left menu.
I've tried to explain the process. Please give your opinion / suggestions

The intention was to better separate the screens where the users **visualize datas** and the ones where they **edit datas**.

Today, we have two screens designed to **visualize datas** : The worldmap and the project dashboard.
The other screens are made for **editing datas** 

Most users visit the site to edit datas. It should be as easy as possible for them to access the screen where they can do their work


 
![menu](https://user-images.githubusercontent.com/2345926/96462936-740d0680-1226-11eb-95d6-083c10d92142.jpg)

Clicking on the admin button will lead to one of those screens depending on your admin level
(You can then navigate using the breadcrumb, if you need to access other projects / workspaces)

if you manage more than one project, you'll arrive on the global admin page :

![3--Admin](https://user-images.githubusercontent.com/2345926/96461554-cfd69000-1224-11eb-9d05-6afb2736428a.jpg)

if you manage only one project, and multiple workspaces, you'll arrive at the project level :

![4--Project](https://user-images.githubusercontent.com/2345926/96461557-d107bd00-1224-11eb-8424-7ce44a189f9a.jpg)

if you manage only one workspace, and multiple health facilities, you'll arrive at the workspace level :

![5--Workspace](https://user-images.githubusercontent.com/2345926/96461566-d1a05380-1224-11eb-93ed-1d9a23e974e5.jpg)

if you manage only one health facility, you'll arrive at the health facility level :

![6--Health-Facility](https://user-images.githubusercontent.com/2345926/96461757-10cea480-1225-11eb-82b0-a7058818c573.jpg)


On every screen, the elements have the same place 

![actions](https://user-images.githubusercontent.com/2345926/96464333-f8ac5480-1227-11eb-98ef-b73c2fff1958.jpg)

1 Navigation
2 Edit the current element
3 Statistics about the current element
4 Synchronize or download
5 Actions on the current element
6 Go back to the world map

**Comment by luna404** [comment]
Generally agree wit everything, I just have a few questions:
- What is the difference between the edit button next to the project name (#2) and the one on the right (next to the sharing button)?
- I see you added the sync button to the project level. While we would love to have an option to sync all workspaces of a project together, as far I understand this will not be be possible as some of the project are relatively big.
- You're mock-ups miss the "backend administration" link. From a workflow perspective, I think it would make most sense to add it at the project level.
- For the admin dashboard, only the list of projects should be visible to all users, the rest depends on their permissions.

**Comment by jeremiehelme** [comment]
- The one next to the project name allow to edit the project, the one on the right to edit the dashboard. I agree they look very similar, there is something to be done
- Ok
- Let's discuss that
- I agree. If the user doesn't have the permissions, we will take the whole width to display the list of projects.  If they have other options, we can add cards

**Comment by jeremiehelme** [comment]
Improvement on the project screen and dashboard, as an example

Project :
- Moved the navigation from the top bar to the content block, as tabs
Those buttons act on the content
It gives more space to use label and icon button

- Added the view icon to go back to the project dashboard, and the pencil to go to the administration of the project
We should always use the view icon / edit icon to switch between viewing / editing an element
We should use the wheel to go to the admin side

![4--Project](https://user-images.githubusercontent.com/2345926/97281641-0e300880-183e-11eb-88cb-18586d657b96.jpg)


![3-1-Dashboard](https://user-images.githubusercontent.com/2345926/97281652-10926280-183e-11eb-9649-cfd167b9e8b0.jpg)

**Comment by jeremiehelme** [comment]
Here it is without the top bar 

![4-2-Project](https://user-images.githubusercontent.com/2345926/97705320-2c06a300-1ab4-11eb-92d7-1c4cdc08d035.jpg)

![5-2-Workspace](https://user-images.githubusercontent.com/2345926/97705323-2dd06680-1ab4-11eb-985f-ae1401942dd2.jpg)

![6-2-Health-Facility](https://user-images.githubusercontent.com/2345926/97705327-2e68fd00-1ab4-11eb-9b00-1dfd58bec1db.jpg)

**Comment by jeremiehelme** [comment]
Here is what I had in mind before creating the mockup 

**What is the most important**
* Data collection
* Data visualization

Data collection (Edition) screen should facilitate the modification
Visualization screen should facilitate the analysis

We should give users the shortest path to the screen where they can do their work

**Types of users**

* Global admin
    * access to everything
* Project admin :
    * 1 or several projects
* Workspace admin
    * 1 or several workspaces
* HF admin
    * 1 or several HF
* Visitor
    * just visualization

The HF admin are the most important group in term of number, and they enter the data, which is at the base of the platform
They should have the shortest path to edit their datas



**Actual**
* The path to the relevant screen for the HF Admin is the longest, unless they use the favorites :
    * Admin Dashboard > List of projects > list of workspaces > list of HF > HF
    * My favorites > list of HF > HF
* Most of the Editing screens are part Visualization screens
* Navigation is not always straightforward
* Buttons positions, icons and labels can be improved


**Suggestions**
* Path to Edition screen could be shorter
* Edition screens could be improved for data editing
* Visualization screens could be created / improved for data analysis


**Solutions proposed**
* Visually differentiate Edition and Visualization to indicate clearly in which mode we are
* Shorten the path to relevant screens :
    * Different options :
        * by clicking the admin button :
            * HF admins should be redirected to the HF list
            * Workspace admin should be redirected to their workspace, or the workspaces list
            * Project admins should be redirected to their project, or the projects list
            * Global admins should be redirected to the admin dashboard
        * by creating a admin dashboard with links to the relevant screen
* Simplifying the navigation (Breadcrumb / menus / buttons / icons)
* Remove the Visualization part of the the Editing screen
* Create Visualization screens if/when needed

**Comment by SamMousa** [comment]
What do you mean by this?
> Remove the Visualization part of the the Editing screen

**Comment by jeremiehelme** [comment]
It seems that the actual admin screens are used both for visualizing and editing data
If you want informations on a health facility for example, you have to got to the admin screen. There is no equivalent of a project dashboard for a health facility. and that's why we have stats on those admin screen, I think

By "Removing the Visualization part", I mean removing the stats mostly, and create a dedicated screen for visualization

**Comment by jeremiehelme** [comment]
Here are the mockup updated, with the following modifications
- project name as title for the dashboard
- simplified user menu
- icons for action buttons
- user and global admin access
- example of table without icons (on Project page)



![3-1-Dashboard](https://user-images.githubusercontent.com/2345926/99996976-c78de980-2dbc-11eb-9a2b-b2fc1bdad168.jpg)
![3-2-Projects](https://user-images.githubusercontent.com/2345926/99996987-cc529d80-2dbc-11eb-8da7-3ac5ca5b575d.jpg)
![4-2-Project](https://user-images.githubusercontent.com/2345926/99997002-cfe62480-2dbc-11eb-9872-3a74b9f8e6c7.jpg)
![5-2-Workspace](https://user-images.githubusercontent.com/2345926/99997004-d2487e80-2dbc-11eb-90a1-4072fe756224.jpg)
![6-2-Health-Facility](https://user-images.githubusercontent.com/2345926/99997161-0e7bdf00-2dbd-11eb-978b-8745f187a7ea.jpg)

**Comment by luna404** [comment]
- I thought we agreed to remove the action button column at the project level. 
- The project level misses the "survey administration" tab
- Can you explain how you envision the dashboard tab will work? 
- For the last one, I don't think we need the delete and add response button there, but an a way to return to the list of health facilities. 
- For the icons in the top right corner. Where would user management be? Also the language has been removed. This should happen once we have a better solution. Right now I would prefer if it can stay.

**Comment by luna404** [comment]
For the workspace page, can we add tab for LSL/HeRAMS data comparison 

https://herams-staging.org/workspace/5150/responses

@jeremiehelme there is a 7th icon that is only visible to global admins and allows comparing data in LS and HeRAMS. (This only relevant while we use LS.)

**Comment by luna404** [comment]
I have split issues related to the admin pages into independent issues (see issues #686-691)
