### ISSUE TITLE
Dashboards no longer "open" on staging

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#308]
With the new permission system, it seems that users need to be granted read/view access in order to see view the project dashboard. I was under the assumption that all project should remain open (users should be able to view any dashboard) unless a project has been set to "closed" or "private". 

@SamuelPetragallo can you confirm this is indeed the desired behavior?

@SamMousa this goes back to the questions in the word document. In the future we would like to create so called "private" or "closed" project. For these projects, access to the dashboard is limited to users that are granted view (read) access. Hence the reason why we need this option in the permissions. However, by default all project should remain open. Thus, all users should have access.

**Comment by SamMousa** [comment]
If project dashboards are open by default then what does the **project viewer** role add?

**Comment by luna404** [comment]
You are right that currently this role does not provide anything. However, moving forward we will need to add an option to distinguish between "open" and "close" projects. For "close" projects, project admins will have to grant view access using the project viewer role.

**Comment by SamuelPetragallo** [comment]
Agree. Closing them up however means we'll need identified Project Owners/Admin to who access requests can be channeled. Same will be needed for WS (and that links to the view WS permission (discussed  that relates to the development of WS dashboard), and it's actually the approach that we had implemented in Prime

**Comment by SamMousa** [comment]
I have started on a list of definitions that one can use for reference in case something is not clear: https://github.com/WorldHealthOrganization/herams-backend/wiki/List-of-definitions 
I will attempt to use **bold** text when using terms from this list.

I have implemented project visibility with 3 levels:
![image](https://user-images.githubusercontent.com/547021/73843619-4494a600-481f-11ea-8805-023c8b67a512.png)

Hidden projects will not show up anywhere unless people have **Implicit Permission** to read them.
Public and private projects will show up in lists and on the world map for **Everyone**.
For private projects people will not be able to view the dashboard unless they have **Implicit Permission** to read it.

**Comment by luna404** [comment]
I will do some more testing, but it seems to working fine.

For private project, if a user doesn't have permission to view the dashboard, they get a `forbidden` error message. The end goal here would be that users would be able to contact the project owner. As we currently don't have project owners could 
  1. the error message be change to something along the line `You don't have permissions to view this dashboard. Please contact herams@who.int for support.`, or
  2. the details button be hidden so users don't see that there is a dashboard available. 

@SamuelPetragallo I think originally we said, as soon as a user has any permission to a project they should see the dashboard (current behavior implemented). However, during our discussion last week, we said only users with explicit `read` permission should view the dashboard, which would mean a users could have `edit` rights to a workspace but cannot see the dashboard. Can you confirm that this is indeed the desired behavior?

**Comment by SamMousa** [comment]
How are you getting a forbidden message? There should be no links to the dashboard

**Comment by luna404** [comment]
If a project is set to `private` and a user with no permissions to this project is trying to open the dashboard form the world map, you get a `forbidden` error. 

You can test it by logging in as Test User and open the Comoros Dashboard
https://herams-staging.org/project/27

**Comment by SamuelPetragallo** [comment]
Great progress on this 

> @SamuelPetragallo I think originally we said, as soon as a user has any permission to a project they should see the dashboard (current behavior implemented). However, during our discussion last week, we said only users with explicit `read` permission should view the dashboard, which would mean a users could have `edit` rights to a workspace but cannot see the dashboard. Can you confirm that this is indeed the desired behavior?

No, the idea is that whoever shares data in a project, should be able to see the overall results of the project, i.e. whoever contributes data through a WS (or more), should automatically be granted access to project dashboards.

The problem we get if we implemented that project level permission automatically is that we then effectively allow WS owners to grant access to the project dashboard (on behalf of Project Owners/Admins).

It is then a question of whether we still want Project Owners/Admins to keep some authority on that. Options could be that to be granted rights in a WS a user would first need to be granted rights at the project level (a bit of a nightmare process wise) or probably easier: simply ensure that Project Owners/Admins can get a full view and hands on all users accessing the project at any point in time

- ?

**Comment by luna404** [comment]
@SamuelPetragallo could you confirm that is the desired behavior.  

1. **Project is open**: All users, regardless of their permissions to the project, have access to the dashboard.
2. **Project is private or hidden**: Only user with explicit permissions to view the dashboard can access it. This means it would be possible for a data contributor to not be able to view a dashboard if permissions were not granted by the project admin. 

>  simply ensure that Project Owners/Admins can get a full view and hands on all users accessing the project at any point in time 

I think we were discussing this before, It would be useful for project admins/owners to be able to view a list of users having access to their project including what permissions. This would also address you the point you made above.  

We could also consider sending a notification to the project admin/owner informing them of a new user having been granted access to their project.

**Comment by SamMousa** [comment]
Maybe just allow a workspace dashboard? That is a feature we need anyway right?

**Comment by SamMousa** [comment]
It is easy to implement if we just show the project dashboard with a data filter

**Comment by SamuelPetragallo** [comment]
> @SamuelPetragallo could you confirm that is the desired behavior.
> 
> 1. **Project is open**: All users, regardless of their permissions to the project, have access to the dashboard.
> 2. **Project is private or hidden**: Only user with explicit permissions to view the dashboard can access it. This means it would be possible for a data contributor to not be able to view a dashboard if permissions were not granted by the project admin.
> 
> > simply ensure that Project Owners/Admins can get a full view and hands on all users accessing the project at any point in time
> 
> I think we were discussing this before, It would be useful for project admins/owners to be able to view a list of users having access to their project including what permissions. This would also address you the point you made above.
> 
> We could also consider sending a notification to the project admin/owner informing them of a new user having been granted access to their project.

Agree it would be useful for admin to be able to view a list of users having access to their project including what permissions.

Regarding permissions of WS contributors: I would like that any WS contributor has access to projects dashboards by default (this will be one of the points of the data policy as well - it's a matter of fairness and a way of increasing pressure on data quality/transparency)

**Comment by luna404** [comment]
Right now all dashboards are open, regardless of the project status.

The desired behavior should be as follows:

Project is open: all users have access
Project is private: project is visible, but only user with at least one permission have access to the project dashboard. 
Project is hidden: The project only appears to having at least one permission assigned at the project or workspace level. 

For the private projects, as we don't have an option yet to message the project admin, I would suggest to have an message displayed asking them to contact herams@who.int to request access.
