### ISSUE TITLE
Data cache refresh for Burkina Faso

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#312]
Until the data refresh function is released, would it be possible to implement the same temporary fix that was put in place for Mali for Burkina Faso (project 31)? I think the data for Mali is now refreshing hourly or so.

**Comment by SamMousa** [comment]
Actually all data is refreshed every 2 hours.

**Comment by luna404** [comment]
I had to manually refresh all the workspaces yesterday as none of the data was being updated on the dashboard. They have been doing data collection for over a week now so some thing with the 2h refresh doesn't seem to work.

**Comment by SamMousa** [comment]
I realize now that you are talking about PROD not staging... Have added the workaround to burkina faso on PROD.

**Comment by luna404** [comment]
I just had a look at the data for BF. The last record was updated at 13.32 today (id=11948). If you look at the `last update` column in the workspace table it states 8:31 today. Shouldn't it update more frequently?

https://herams.org/project/31/workspaces?Workspace%5Bid%5D=&Workspace%5Btitle%5D=Centre%20%2F%20Kadiogo%20%2F%20Baskuy

https://ls.herams.org/admin/responses/sa/browse/surveyid/341175

**Comment by SamMousa** [comment]
Hmm, as far as I can tell, automatic data pushing has not worked for staging since December 6th.
With the release we pushed that bug through to production.

I'll have a look, but this might take more time to fix.

**Comment by SamMousa** [comment]
I think this is working now, both on prod and staging. Please confirm!

**Comment by SamMousa** [comment]
Can someone confirm please?
