### ISSUE TITLE
Permission table layout enhancements

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#315]
Would it be possible to make a few improvements to the way permissions are displayed?
- Email should be displayed either in brackets or in a separate column. We have users who registered multiple time with different emails. Only having the name makes it difficult to identify the person. 
- As the permission are more granular now, we also have more permissions applied. Could permission be sorted by users? As you can see in the screen shot below, it's difficult to identify all the permissions granted to a users.
- Would be possible to use the same table layout as used for the WS/project which allows filtering the data?

![image](https://user-images.githubusercontent.com/18245059/74140337-2bac3c00-4bf5-11ea-94ba-464e5c16b400.png)

**Comment by SamMousa** [comment]
- [ ] Add email to table
- [ ] Redesign table

**Comment by jeremiehelme** [comment]
@SamMousa I'm not sure how to have the ordering and search functions we have in the project list.

- I've added a Sort object to the dataProvider. 
- It only contains relations between projects, users and permission, so I can't sort directly by user name or email.

Is it possible to specify a property in the source object, which is a User, to sort the table with ?

Here is the Sort, i've tried with source_id and permission, which works but is not very useful 

`$dataProvider = new ActiveDataProvider([
                'query' => $this->model->getPermissions()
            ]);`
      `$sort = new Sort([
            'attributes' => [
                'source_id',
                'permission'
            ]
        ]);`
        `$dataProvider->setSort($sort);`

Thank you for your help

**Comment by SamMousa** [comment]
The table structure needs to be changed away from showing each permission in a line.
Instead there should be a column for each permission and a row for each user.
I have some ideas for this.

**Comment by luna404** [comment]
Looks great, but I can't grant permissions to a new users at the project level. The add button doesn't seem to work. 

On a workspace level, I get an error 
https://herams-staging.org/workspace/5417/share

> Error: Class 'kartik\widgets\ActiveForm' not found in /home/www/sites/herams-staging.org/protected/views/workspace/share.php:35
Stack trace:
#0 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/www/sites...', Array)
#2 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/www/sites...', Array, Object(prime\controllers\WorkspaceController))
#3 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('share', Array, Object(prime\controllers\WorkspaceController))
#4 /home/www/sites/herams-staging.org/protected/components/Controller.php(36): yii\base\Controller->render('share', Array)
#5 /home/www/sites/herams-staging.org/protected/controllers/workspace/Share.php(66): prime\components\Controller->render('share', Array)
#6 [internal function]: prime\controllers\workspace\Share->run(Object(prime\components\NotificationService), Object(yii\web\Request), Object(SamIT\abac\AuthManager), Object(yii\web\User), 5417)
#7 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#8 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#9 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('share', Array)
#10 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('workspace/share', Array)
#11 /home/www/sites/herams-staging.org/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /home/www/sites/herams-staging.org/protected/entry.php(27): yii\base\Application->run()
#13 /home/www/sites/herams-staging.org/protected/entry.php(28): {closure}()
#14 /home/www/sites/herams-staging.org/public/index.php(2): include('/home/www/sites...')
#15 

>

**Comment by luna404** [comment]
Also, I wonder whether it would be more user friendly to have a delete option rather than having to revoke all existing permissions granted to a user.

**Comment by SamMousa** [comment]
The button now works for projects & workspaces.
