### ISSUE TITLE
Tab titles

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#317]
If you filter the list of workspaces, the tab title changes to `pencil-alt`. Would it be possible to change this to something more useful? Also, would it be possible to display the HeRAMS logo the tab?

![image](https://user-images.githubusercontent.com/18245059/74150222-beef6c80-4c09-11ea-93cf-39e908842444.png)

**Comment by jeremiehelme** [comment]
@SamMousa 
There is a title attribute in the head and it's value is 
`<title><?=Html::encode($this->title ?: app()->name); ?></title>`

Where does $this->title is set for a particular page ?
 
I'll change that with only the app()->name for now, it will fix the issue, and we can add the page title back when it is set correctly

**Comment by jeremiehelme** [comment]
Moving the title to css3-grid seems to work

**Comment by jeremiehelme** [comment]
**fix #329**

**Comment by JeffDotingco** [comment]
This is working, filtering of workspaces and the pencil-alt is not seen anymore

**Comment by luna404** [comment]
@jeremiehelme the tab titles still states pencil-alt when you sort the list of workspaces (both on staging and prod). 

![image](https://user-images.githubusercontent.com/18245059/75874586-519eb800-5e12-11ea-8eae-d720dba9ebe0.png)

**Comment by jeremiehelme** [comment]
@luna404 I don't see this problem anymore
Which browser do you use ? on PC or Mac ?

Thank you,

**Comment by JeffDotingco** [comment]
@jeremiehelme, it's the name of the page that is "pencil-alt" when you sort the list of the WSU. Please see screenshot 
<img width="1680" alt="Screen Shot 2020-03-09 at 4 34 42 PM" src="https://user-images.githubusercontent.com/50957748/76195975-586b6780-6224-11ea-925f-640b7024de34.png">

**Comment by jeremiehelme** [comment]
Thank you @JeffDotingco and @luna404 
I tried on Chrome / Mac like you Jeff, I don't see the problem anymore

Can you empty your cache ? (CTRL + SHIFT + Reload the page)

**Comment by JeffDotingco** [comment]
I used command + R of loading HeRAMS in Mac @jeremiehelme, and the pencil-alt is still there. I also cleared the chrome settings in cached images and files.
