### ISSUE TITLE
Response Picker Plugin / make the "Last / True-False" more explicit

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#321]
This field allows filtering all responses of the response table to the latest update of each health facility only (hiding older versions).

The function is very much needed and appreciated, but not explicit enough.

We can discuss how to best improve this. Various options (that may be implemented gradually) include:
1. relabeling the column and values to make them more explicit
2. allowing to set a default value for that filter (specific request from Yemen) in the plugin configuration?
3. graphically reworking this in the table: e.g. for HFs with more than one version, showin the lates by default, but with a "+" sign aside indicating there are more versions (and opening up those versions as a sub-list)

Else?

**Comment by jeremiehelme** [comment]
@SamuelPetragallo N°1 can be done quickly. how should I call the column ? Last Status update ?

**Comment by jeremiehelme** [comment]
Here it is, 

Clicking an element in the list opens the sub listing, showing versions of the HF responses
Any suggestion is welcome !

![Capture d’écran 2020-04-16 à 17 58 03](https://user-images.githubusercontent.com/2345926/79478922-498a8880-800c-11ea-923a-41856f425a51.png)

![Capture d’écran 2020-04-16 à 18 01 38](https://user-images.githubusercontent.com/2345926/79478968-59a26800-800c-11ea-9572-d78228c780fa.png)

**Comment by SamuelPetragallo** [comment]
1. I think we need an action/button on the top element that indicates there's a sublist and that allows opening it up (there was something on Bruno's mockups)

2. we still need to actions for the elements of the sublist

**Comment by jeremiehelme** [comment]
@SamuelPetragallo 
1 - Yes, It's the first column on Bruno's mockup. It's a Plus sign, I'm looking for a way to separate it from the action buttons

2- What are the possible actions for the sub-elements ? I don't have them on the mockup

**Comment by SamuelPetragallo** [comment]
Same actions as for the top element (view, edit, update, delete)

**Comment by SamMousa** [comment]
What does updating an old record do?

**Comment by SamuelPetragallo** [comment]
> What does updating an old record do?

New record, new record ID, new update.
But agree that use case not really clear for that if that's where you're headed.

I'm not against removing that option for older records. @luna404 @JeffDotingco other views on this?

**Comment by SamMousa** [comment]
It will cause data loss because the newest record is then based on older information

**Comment by jeremiehelme** [comment]
@SamuelPetragallo @SamMousa @luna404 @JeffDotingco Can we discuss that together ?

Here is my understanding and a mockup to help visualize

We have a list of Health Facilities. 
They have a number of records (answers to the questionnaire)
A record represent the state of a HF at a given time
A new record represent an update of the state of the HF, 
An older record is 'obsolete', and is kept just for reference ?

We can visualize any record
we can edit any record (?)
We can delete any record (?)
We can add a record, and it should use the most recent record as a base (?)

In the mockup, I tried to show the relation between a HF and it's records

![Capture d’écran 2020-04-20 à 16 39 16](https://user-images.githubusercontent.com/2345926/79765302-b791c100-8326-11ea-8410-2a524b3e4a01.png)

**Comment by jeremiehelme** [comment]
Remove the action button on a container
Order by date, and by response ID if the date are equal 
The last update date should be the date given by the user, and not the last time the response has been updated

Find a way to filter by response, not container
- suggestion : add a button to display all responses (unfold all containers)

**Comment by SamuelPetragallo** [comment]
> It will cause data loss because the newest record is then based on older information

Make sense: we've agreed to limit that function to the latest record

**Comment by SamuelPetragallo** [comment]
> Remove the action button on a container
> Order by date, and by response ID if the date are equal
> The last update date should be the date given by the user, and not the last time the response has been updated
> 
> Find a way to filter by response, not container
> 
> * suggestion : add a button to display all responses (unfold all containers)

Just to specify that the date to be used for ordering is the "Update" standard question

**Comment by SamuelPetragallo** [comment]
@jeremiehelme @SamMousa not sure how o handle this issue. Its's all work in progress (almost done I guess now) on the Resp Picker. @jeremiehelme can you please check where we are and advise? Thanks!

**Comment by jeremiehelme** [comment]
Here are a few examples, working with the real datas
I have to add an icon to the first column, so that we know it can open  

We can discuss it together if you have other ideas 

**Cox's Bazar** 
https://herams-staging.org/workspace/4893/limesurvey
https://ls.herams.org/survey/index/sid/358212/token/zYtct6SDlMJy6j0/newtest/Y
https://ls.herams.org/survey/index/sid/358212/token/zYtct6SDlMJy6j0/newtest/Y?test=ResponsePicker

**Burkina Faso**
https://herams-staging.org/workspace/6489/limesurvey
https://ls.herams.org/survey/index/sid/341175/token/pHUi1Xny0OMCs9e/newtest/Y
https://ls.herams.org/survey/index/sid/341175/token/pHUi1Xny0OMCs9e/newtest/Y?test=ResponsePicker

**Comores**
https://herams-staging.org/workspace/890/limesurvey
https://ls.herams.org/survey/index/sid/363113/token/cpFmM8eTWiQ8FTr/newtest/Y
https://ls.herams.org/survey/index/sid/363113/token/cpFmM8eTWiQ8FTr/newtest/Y?test=ResponsePicker

**Mali**
https://herams-staging.org/workspace/5402/limesurvey
https://ls.herams.org/survey/index/sid/996483/token/Zh4kPqzCAGUJhNa/newtest/Y
https://ls.herams.org/survey/index/sid/996483/token/Zh4kPqzCAGUJhNa/newtest/Y?test=ResponsePicker


<img width="1680" alt="Capture d’écran 2020-05-28 à 16 09 35" src="https://user-images.githubusercontent.com/2345926/83152049-a4c89400-a0fd-11ea-8079-e2e0ec27488e.png">

**Comment by SamuelPetragallo** [comment]
@jeremiehelme think we said we'd organise another round of discussion on this to fine tune it a little (maybe). Can you please send an invite to the same group as first round of talks? Thanks

**Comment by luna404** [comment]
1. @jeremiehelme do you need the dt_rowid column for the aggregation of the data or could it be hidden from users?

2. As it is difficult to align the column correctly, would it be easier to just add the field name to the date of update. Similar to what you did with the response id. 

This is more of a process question. Currently the `add a new response button` is always visible even if `update` has not been enabled in LS. If we are changing all surveys to always allow `edit` and `update` then I guess this is fine. However, if we are taking into considerations countries such as Yemen, where they would like to restrict access, we would need to be able to hide icons if they are not enabled in LS.

**Comment by SamuelPetragallo** [comment]
Being able to activate/deactivate these functions per project is important, we need to keep that flexibility

**Comment by jeremiehelme** [comment]
<img width="1680" alt="Capture d’écran 2020-06-11 à 16 48 52" src="https://user-images.githubusercontent.com/2345926/84401741-e9772380-ac03-11ea-979f-7ad5769e0a3f.png">

The last improvement have been added :
- Renaming dt_rowId to UOID 
- Adding an icon showing we can open
- Changing the the add Response button to white
- Hiding undefined name
- hiding icon when action is not available 
- Making the name of the facility bigger  
- Adding "List of responses" on top of the table

There is two features still missing : 
- Translating (though messages to edit / delete...appear to be translated)
- Open all / Collapse all

**Comment by jeremiehelme** [comment]
<img width="1680" alt="Capture d’écran 2020-06-22 à 17 59 13" src="https://user-images.githubusercontent.com/2345926/85308890-1c49d300-b4b2-11ea-9469-eb46cb827d5f.png">

Displayed the header of the table and a status column.
To go further we need to choose a prefix, so I can add the columns to the response table

**Comment by jeremiehelme** [comment]
<img width="1680" alt="Capture d’écran 2020-06-23 à 17 09 18" src="https://user-images.githubusercontent.com/2345926/85421087-4e236e00-b574-11ea-8fde-d487836a07e9.png">

Added configured columns to the response list 

Adding "d:" to the configuration display the column in the response

Example
https://ls.herams.org/survey/index/sid/391149/token/AfHsQ82ri7Pedn3/newtest/Y?test=ResponsePicker

Default columns :
https://ls.herams.org/survey/index/sid/391149/token/AfHsQ82ri7Pedn3/newtest/Y?test=ResponsePicker

**Comment by luna404** [comment]
I'm closing this as the response picker has been released today. Any new issues/enhancement will be raised as a new issue.
