### ISSUE TITLE
Response Picker > Icons for actions not showing on some browsers

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#324]
Seems that there is a problem with the icons not showing sometimes
Occurred on Burkina Faso 
https://herams.org/workspace/7091/limesurvey

Testing on different browsers doesn't reproduce the bug
May be because the Icons CSS does not load 

Waiting for more informations

**Comment by jeremiehelme** [comment]
So I confirm, if the CSS for the icons doesn't load, then the buttons are invisible.
It's not possible to add an alt attribute, as it is not an image

**Comment by jeremiehelme** [comment]
Fix :
I've added a minimum width and height and a default symbol for the icons.
That way they are always clickable and don't block the user, even if they are not the right icons 

That's what users will see if icons don't load 
<img width="1394" alt="Capture d’écran 2020-02-12 à 15 49 16" src="https://user-images.githubusercontent.com/2345926/74346142-68bc2e00-4daf-11ea-8ce7-e6d811ececa3.png">

I will remove the fix if we find a better solution
if it's ok for you, I'll push the fix on the response-picker repo

**Comment by jeremiehelme** [comment]
Let's wait for their answer if they use the [Browser tools](https://lehollandaisvolant.net/tout/tools/browser/)

**Comment by luna404** [comment]
@jeremiehelme I think this is no longer relevant once we release the new response picker. Is this correct?
Also I have never heard back from them, so I guess they managed to resolve the issue themselves.

**Comment by jeremiehelme** [comment]
The new response picker uses the same icons, so the problem can occur too
Let's see if they stil have the issue with the new one

**Comment by luna404** [comment]
Understood. I'm still closing the issue for now as I haven't heard back from the country that this is still an issue. We will reopen it should the problem arise again.
