### ISSUE TITLE
Response Picker > Improvements

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#338]
![image](https://user-images.githubusercontent.com/2345926/74639902-f82a5e00-516e-11ea-8381-562190969411.png)

This screen is equivalent to http://localhost:12346/workspace/1200/limesurvey
We only have the Data part so far. 

- Nesting facilities version this way would help the user to understand what "Editing" and "Updating" a facility means
- Sharing : does the functionality exists ?
- Columns : decide which one are important

- It's not easy to edit the response picker because I can't see the changes other than by pushing to production.

**Comment by SamMousa** [comment]
I think we should delay these changes until we can move this part over to the platform.
Health Facilities are entities that are quite important and the platform should treat them as such. Currently the platform has very limited understanding of HFs and just offloads that to the response picker.

**Comment by SamMousa** [comment]
@jeremiehelme if you want to work on the display of responses in a nested way go ahead.
This can serve as inspiritation for a future implementation on the platform side.

**Comment by luna404** [comment]
Closing this as it seems to a duplication of #321
