### ISSUE TITLE
Favorite workspaces page

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#339]
- [x] Add workspaces manually via toggle button
- [ ] Full list available from favorites <=> 2  way navigation
- [x] Don't use paging on favorites page

**Comment by jeremiehelme** [comment]
Here is what it could look like with the two list
Clicking the All / Favorites buttons change the page, unless it's possible to load the table dynamically ?

I've moved the search bar inside the list container, as it is more a filter for the list than a global search


![HeRAMs-Workspaces-favorites](https://user-images.githubusercontent.com/2345926/74926857-e0eda980-53d6-11ea-9872-f3acea9537eb.jpg)

![HeRAMs-Workspaces-all](https://user-images.githubusercontent.com/2345926/74926853-dfbc7c80-53d6-11ea-84ca-62f3eb92ef98.jpg)

**Comment by SamuelPetragallo** [comment]
Yes validated on the "Favorites / All"
We suggest however to keep the general search in the left menu in addition to the "list filter search".

Note that the "Administration" blue button on the left menu is no longer relevant (which frees up space for the general search)

**Comment by SamuelPetragallo** [comment]
Great, works fine!

@jeremiehelme can we something else than hearts (and also maybe use hollow when the symbol is not selected vs black fill currently)?

**Comment by JeffDotingco** [comment]
works in staging

**Comment by jeremiehelme** [comment]
@SamuelPetragallo Opening a new issue so this one can be closed when working 
#423
