### ISSUE TITLE
Search / jump to box

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#340]

**Comment by jeremiehelme** [comment]
Here is a suggestion for the searchbox 

![HeRAMs-Home](https://user-images.githubusercontent.com/2345926/74825735-b59d8880-530a-11ea-87c9-11b51667aba8.jpg)

In the Admin :

It could stay in the menu, which would allow more space for the breadcrumb :

![HeRAMs-Admin2](https://user-images.githubusercontent.com/2345926/74826385-cb5f7d80-530b-11ea-823f-633e8355c1a8.jpg)


Or in the header, if we decide to hide the menu at some point 

![HeRAMs-Admin](https://user-images.githubusercontent.com/2345926/74826219-82a7c480-530b-11ea-9604-8fd3cf4d1764.jpg)

**Comment by SamuelPetragallo** [comment]
Looks really nice in the left menu.
We'd rather keep it there always (incl. when menu is collapsed): would make the header too crowded otherwise

**Comment by SamMousa** [comment]
Does that mean header will collapse just below the search box?

**Comment by jeremiehelme** [comment]
Yes, that's the way I see it @SamMousa 

Here is what it could look like
![HeRAMs-Home](https://user-images.githubusercontent.com/2345926/75690531-4e38ee80-5ca3-11ea-81ea-15b97db248ea.jpg)
