### ISSUE TITLE
Formalise bug / issue priorities

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#348]
We should formalize what kind of issues need what kind of urgency.
The urgency should be determined based on the impact on processes and the availability of a workaround.

| Urgency 	| Definition                                                                                                                            	|
|----------	|---------------------------------------------------------------------------------------------------------------------------------------	|
| Extreme   	| Data collection or project management is not possible                                                                                 	|
| High     	| Exporting data or viewing dashboards is not possible, there is no workaround available                                                	|
| Normal   	| Issues that a have a workaround available                                                                                             	|
| Low      	| Small issues that when fixed will improve quality-of-life when using the platform (think redirecting to a page after doing an action) 	|

Urgency combined with amount of work / complexity will then lead to a priority. This is also important for expected response times. Currently high urgency to me means **drop what I'm doing, fix this** which probably not what is meant at all times.

**Comment by SamMousa** [comment]
@SamuelPetragallo as a team we need agreement on what the priorities are.
We cannot have priorities based on the end-user's perceived importance.

**Comment by SamuelPetragallo** [comment]
Let's discuss that in our weekly next week to make sure everyone refers to this description when using priority/urgency tags (myself include ;) )
