### ISSUE TITLE
Worldmap default zoom / left menu

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#352]
The default zoom of the worldmap does not take into account the left menu, can that be adjusted? @jeremiehelme ?

**Comment by jeremiehelme** [comment]
Sure, here is the minimum zoom now 
<img width="1680" alt="Capture d’écran 2020-03-05 à 13 18 03" src="https://user-images.githubusercontent.com/2345926/75980982-d1e11e00-5ee3-11ea-9640-02263df4fed0.png">

**Comment by SamuelPetragallo** [comment]
This may not be enough if you look at Palestine on prod:
![image](https://user-images.githubusercontent.com/15345099/75981368-a448a480-5ee4-11ea-8798-a9a4a5a16b02.png)

@luna404 any good parctices on that? I also suggest we limit the max zoom as mentioned in the pull request (wrong place): currently, one can zoom out and see the entire world 4 times 

![image](https://user-images.githubusercontent.com/15345099/75981451-cd693500-5ee4-11ea-85be-0d66233a746d.png)

Would be good to limit that to 1 :)

**Comment by jeremiehelme** [comment]
@SamuelPetragallo What I did only apply to when you load the map.
It moves the map so that all the dots are visible and centered on the space available right to the menu.

It doesn't affect the centering after you started using the map (zooming, panning)

**Comment by luna404** [comment]
@jeremiehelme would it be possible to use the same approach as for the dashboard maps where we use `fitbounds()` to dynamically render the zoom based on the coordinates of the projects?

https://leafletjs.com/reference-1.6.0.html#map-fitbounds

I would also suggest to use a min. and max. zoom levels to avoid the second image Sam P. posted and to avoid a zoom level that is not supported by the basemap (see below)

![image](https://user-images.githubusercontent.com/18245059/75985609-e544b700-5eec-11ea-8313-2cb4a7945a61.png)

**Comment by jeremiehelme** [comment]
@luna404 Normally, It's the case. Sam has done that already
When you load the map page, it adjusts to show all the projects

Is it what you're talking about ?

Ok to add a min/max zoom level

**Comment by luna404** [comment]
Looks good. Should we set the max zoom level a little lower? We can still zoom in way more than what is useful.

@SamuelPetragallo  what do you think?

**Comment by SamuelPetragallo** [comment]
Agree, suggest we zoom down to the point where we see a country in full max (e.g. Tchad)

**Comment by jeremiehelme** [comment]
@luna404 @SamuelPetragallo good point, as discussed, here is what zooming to the max looks like.

![Capture d’écran 2020-04-28 à 18 31 13](https://user-images.githubusercontent.com/2345926/80512993-aaa44b80-897e-11ea-8ec0-8499184a8c2a.png)

Added in #416

**Comment by luna404** [comment]
Perfect, thanks a lot!
