### ISSUE TITLE
New layout for simple forms

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#359]
We need a new layout (which probably extends the admin layout) for screens with a single form:
![image](https://user-images.githubusercontent.com/547021/75337175-c6ab4400-588c-11ea-8e9b-3f1be9a93bde.png)

This layout should contain all wrapper code so that all we need to do in the view files is render the actual form.

**Comment by jeremiehelme** [comment]
@SamMousa I would need some help for that, I've had a look, but now I'm stuck
Can we discuss it tomorrow morning ?

**Comment by SamMousa** [comment]
Yes

**Comment by SamMousa** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/structure-views

**Comment by jeremiehelme** [comment]
Added in #369

**Comment by SamMousa** [comment]
Use the new layout where applicable.

**Comment by jeremiehelme** [comment]
Done for almost every forms, but I'm not sure about how to access the pages for those actions
Project :
- 'export-dashboard'
- 'import-dashboard'
- 'create'
Workspaces :
- 'configure"
