### ISSUE TITLE
Data export does not including _other columns 

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#360]
In LS we can opt to allow users to manually enter a value if they select `Others` for ranking or single choice questions. This creates an additional column with xxx_other. These columns are currently not included in the data export. For example, MoSD3_other is not included in the data export. 

Can all xxx_other fields be added to the export by default?

**Comment by SamMousa** [comment]
Yes, we should add these as an extra text question (when we create the abstract survey structure).

**Comment by SamMousa** [comment]
With these kinds of issues please add an example survey. When looking at a few random surveys `MoSD3` does not have an other option enabled.

**Comment by luna404** [comment]
Here's an example:
MoSD3 variable in project 24 / survey 996483

https://herams-staging.org/project/24/export

https://ls.herams.org/admin/questions/sa/editquestion/surveyid/996483/gid/443/qid/6570

**Comment by luna404** [comment]
Others is now included but the original column is now missing. In the above example, `MoSD3other` is now there but `MoSD3` is missing.
Also could we keep the same syntax as for ranking and multiple choice questions and call it xx_other?

**Comment by SamMousa** [comment]
No, LS stores it in `MoSD3other` not `MoSD3_other`; we get these codes directly from LS and need them to match to find the appropriate data.

**Comment by luna404** [comment]
The columns are there, but the `MoSD3_other` column is empty. 

Btw, it is called `MoSD3_other` now.

**Comment by SamMousa** [comment]
The survey structure is cached; the name has been reverted and the column now contains data.
