### ISSUE TITLE
Error in refreshing a WS (Région de Ngazidja / Grande Comore) in HeRAMS Comores 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#363]
Error in refreshing a WS in HeRAMS Comores in PROD and STAGING. I made a manual refreshing of WSs to reflect the total number of HFs (previously, 17 HFs were only shown). Successful of refreshing 3 WS but not in Région de Ngazidja / Grande Comore. 

<img width="1680" alt="Screen Shot 2020-03-02 at 4 37 52 PM" src="https://user-images.githubusercontent.com/50957748/75659506-116df700-5ca5-11ea-9592-e757615c4a40.png">

<img width="1680" alt="Screen Shot 2020-03-02 at 4 42 05 PM" src="https://user-images.githubusercontent.com/50957748/75659480-06b36200-5ca5-11ea-8d0f-0209407e07bf.png">

**Comment by SamMousa** [comment]
The issue was because of the list with comment question type (FREQ1).
This should now work on staging.

**Comment by JeffDotingco** [comment]
confirmed. WS refresh for Comores, working in staging
