### ISSUE TITLE
Formats of text header are also included in the downloaded data 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#364]
Formats of text header are also included in the downloaded data (example below: HeRAMS Comores)
<img width="1680" alt="Screen Shot 2020-03-02 at 4 50 01 PM" src="https://user-images.githubusercontent.com/50957748/75660037-07002d00-5ca6-11ea-82a8-f62fdcc4a95e.png">

**Comment by luna404** [comment]
@JeffDotingco I thought the agreement was to just use plain text for the question  in order to avoid this issue. If you open the quick translations you can easily see where there are html tags that should be removed. 

https://ls.herams.org/admin/translate/sa/index/surveyid/618734

**Comment by JeffDotingco** [comment]
I have already updated the questions to get rid of the html tags for HeRAMS YEM. But not yet for text display questions that needs some formatting in the questionnaire. Example below is a text display for Governorate and District. Will update this today. 
<img width="997" alt="Screen Shot 2020-03-03 at 4 44 37 PM" src="https://user-images.githubusercontent.com/50957748/75757990-53af3b00-5d6e-11ea-9edb-1ec9fab43223.png">

**Comment by luna404** [comment]
@SamMousa would it possible to exclude questions form the export based on the question type? I.e. would it be possible to exclude text display questions?

@JeffDotingco The text display questions are not very useful for the export. If you look at the export the columns are empty as there is no data. If it's not possible to exclude these question from the export, what do you think of changing it into equations. This would allow you do display it as text as well as having the name of the Governorate/ district stored in the field and thus in the export.

**Comment by SamMousa** [comment]
It is possible

**Comment by SamMousa** [comment]
It is possible

**Comment by JeffDotingco** [comment]
Already fixed the text display as one-liner texts @luna404, getting rid of the formatting.

**Comment by SamMousa** [comment]
Put it in a separate issue though

**Comment by luna404** [comment]
@JeffDotingco  what do you think of excluding these question from the data export. This would also allow you to keep the formatting for these questions

**Comment by JeffDotingco** [comment]
Agree @luna404, especially that some text display questions are included in all of the questionnaires (i.e. submit text display question)
