### ISSUE TITLE
Create real excel exports

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#367]
I could look into this library to create actual excel sheets.

https://github.com/PHPOffice/PhpSpreadsheet

@JeffDotingco @luna404

**Comment by luna404** [comment]
Excel is (and will remain) the default tool for users to analysis the data. Having an Excel export that resolves the current encoding issues would therefore be great.

**Comment by SamMousa** [comment]
This should work now, but still uses extreme amounts of memory so might crash on larger projects. (Please test and see what happens)

**Comment by luna404** [comment]
It works fine for individual workspaces but it times out when I try to download an entire project.

**Comment by SamMousa** [comment]
It's a memory limit I think.

**Comment by SamMousa** [comment]
Please remove the test on staging label after you tested.

**Comment by SamMousa** [comment]
The library that creates excel sheets uses a lot of memory; combined with the number of columns in our data (731 for a test Tchad export) this is an issue that cannot be easily solved.

Will have to look into an alternative method of creating the excel sheet.

**Comment by SamMousa** [comment]
This now seems to work okay for the largest project on staging. Please give it a go!

**Comment by JeffDotingco** [comment]
xlsx import works in staging. Downloaded Arabic dataset for Yemen and excel layout is fine

<img width="1680" alt="Screen Shot 2020-04-28 at 4 58 42 PM" src="https://user-images.githubusercontent.com/50957748/80468543-e1279980-8971-11ea-902b-b2295a126d84.png">

**Comment by SamMousa** [comment]
@JeffDotingco use the labels

**Comment by JeffDotingco** [comment]
getting an error "504 gateway timeout" if I enable "answers as text" @SamMousa

**Comment by SamMousa** [comment]
Can you retry several times? Could be the LS cache was empty

**Comment by JeffDotingco** [comment]
managed to download the excel file of HeRAMS Yemen as Arabic and enabling "text as responses". I am just having difficulty opening the excel file @SamMousa

**Comment by JeffDotingco** [comment]
Opening the Arabic and text as responses dataset of HeRAMS can be opened in excel, but takes some time

**Comment by luna404** [comment]
I have discussed this with @JeffDotingco,  as the issue seems to be related only to Yemen and affecting both csv and Excel export, we will open a new issue for this. 
I'll mark this as `works on staging` as it seems to be working as anticipated for other projects.
