### ISSUE TITLE
Exclusion of text display questions in exporting data (project and WS level)

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#368]
Exclusion of text display questions in exporting data (e.g. Submit text display question) at project and WS level

**Comment by SamMousa** [comment]
This cannot currently be done due to the way we receive information about the survey structure.
Can we remove this from the next release?

**Comment by JeffDotingco** [comment]
Yes @SamMousa, Ministry of Health of Yemen temporarily provided by Samuel the backend access

**Comment by SamMousa** [comment]
Not relevant; can be solved by using page description, or question help text
