### ISSUE TITLE
Summary stats don't match

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#371]
The summary stats in the carousel (bottom left corner) don't match the stats form the api.

|  	| Carousel 	| API 	|
|--------------	|----------	|-------	|
| Projects 	| 20 	| 20 	|
| HF 	| 53055 	| 32724 	|
| Contributors 	| 3690 	| 3243 	|

**Comment by SamMousa** [comment]
The carousel does not take overrides from individual projects into account.

**Comment by SamMousa** [comment]
- [ ] Fixed contributors, issue was caused by 1 method not counting UNIQUE users with permissions.

**Comment by luna404** [comment]
Summary stats match the api, but the facility count in the api/summary stats does not match the count in the project tables. There are several projects that show 0 HF in the api.

In the below example, Tchad has 1888 HF in the [project table](https://herams-staging.org/project/index?Project%5Bid%5D=18&Project%5Btitle%5D=&sort=id), but 0 in the api.

` {
        "id": 18,
        "name": "Tchad",
        "url": "https://herams-staging.org/project/18",
        "facilityCount": 0,
        "workspaceCount": 124,
        "contributorCount": 124,
        "latitude": 15.361167,
        "longitude": 18.664479,
        "latestDate": "2019-09-08"
    },`

**Comment by SamMousa** [comment]
Can you recheck? It works for me, this could be due to me updating the project. Updating the project resets the overrides which was an issue earlier.

**Comment by SamuelPetragallo** [comment]
HF count for Tchad through https://herams-staging.org/api/projects still equals 0

**Comment by SamuelPetragallo** [comment]
Lol @luna404

**Comment by SamMousa** [comment]
@SamuelPetragallo: 

> Updating the project resets the overrides which was an issue earlier.

If this happens you need to update the project so that empty overrides are removed. I have now done this for all projects.
