### ISSUE TITLE
Display contributors in key metrics

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#373]
Now that we have (or as soon as we'll have if tweaks are still required) determined the way we calculate #Contributors, would like that it is displayed on key metrics such as home/login page, bottom left of dashboards, etc.

Most likely instead of "Users" - not sure this is any longer relevant (more of a placeholder until now)

**Comment by SamMousa** [comment]
I think this is implemented already? Please check the places, I did it in some if not all

**Comment by SamuelPetragallo** [comment]
Done indeed thanks!
