### ISSUE TITLE
Data export is incorrect for some variables

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#374]
Data export for Mali is not correct for some variables. 
https://herams.org/project/24/export

For example, below is is a subset of the data exported from LS. Here all records have a response for the variable BAWA1x. 
![image](https://user-images.githubusercontent.com/18245059/76554358-0df12180-6496-11ea-9045-f9ff5c8aea9e.png)

In comparison, the same data exported from HeRAMS misses most of the values for this variable.
![image](https://user-images.githubusercontent.com/18245059/76554362-10ec1200-6496-11ea-91ac-d0caace5ad28.png)

I refreshed the workspaces before downloading the data so that shouldn't be the issue. 

I renamed this variable a couple of weeks ago, could the issue be related to that?

**Comment by SamMousa** [comment]
Ranking questions

**Comment by luna404** [comment]
The issue seems to affect only ranking question in both code and text exports. The is not limited to a single project. So far I have encountered the issue in projects 31 and 24.

**Comment by SamMousa** [comment]
I have found one issue; to confirm I need to test with a survey that has a multiple choice question. Do you know of any?

**Comment by luna404** [comment]
The export is correct for single choice and ranking questions. I can't find any multiple choice question to test it. @JeffDotingco do you know of a survey that still uses multiple choice questions?

**Comment by JeffDotingco** [comment]
HeRAMS Ethiopia has some multiple questions. I also encountered issues when it comes to data downloading of numeric array in the new questionnaire for Philippines Covid-19 response

**Comment by SamMousa** [comment]
> HeRAMS Ethiopia has some multiple-choice questions. I also encountered issues when it comes to data downloading of numeric array in the new questionnaire for Philippines COVID-19 response

Why are you downloading this via HeRAMS?

**Comment by JeffDotingco** [comment]
A project was created in HeRAMS for the Hospital capacity monitoring of PHL

**Comment by SamuelPetragallo** [comment]
> > HeRAMS Ethiopia has some multiple-choice questions. I also encountered issues when it comes to data downloading of numeric array in the new questionnaire for Philippines COVID-19 response
> 
> Why are you downloading this via HeRAMS?

We'll need that if we're to implement HeRAMS-COVID projects. # of ICU beds etc. are a must
