### ISSUE TITLE
Cannot import HeRAMS YEM survey

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#375]
Doing some modifications again as requested by WCO YEM IM (create separates WSs for all hospitals). But I couldn't import survey back with the screenshot below:
<img width="1680" alt="Screen Shot 2020-03-15 at 7 37 24 PM" src="https://user-images.githubusercontent.com/50957748/76725795-4fc9e280-678a-11ea-8130-bc88d575fc87.png">

- solution at the moment, I am doing the modifications directly at LS (e.g., changing tokens)

-  a similar issue was also raised in LS forums: https://www.limesurvey.org/forum/installation-a-update-issues/115068-cannot-import-survey,-incorrect-permissions-for-the-application-tmp-folder

**Comment by SamMousa** [comment]
@JeffDotingco can you retry this to see if the issue is still there.

Also try it for a different survey to make sure it's a global LS issue not just a survey specific isue.

**Comment by JeffDotingco** [comment]
Not a global LS issue but just for HeRAMS YEM. I can try this issue if HeRAMS YEM needs to be deactivated for a major survey update / editing of responses

**Comment by luna404** [comment]
@JeffDotingco has this been resolved?
