### ISSUE TITLE
HF type charts on worldmap pop-up are incorrect

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#383]
I'm not sure whether this is an issue, or it's due to us messing up the JSON, but the HF type chart seems to be wrong for all projects.

Here's an example for project [24 (Mali)](https://herams.org/project/24/update). 

![image](https://user-images.githubusercontent.com/18245059/77556249-8acdc380-6eb8-11ea-9967-6dc281841b8a.png)

This is what it should look like

![image](https://user-images.githubusercontent.com/18245059/77556585-029bee00-6eb9-11ea-9e98-4d91e07341ec.png)

JSON for Mali

`{
    "A1": "Tertiaire",
    "A2": "Autre",
    "A3": "Secondaire",
    "A4": "Secondaire",
    "A5": "Primaire",
    "A6": "Primaire",
    "A7": "Primaire",
    "A8": "Primaire",
    "A9": "Primaire"
}`

The percentages shown seem to be based on the number of categories rather than the facility count. For example, there are two categories corresponding to `Secondaire` if you divide this by the number of categories (11) it will give you the 18.2% displayed.

**Comment by SamMousa** [comment]
@luna404 please have a look on staging (the popups only show data, but that data should now be correct)

**Comment by luna404** [comment]
Seems to be correct now, thanks.
