### ISSUE TITLE
changing the settings and logout icons into darker gray

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#390]
the new settings icon is not visible using iPhone (but directs you to projects if you press beside your name) and slightly seen if you use a laptop

![IMG_3654](https://user-images.githubusercontent.com/50957748/78358815-65dafe00-75e6-11ea-8091-29744f894973.PNG)

**Comment by jeremiehelme** [comment]
Thanks @JeffDotingco
It was supposed to be darker, I've made a mistake while merging.

It'll be fixed in the next release, sorry for that

**Comment by JeffDotingco** [comment]
No worries @jeremiehelme

**Comment by jeremiehelme** [comment]
It'll be back to normal :)

![Capture d’écran 2020-04-03 à 14 38 51](https://user-images.githubusercontent.com/2345926/78361957-89d41a80-75b9-11ea-94b9-0fc86d8168f4.png)
![Capture d’écran 2020-04-03 à 14 39 08](https://user-images.githubusercontent.com/2345926/78361968-8d67a180-75b9-11ea-842a-8f41651f3991.png)

**Comment by jeremiehelme** [comment]
Pushed in #391

**Comment by JeffDotingco** [comment]
works in staging
