### ISSUE TITLE
Health facility attributes

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#392]
Create a list of HF attributes that do not change, and thus need not be in the survey.

Some things I can think of:
- Name
- District
- Province

These fields need to be global for all HFs in all countries. Editing them will not have history but can be limited to workspace admins or some other HeRAMS permission.

**Comment by SamuelPetragallo** [comment]
Here they are, based on our SDM and adapted from more globally agreed upon standards (https://www.who.int/healthinfo/country_monitoring_evaluation/mfl/en/):

1. Unique identifier / UOID currently
2. Name
3. Postal address
4. Contact phone number / Those relate to the HF and not the respondant as we currently have. Respondant details will remain with the actual records)
5. Contact email /same comment as above
6. Administrative areas (e.g. Province, District) / Not the easiest as we lack reference standards on this and could consider Name / p-codes / etc. Realistically speaking, think we're talking about names for now and no more than 4 levels. @luna404 what do you think?
7. Geographic coordinates
8. Operationnal status / currently MoSD4

**Comment by SamuelPetragallo** [comment]
This is a big step, beyond decoupling ls... can't wait! :)

**Comment by luna404** [comment]
Here are the codes for this

1. UOID 
2. MosD2
3. MoSD3
4-6 I would propose to change MoSD6 into a multiple short text fields names MoSD6_Address, MoSD6_Phone, MoSD6_Email.
7. GEO1 split into up to for different values. String should split after " / ".  
8. MoSDGPS_SQ001 and MoSDGPS_SQ002 (maybe we could rename them into MoSDGPS_Lattitude and MoSDGPS_Longitude.
9. MoSD4

For point 7. It would be nice to have pcodes, but I think we'll save ourselves a lot of work if we don't do it for now. Optionally, we could add the GEO2 field but I think it's not used for most projects right now.

**Comment by SamMousa** [comment]
We won't be using LS question codes but proper names from the SDM instead

**Comment by SamuelPetragallo** [comment]
This basically constitutes the Health Facility Master List, the cornerstone of any health information system :). We should already consider (provided agreement through the data policy) that it will need, on a project to project basis, to be easily "packaged and pushed" to other external systems and users

**Comment by SamuelPetragallo** [comment]
> Here are the codes for this
> 
> 1. UOID
> 2. MosD2
> 3. MoSD3
>    4-6 I would propose to change MoSD6 into a multiple short text fields names MoSD6_Address, MoSD6_Phone, MoSD6_Email.
> 4. GEO1 split into up to for different values. String should split after " / ".
> 5. MoSDGPS_SQ001 and MoSDGPS_SQ002 (maybe we could rename them into MoSDGPS_Lattitude and MoSDGPS_Longitude.
> 6. MoSD4
> 
> For point 7. It would be nice to have pcodes, but I think we'll save ourselves a lot of work if we don't do it for now. Optionally, we could add the GEO2 field but I think it's not used for most projects right now.

This mapping (though will have to confirm it on a case to case basis) will still be needed to migrate data from ls to herams when this becomes operationnal

**Comment by SamuelPetragallo** [comment]
I think that's ready from our side

**Comment by SamMousa** [comment]
Do we need history for fields like contact info? Or are we only interested in the current status (like phone number).

All fields listed above will no longer be in the survey and only be available for editing in the platform, this means there is no history.
