### ISSUE TITLE
Users with no permissions are not removed from the permissions table

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#393]
If you remove all permissions granted to a user, the user is not removed from the list.

https://herams.org/project/31/share

![image](https://user-images.githubusercontent.com/18245059/78649207-6c56c780-78bd-11ea-939b-ea7d0236250c.png)

**Comment by SamMousa** [comment]
But when you refresh he is right?
We're not updating the list dynamically, this is by design.
I don't see this as an issue, reloading the whole table will just make it slower to load.

I propose leaving it like it is now.

**Comment by luna404** [comment]
For other uses yes, but this one is staying even after refreshing. Is it possible that this is related to the "allow everything" permission. The same issue also happens in other projects.

https://herams.org/project/24/share

![image](https://user-images.githubusercontent.com/18245059/78666640-eb58f980-78d7-11ea-9b06-99a1e56d6ab8.png)

Both of us definitely have access to this project.

**Comment by SamMousa** [comment]
That's a remnant of the admin permission. I have removed these permissions now.

Please confirm and then close!

**Comment by luna404** [comment]
Confirm, it's working now
