### ISSUE TITLE
Not possible to grant permissions at the project level

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#394]
It's not possible to grant permissions to a new users at the project level. Works fine at the workspace level though.

**Comment by luna404** [comment]
Adding this to the next milestone. If we are implementing COVID related projects in Sudan and Mali, this will need to be resolved.

**Comment by SamMousa** [comment]
Is there a bug, or is this feature not there? If it's a bug what is the error you're seeing?

If we are adding new stuff to this milestone we should remove something else.

**Comment by luna404** [comment]
It's a bug. The `add` button doesn't seem to function correctly. 

When you try share any permission at the project level, nothing happens. you can select users and assign permissions, but when you click the `add` button, nothing happens.

**Comment by luna404** [comment]
I'm reopening this as it's still not working on staging.

**Comment by SamuelPetragallo** [comment]
@SamMousa pinging you on this as quite important (e.g. we'll be assigning permissions on 60 WSs manually in the meantime ;) )
