### ISSUE TITLE
Unable to create dashboard elements for new project

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#397]
Issue only related to this survey https://ls.herams.org/admin/survey/sa/view/surveyid/655873

I'm trying to create a dashboard for this survey but I can't add new elements. I keep getting an error `Undefined offset: 13014`.
https://herams-staging.org/element/create?page_id=263&type=map
https://herams.org/element/create?page_id=312&type=map

Do I assume right that this means there is an issue with questions 13014 in this survey, which is a subquestion of question 13013? 

https://ls.herams.org/admin/questions/sa/editquestion/surveyid/655873/gid/857/qid/13014
https://ls.herams.org/admin/questions/sa/editquestion/surveyid/655873/gid/857/qid/13013

Any ideas what the issue might be?

**Comment by SamMousa** [comment]
What's the question type?

**Comment by luna404** [comment]
Array (Numbers)

**Comment by SamuelPetragallo** [comment]
Folks (@SamMousa @luna404 @jeremiehelme @JeffDotingco ):

HeRAMS-COVID19 has now officially been launched for Mali. See the nice letter from MoH to there staff attached :)

That's making this issue a bit hotter: beyond the use in-country itself, I'd like to be able to share the news while it's still hot off the press with senior management (particularly at the regional level) so that we can get some more support and traction (and as importantly avoid the proliferation of unnecessary noise around)

Can we discuss that all together and see what can be done? Thanks

[HeRAMS_COVID19_Mali_LettreIntroduction_MoH_20200423.pdf](https://github.com/HeRAMS-WHO/herams-backend/files/4522486/HeRAMS_COVID19_Mali_LettreIntroduction_MoH_20200423.pdf)

**Comment by luna404** [comment]
Even if this issue is being resolved, one of the main challenges that will remain is the fact that we are using a lot of array and numeric question types in the COVID questionnaires (both Mali and Sudan). As it might not be possible to have a solution for these field types immediately, I would suggest to create COVID dashboards elsewhere (e.g. PowerBI, ArcGIS, Tableau etc.) and embed them in the page where we would normally have the dashboard. While this is not an ideal solution, it would allow us to start developing dashboard as soon as data collection is taking up while at the same time maintaining the user experience of having everything available in the some location. 

I'm aware that one of the issue with this approach is that permissions cannot be mimicked in an external application. However, as both of the projects are currently open, the dashboards are already visible to all users. I therefore think it would be an acceptable solution to make these dashboards fully public. Of course this would have to be communicated with our country focal points first...

**Comment by SamMousa** [comment]
> As it might not be possible to have a solution for these field types immediately, I would suggest to create COVID dashboards elsewhere (e.g. PowerBI, ArcGIS, Tableau etc.) and embed them in the page where we would normally have the dashboard. While this is not an ideal solution, it would allow us to start developing dashboard as soon as data collection is taking up while at the same time maintaining the user experience of having everything available in the some location.

This comes with its own challenges (unless you're manually exporting the data, in which case i'm fine with it..)

Not sure what the timeline is here, but support for pushing the data to a BI tool will not be in the next milestone.

**Comment by SamuelPetragallo** [comment]
Throwing another idea in: if we move along the lines of regular pdf reports for COVID maybe we could also consider serving those in lieu of dashboards - ?

**Comment by SamuelPetragallo** [comment]
While we brainstorm on longer term issues, could we simply ensure as a first step (and as a way to resolve this issue) that question types that are not handled are simply ignored, without creating a bug?

@SamMousa any relevant/easy to implement that kind of an approach for now?

**Comment by luna404** [comment]
https://herams-staging.org/project/42

**Comment by SamMousa** [comment]
Fixed the survey in LS
