### ISSUE TITLE
Filters > filtering by date should only allow past date

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#398]
filtering by date should only allow past date in the project dashboard filters 

![Capture d’écran 2020-04-09 à 15 28 09](https://user-images.githubusercontent.com/2345926/78900175-bd5deb80-7a76-11ea-83fb-e37caa66a84a.png)

**Comment by jeremiehelme** [comment]
Pushed in #401

**Comment by luna404** [comment]
As this is labelled as `works on staging`, can it be included in this week's milestone?

**Comment by SamuelPetragallo** [comment]
@SamMousa for your attention and decision ;)
