### ISSUE TITLE
Allow users to select fields to be downloaded (excel download)

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#399]
As a way to cut short on multiple requests we're getting for what needs to be included or not in excel exports. Similar to what is available in ls export.

**Comment by SamMousa** [comment]
When you say fields, do you mean questions? (Questions can have multiple fields)

I don't think the UX will improve if people have to choose ~150 columns.

Would it make more sense to offer this per group? Then instead of ~150 columns you choose from around ~15 areas of interest

**Comment by SamuelPetragallo** [comment]
Agree on the challenge to have too many questions. Groups would indeed make sense, but we'd then need to ensure question group names are understandable and usable. Unsure that's the case. @luna404 do you think?

**Comment by luna404** [comment]
Would the groups be project specific and permission dependent?

**Comment by SamMousa** [comment]
Yes, because they are survey specific

**Comment by SamMousa** [comment]
And not yet, since we have no model for permissions based on dynamic structure.
