### ISSUE TITLE
Hide dashboard button

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#402]
The project popup should not show the dashboard button if the project does not have pages configured.

**Comment by jeremiehelme** [comment]
@SamMousa  
I've added a parameter to the json to determinate if the project have pages :
`!empty($project->pages)`

Previously we had that check 
`!empty($project->pages) && (true || \Yii::$app->user->can(Permission::PERMISSION_READ, $project))`
Is the second part useful ?


There is different status of project
    ONGOING
    BASELINE
    TARGET
    EMERGENCY_SPECIFIC

What are BASELINE and EMERGENCY_SPECIFIC project ?

**Comment by SamMousa** [comment]
@SamuelPetragallo the question on status is for you.

**Comment by SamMousa** [comment]
Also, I have no idea what source code file you're referring to.

**Comment by jeremiehelme** [comment]
@SamMousa Right sorry, I'm referring to this one, that were used before we switch to the new popups :

https://github.com/HeRAMS-WHO/herams-backend/blob/master/protected/views/project/summary.php

**Comment by jeremiehelme** [comment]
Sure ok,

I've added a dashboard_url to the json, and I hide the dashboard button if it's empty
For now I've let the test I mentioned, that way it still works

Then I guess the same question applies to the workspace button ? should it always stay visible ?

**Comment by luna404** [comment]
Hiding the dashboard button is working, but there is a `no data` string showing in the popup. Could this be removed?
![image](https://user-images.githubusercontent.com/18245059/80469218-8b86c900-8940-11ea-9a7e-310f26f35b77.png)

**Comment by SamMousa** [comment]
This is due to #412. I wasn't sure what is actually intended to be there.

I'm closing this and we should create a new smaller issue for the no data thing.
