### ISSUE TITLE
Overwriting summary stats

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#403]
I'm trying to overwrite the summary statistics for one of the projects where have no data available but received some aggregated information form the country. 

https://herams-staging.org/project/20/update

1. Do you have a sample of the proper syntax? I've been using the below json, but it only works to overwrite the contributor count. 

`{
    "facilityCount": 1019,
    "workspaceCount": 100,
    "contributorCount": 65
}` 

2. We know the number of HF by type so it would be great if we could display this information too. Is it possible to overwrite the data for the hf type chart (in the pop-up) or do we have to create dummy records in order for this to work?

**Comment by SamMousa** [comment]
You can:
```
 "typeCounts": {
        "Other": 0,
        "Primary": 120,
        "Tertiary": 0,
        "Secondary": 0
    },
```

**Comment by luna404** [comment]
Thanks, this works great on staging. For whatever reason the total number of HF is not showing on Prod. Can I assume this will fix itself with the next release?

Staging: 
https://herams-staging.org/project/20/update
![image](https://user-images.githubusercontent.com/18245059/79767506-ba41e580-8329-11ea-98f9-2b283d25f790.png)

Prod:
https://herams.org/project/20/update
![image](https://user-images.githubusercontent.com/18245059/79767594-d6de1d80-8329-11ea-9936-f5597475457b.png)

**Comment by SamMousa** [comment]
Yes, the override on prod doesn't work unless there's at least 1 workspace. I fixed that bug this morning. (which is why it is only on staging)
