### ISSUE TITLE
Contributor count

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#405]
Correct me if I'm wrong, but on a project level, the # of contributors is the number of unique users having at least one permission assigned (or the number of WS if less than one user per workspace). In comparison, on the workspace level it shows the number of permissions assigned. Could we change the # contributors at the WS level to also show unique users?

**Comment by luna404** [comment]
As this is working on staging, can it be included in this week's release?

**Comment by SamuelPetragallo** [comment]
Adding the milestone to make sure @SamMousa gets it on his radar (@SamMousa  up to you whether to actually include it)

**Comment by SamuelPetragallo** [comment]
@SamMousa for your attention and decision ;)
