### ISSUE TITLE
Communicating through the platform

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#407]
Hi Folks, this is a broad topic. 

Just want to launch the discussion as I'm getting requests these days to access data, which ideally should be managed through the platform directly.

That implies having identified and reachable Project and WS owners to start with but also touches upon a number of other issues around general communications incl. chat, possibility to exchange over dashboards (chat/tracking?), notifications etc.

Just throwing this here as food for thoughts on the overall area of work, plus asking @SamMousa how we can specifically look into the first (most urgent) part of it which is being able to reach out to Project and WS owners

**Comment by SamMousa** [comment]
The access request flow is already in here: #349.

**Comment by joester89** [comment]
@SamuelPetragallo @luna404 

If the requesting access is covered by another issue what is left then for this issue?

I read it like some possibility to communicate inside the platform within a given context. Basicly like giving comments on a post like Facebook.

Some questions to think about:
- What kind of contexts are possible (starting off with only a project or workspace?)
- Is the communication public like a chat room to anyone whom can read the context?
- Can you (un)follow a chat and do we send any notifications?
- How is it incorperated in the interface?

**Comment by luna404** [comment]
One of the main goals of this feature is that we have a workflow where users can report discrepancies of what we have in the system to what they observed in the field. For example, while on a field visit, I notice that the data in the system does not correspond to what I've observed on the ground. I can then contact the project coordinator or workspace owner informing them that a health facility has been closed or that there is a new health facility in district XY.

Another example would be a regional coordinator reminding workspace owners in their district to update the data for the current reporting period.

For a first iteration, I would suggest a project-level messaging board that anyone with access to the project can view. I'm torn on the notification point. We wanna avoid spamming users but we also don't want notifications to go unseen for weeks. Maybe with the exception of the project coordinators, users would have to opt in to be notified...

@SamuelPetragallo what do you think?

**Comment by joester89** [comment]
More details after the discussion of this morning:
- [ ] communication will be made based on threads
- [ ] a thread can be created (for now) from a dashboard page. Filters need to be stored so that from the thread the dashboard can be reproduced. This storage of filters should preferably be reusable (for the chart export i.e.)
- [ ] the read status of messages must be tracked so it can be indicated that there are new messages

Still open:
- [ ] how to handle notifications?
- [ ] can you subscribe to threads or are you auto-subscribed in some cases?
