### ISSUE TITLE
HF popups

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#408]
We now have popups for HFs I've just realized while skimming through with a colleague from MSF who is after data

![image](https://user-images.githubusercontent.com/15345099/79962039-d65b9900-8487-11ea-87af-3eb6892d86d8.png)

That's great!

Guess we now need to pimp these a little. I see 3 things:
1. some key metrics (ideally HeRAMS standard) such as Name, GEO1, Damage, Functionality, Accessibility and overall service avail?
2. access to the related WS (and for those that don't have access this would take them to the "Request access") - note this is linked we the fact that we need identified WS owners (issue to be derived from #407 )
3. access to the HF report (also for a lter stage when we'll actually have those reports)

So for now, shall we focus on 1. and decide which metrics we display there? Open up for suggestions @luna404 @JeffDotingco and Fatma, thanks!

**Comment by SamMousa** [comment]
This is actually a bug due to implementation of the new popups on the world map.

**Comment by SamuelPetragallo** [comment]
Thought so and confirmed by Jeremie too... but it's breat: it re-opens up the discussion on pimping these popups which we've parked "some time ago"... :)

**Comment by luna404** [comment]
> 1. some key metrics (ideally HeRAMS standard) such as Name, GEO1, Damage, Functionality, Accessibility and overall service avail?

I would suggest the following variables. MoSD2, MoSD3, CONDB, HFFUNCT, HFACC. For the overview on service availability, I would suggest  we use use the value from the service availability map. 

> 2. access to the related WS (and for those that don't have access this would take them to the "Request access") - note this is linked we the fact that we need identified WS owners (issue to be derived from #407 )

For a first release, could we just include the workspace name? This would already help data managers to locate a given facility to edit the record. 

> 3. access to the HF report (also for a later stage when we'll actually have those reports)

Agreed.

**Comment by SamuelPetragallo** [comment]
@jeremiehelme is that for you to pick now? @SamMousa is your support still needed to get this done?

**Comment by jeremiehelme** [comment]
@SamuelPetragallo I think I need the data first, before styling the popup. Unless I can have them but don't know how @SamMousa ?

**Comment by SamMousa** [comment]
I'll add them, think that's easiest.

**Comment by SamMousa** [comment]
@jeremiehelme I have added the data to the tooltip,  search the source code for `#408` or check the changes in the commit you see above this comment.

**Comment by jeremiehelme** [comment]
I can easily display something so that we have a clean popup, and come back to it later to improve it if it’s too long

**Comment by jeremiehelme** [comment]
Add the title and a shortcut to the workspace
Find the HF API

**Comment by jeremiehelme** [comment]
Added the title and a link to the response picker containing this HF.
Linking to the response picker seemed the most relevant to me, but let me know if it's not the case or if you want other links

![Capture d’écran 2020-07-30 à 12 17 49](https://user-images.githubusercontent.com/2345926/88911829-b72a8f80-d25e-11ea-99e0-33983eada508.png)

**Comment by jeremiehelme** [comment]
@SamuelPetragallo @luna404 Can we talk about that when you are available ?

**Comment by luna404** [comment]
I agree with the link to the response picker being the most relevant, but we need to keep in mind that not all users have access to the data. Do you have access to the user's permission so you could set up a redirect link based on the user's permissions?

The ideal behavior should be like this.
Scenario 1: User has edit permission to the workspace and is redirected to the response picker. 
Scenario 2: User does not have access and is redirected to the list of workspaces with an automatic filter applied for the selected worksapce (https://herams-staging.org/project/24/workspaces?Workspace%5Bid%5D=5455).

@jeremiehelme give me call this afternoon if you would like to discuss this further.

PS: can we change the pop-up back to the simple white pop-up we used to have before?

**Comment by jeremiehelme** [comment]
Great, I've set up the redirection based on the user's permissions
- User has edit permission to the workspace and is redirected to the response picker.
- User does not have access and is redirected to the list of workspaces with an automatic filter applied for the selected workspace

@luna404  "can we change the pop-up back to the simple white pop-up we used to have before?"
I've used the same design as the for the projects
If I change it back to white, then it would mean that we now associate the dark grey to Projects, and the white to Health Facilities. It's not a problem, we just have to keep that in mind

**Comment by luna404** [comment]
Cool, this seems to be working well.

Regarding the background color. I think this actually not bad if we use a different color for health facilities compared to project. This way a user always knows at what level they are.

**Comment by jeremiehelme** [comment]
Ok great ! 
So projects will be dark grey and Health Facilities white, that works for me
It's on staging

**Comment by jeremiehelme** [comment]
About the other datas to be displayed (MoSD2, MoSD3, CONDB...)
For now I only have the code (CONDB : A4) and I'm looking for a way to display the label instead

**Comment by luna404** [comment]
I would suggest opening a new issue for this so we can already release the new pop-ups as they are right now.

**Comment by jeremiehelme** [comment]
Opening the #610 to discuss the content
