### ISSUE TITLE
Project popup review

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#412]
After cleaning up the implementation of the new popups I noticed several cases are not handled clearly or properly...

Some of the things that were wrong with the implementation:

- String concatenation without proper escaping, this is a big security risk
- No error handling
- No structure

I've fixed most of these but am unclear what needs to happen in the case the project status is `ongoing`, but the numbers are all `0`.

@SamuelPetragallo what is the expected behavior in those cases?

**Comment by SamuelPetragallo** [comment]
> 
> @SamuelPetragallo what is the expected behavior in those cases?

We've agreed to simply display the popup without any data (only icon and text (when relevant) of each metric)

**Comment by SamMousa** [comment]
Ok

**Comment by jeremiehelme** [comment]
Thanks for the cleaning,
I had followed the structure in place, but having it in a separate class is indeed clearer

We should have talked about that before though
Some cases were handled in the next PR for example, 
With your advice I could have done it and save you some time, we end up doing extra work

I will change the next PR, can we discuss the next step after that ?

**Comment by SamMousa** [comment]
Why not just create clear and correct code in the initial PR. You are introducing security issues in our code base.

> With your advice I could have done it and save you some time, we end up doing extra work 

This would not save time; doing it myself is more efficient then explaining it to you and then reviewing code.. That would take several iterations, not to mention the fact that I am a terrible teacher.

**Comment by SamMousa** [comment]
Todo: 
![image](https://user-images.githubusercontent.com/547021/80472296-cf7bcd00-8944-11ea-8200-d465ea0dbe75.png)

**Comment by jeremiehelme** [comment]
Merged in #406
