### ISSUE TITLE
Projects Status and display (map and summary popup)

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#414]
Ok, we've discussed and agreed on the way forward regarding Project Status.

1. We currently have 4 categories: Ongoing, Baseline, Target, Emergency Specific of which we'll only keep 3: Ongoing, Target and Emergency Specific. I have verified that all current projects on Prod have either of these 3

2. "Target" to be renamed "SetUp"

3. "Emergency Specific" to be displayed differently on WorldMap to single them out a bit (we've already had users not see the one in Mali): we discussed 2 ideas: a. using a different color for the project "dot" and 2. displaying "Emergency Specific" project names at the top of project name list on the right (possibly using the same color as the dot?) - but there may be many other options there, up to you @jeremiehelme (and others of course) to suggest stuff maybe

 but of course others are welcomed @jeremiehelme

**Comment by jeremiehelme** [comment]
I tried something, just to open the discussion
![HeRAMs-Home](https://user-images.githubusercontent.com/2345926/80953223-617b4e00-8dfb-11ea-9990-a53c18469247.jpg)

**Comment by jeremiehelme** [comment]
Adding clusters where markers are too close. 

Will be useful for countries having an emergency specific project. 

Clicking on the cluster zooms the map to display all the projects contained
Clicking on a project in the left menu zooms as well, and open the popup

<img width="1680" alt="Capture d’écran 2020-05-14 à 10 09 46" src="https://user-images.githubusercontent.com/2345926/81909832-70b48580-95cb-11ea-83ff-93a6e4400f7c.png">

We still need a way to know which dot is the emergency specific one

**Comment by jeremiehelme** [comment]
@SamuelPetragallo @luna404 @JeffDotingco I push it to staging to see what it does.

One side effect is that it might also clusterize projects that are too close, like Syria, Turkey and Palestine.

**Comment by jeremiehelme** [comment]
Can someone move Mali-COVID close to the Mali dot ? 
That way it will show the cluster

**Comment by luna404** [comment]
Can you manipulate the clustering range or zoom in more upon clicking the clustered dot? I changed the coordinates for the two projects, but now the dots still overlap when you expand the cluster. 

![image](https://user-images.githubusercontent.com/18245059/82201658-02403200-9901-11ea-9231-50db28c50fa1.png)
![image](https://user-images.githubusercontent.com/18245059/82201687-0d935d80-9901-11ea-8930-2d925974a05d.png)

**Comment by jeremiehelme** [comment]
Try to add a new color for emergency specific projects
Display the legend, and see how it works with clusters

**Comment by luna404** [comment]
@jeremiehelme if I remember correctly, we discussed this again last week and decided against the colors. Rather than zooming in, upon clicking on  (or hovering over) the clustered point, a small pop-up should be shown displaying the names of the projects.  If a users clicks on the name of the project the corresponding pop-up should open.

**Comment by jeremiehelme** [comment]
@luna404 Yes, this is what I wrote 
- When hovering over a point, show a tip with the title of the project 
- Click on a cluster show a popin listing all the points

**Comment by jeremiehelme** [comment]
Here is an update, you can test on staging

<img width="1680" alt="Capture d’écran 2020-06-02 à 09 43 52" src="https://user-images.githubusercontent.com/2345926/83494330-65f85c80-a4b6-11ea-9382-3d62447832f6.png">

The last thing to do is to avoid having to zoom to display the popup

**Comment by luna404** [comment]
Looks very nice. Two points

1. There seem to be two zoom levels. if you click the aggregated button it zooms the first time and if you select the project it zooms again. As both points are on the same place, do we need the second zoom?
2. I changed the location for the two projects in Mali so they fully overlap. Once you open and close the pop-up it's no longer possible to select between the two project. 

I think both of these issues are related to the clustering functions. Do you know whether it is possible to prevent the points from un-clustering?

**Comment by jeremiehelme** [comment]
@luna404 Yes, i'm on it :)

**Comment by jeremiehelme** [comment]
@luna404 It's on staging if you want to test it
thanks !

**Comment by luna404** [comment]
Perfect, for me it's good for release.
