### ISSUE TITLE
Is there a requirement for GPS coordinates to be shown in the map like decimal places?

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#417]
I noticed in HeRAMS Yemen that a health facility with a GPS coordinate having only 3 decimal places is not shown. 

- I have already deleted the validation rule for GPS coordinates that there should be at least 4 decimal places, still a health facility with gps coordinate with only 3 decimal places is not shown in the map;

- but after adding zero (0) for that HF to have 4 decimal places in GPS, it is already appearing

**Comment by luna404** [comment]
@JeffDotingco do you mean not shown on the dashboard or in the questionnaire? 

If it's a dashboard issue, the validation rule shouldn't matter unless it's erasing the value. Did you completely remove the validation formula or did you just change it to a min. of 3 digits? From a mapping point of view a min. of 4 digits is required to get street level precision. We could make it a little less precise and change to 3 digits, but I wouldn't recommend to completely remove the validation formula (or you will get a lot of HF that end up in the water). FYI here's a nice explanation on what precision level you get depending on the number of decimals. https://en.wikipedia.org/wiki/Decimal_degrees

**Comment by JeffDotingco** [comment]
Thanks @luna404. HFs are not shown in the dashboard if GPS coordinates has only 3 digits upon observation. I removed the validation rule. Copy on not removing the validation rule, I will put it back. Thanks for the info on 4 digits to get street level precision.

**Comment by SamuelPetragallo** [comment]
If this validation rule is in place at ls level for data submission it should not impact display in herams.
Don't we have 2 distinct issues here?

**Comment by SamMousa** [comment]
@JeffDotingco have you checked the data we're getting from LS via the new data comparison tool? 

Steps:
1. Login on staging
2. Admin view
3. Project list
4. List of workspaces
5. List of responses
6. Pick a response

Need to have a specific response that shows the issue so we can fix it.

**Comment by JeffDotingco** [comment]
HFs with GPS coordinates of at least decimal places are shown in the map (STAGING). See below as an example: 

<img width="1680" alt="issue 417" src="https://user-images.githubusercontent.com/50957748/82801203-83726880-9eaf-11ea-93b6-5d0711a5ed8d.png">
