### ISSUE TITLE
Draft hosting requirements

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#419]
Draft rough technical requirements for hosting platform

**Comment by SamuelPetragallo** [comment]
@SamMousa did you share something on this yet?

**Comment by SamMousa** [comment]
Ideally we would need some budget X on a platform like digitalocean.
Services we need are:
- Hosted databases
- VPSes
- Load balancers
- Managed k8s

Instead of specifying everything in detail in advanced I'd prefer to figure it out as we go. For < $200 a month we should get most things we need done.

**Comment by SamuelPetragallo** [comment]
Message shared with IMT / will follow up on this

**Comment by SamuelPetragallo** [comment]
That's the file we need ot return to IMT (just consider the Infrastructure tab)

[HeRAMS_HostingRequirements_AZUR_IMT_20200617.xlsx](https://github.com/HeRAMS-WHO/herams-backend/files/4791417/HeRAMS_HostingRequirements_AZUR_IMT_20200617.xlsx)

**Comment by SamMousa** [comment]
[HeRAMS_HostingRequirements_AZUR_IMT_20200617.xlsx](https://github.com/HeRAMS-WHO/herams-backend/files/4818378/HeRAMS_HostingRequirements_AZUR_IMT_20200617.xlsx)

@SamuelPetragallo I have marked the stuff you should be able to fill in in yellow.

**Comment by SamuelPetragallo** [comment]
Shared with IMT just now - will feedback as needed
