### ISSUE TITLE
Project PDF

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#421]
@luna404 
Some of the table (and map legends) have a scroll bar, which means they will be cut off in the export. Could the tables be made a little bigger to make sure the entire content is always included?

![80689171-33310200-8acd-11ea-8c6b-c58c7752dc84](https://user-images.githubusercontent.com/2345926/80714797-b8301180-8af5-11ea-871a-b7e24052439c.png)

Is it possible that the map zoom level has a padding applied? The default zoom level doesn't seem optimal
![80689030-041a9080-8acd-11ea-80de-06affb35f90f](https://user-images.githubusercontent.com/2345926/80714808-bc5c2f00-8af5-11ea-81a9-95eabaeb2369.png)

Not sure whether this is possible, what in the print view, you can adjust the zoom level of the maps. Would it be possible that map zoom levels are always the same for all maps. Meaning if a user changes the zoom level for one map all the others will use the new zoom level?

**Comment by jeremiehelme** [comment]
@luna404 
I have fixed the table height problem

In which country do you see the legends with a scrollbar ?

Also for the map not adjusting to the view, I don't know how to reproduce the bug
What browser / computer do you use ?

Thanks,

**Comment by luna404** [comment]
If you look at the first map here, the legend has a scroll bar. https://herams-staging.org/project/24/pdf

Would it be possible to have the legend outside the map? This would also address the issue of the legend overlapping with the data for some of the countries.

For the second question, I'm using chorme. Here's an example of the dashboard vs the report. The zoom level on the map seems much better

**dashboard**
![image](https://user-images.githubusercontent.com/18245059/80970175-08231700-8e1b-11ea-84ed-ca37a6a0f441.png)

**pdf**
![image](https://user-images.githubusercontent.com/18245059/80970241-20933180-8e1b-11ea-8179-08adae26f239.png)

https://herams-staging.org/project/24/pdf

**Comment by jeremiehelme** [comment]
@Luna : can we add the page title for the sub-pages? No need to repeat the entire header, just the name of the page?

**Comment by jeremiehelme** [comment]
@SamuelPetragallo Also regarding the way the map is centered: the legend is not taken into account. Now, looking at the prints, it seems it's even delinked from the map in the pdf.

Wondering whether we could actually make that standard: 2 thirds for the map, 1 third for the legend

Should we systematically check whether 2 report sections can actually fit on 1 A4 (it's the case for the smallest sections) and "merge" them when feasible?

(More generally wondering how we should discuss issues/suggestions on this as it's likely that more refinements will be made along the way and using a single thread may become messy)

**Comment by jeremiehelme** [comment]
@SamuelPetragallo @luna404 @JeffDotingco I've pushed a fix for the map issues to staging

The map now take the same height then what's defined in the dashboard. It should solve the problem with the zoom level and the legend having a scrollbar

For most cases, the dashboard pages display well on one print page. if you find a page that doesn't display right, I can investigate

**Comment by luna404** [comment]
@jeremiehelme I like the new map size :). When I print it it cuts off part of the map. Not sure if this is a bug or just an issue with chrome. 

![image](https://user-images.githubusercontent.com/18245059/81693437-2fec2d80-9460-11ea-9845-05eb0c1ce451.png)

**Comment by luna404** [comment]
related to comment in issue #508

**Comment by luna404** [comment]
Not sure how you are controlling the width of the legend. Any chance it would be possible to also limit the width in the map or introduce line breaks similar to how you do it on the chart. In the example below, the map legend seems to be dis-proportionally large because of the long title.

https://herams-staging.org/project/24/pdf
![image](https://user-images.githubusercontent.com/18245059/86009481-9205ef80-ba1a-11ea-83ab-e1d809614ad8.png)

**Comment by jeremiehelme** [comment]
I've limited the width of the map legend title, it should be better now
