### ISSUE TITLE
Project popup messages

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#422]
@SamuelPetragallo suggest we rework the messages a bit.
here are the different messages :

**Loading Failed**
In Progress
Datas for this project are being collected. When it becomes active this popup will show key metrics and allow access to the project dashboard.

**Target Project**
In Progress
This project is in the process of being set up. When it becomes active this popup will show key metrics and allow access to the project dashboard.

**Ongoing Project without datas**
In Progress
Datas for this project are being collected. When it becomes active this popup will show key metrics

**Comment by SamuelPetragallo** [comment]
Thanks @jeremiehelme 

Wondering whether we could actually simply limit the text to "In Progress" for all 3 cases (they should be rare cases anyway)?

@luna404 what do you think?

Loading Failed
In Progress
Datas for this project are being collected. When it becomes active this popup will show key metrics and allow access to the project dashboard.

Target Project
In Progress
This project is in the process of being set up. When it becomes active this popup will show key metrics and allow access to the project dashboard.

Ongoing Project without datas
In Progress
Datas for this project are being collected. When it becomes active this popup will show key metrics

**Comment by jeremiehelme** [comment]
**Loading text**
Loading project summary
We're getting your summary ready...

**Comment by jeremiehelme** [comment]
Here is the loading

![Capture-d’écran-2020-05-04-à-10 00 39](https://user-images.githubusercontent.com/2345926/80946405-47873e80-8dee-11ea-8a89-d5bc9d79e2d8.png)

**Comment by jeremiehelme** [comment]
Removing the messages
Adding an error message and a refresh button if the loading fails

<img width="444" alt="Capture d’écran 2020-05-06 à 17 24 29" src="https://user-images.githubusercontent.com/2345926/81196970-00e93e00-8fc0-11ea-8b70-51d54536ed84.png">

<img width="445" alt="Capture d’écran 2020-05-06 à 17 24 41" src="https://user-images.githubusercontent.com/2345926/81196978-02b30180-8fc0-11ea-8d89-04dd7758e0b9.png">

<img width="459" alt="Capture d’écran 2020-05-06 à 17 24 53" src="https://user-images.githubusercontent.com/2345926/81196982-047cc500-8fc0-11ea-8287-eb9d08ee531e.png">
