### ISSUE TITLE
Favorite workspaces integration

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#423]
@SamuelPetragallo : can we something else than hearts (and also maybe use hollow when the symbol is not selected vs black fill currently)?

**Comment by jeremiehelme** [comment]
We can use a star instead

here is the use menu for the map and dashboard pages 

![HeRAMs-Home](https://user-images.githubusercontent.com/2345926/80971005-67cdf200-8e1c-11ea-8a0d-a112afb47494.jpg)

![HeRAMs-Admin](https://user-images.githubusercontent.com/2345926/80970999-66042e80-8e1c-11ea-9792-0abecef28296.jpg)

**Comment by SamuelPetragallo** [comment]
Yes for the Star

For the left menu let's not use titles ("emergency specific" and "regular projects"): let's simply place the projects with the "emergency specific" status upfront (and in alphabetical order)

**Comment by SamMousa** [comment]
I don't like that. We should use icons or colors. Not change sorting in a magical way that is not intuitive and often not logical

**Comment by SamMousa** [comment]
Ie if I'm looking for a project I might not know what status it has. Alternatively if I already know changing the sort order doesn't add anything

**Comment by luna404** [comment]
The star should change to filled if a project was added to the favorites page. This is currently not working. 
Also, if you click on the star in the favorites page the workspace should be removed from the favorites page.

**Comment by SamMousa** [comment]
> Also, if you click on the star in the favorites page the workspace should be removed from the favorites page.

That will only happen on refresh (to allow you to easily change your mind)

**Comment by jeremiehelme** [comment]
Depends on #430
