### ISSUE TITLE
ResponsePicker staging env

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#424]
Setup a way to test response picker changes

**Comment by SamMousa** [comment]
@jeremiehelme I have a solution.

I have altered the ResponsePicker to conditionally load a different class. To use this you need to do the following:

- On the server checkout another commit in the `ResponsePicker/test` folder. Note I have currently used the test branch for it, you can use any branch even master.
- Then add to the URL of that shows the response picker (extract it from the iframe) add the query param: `test=ResponsePicker`.

Let me know if you need help.

**Comment by jeremiehelme** [comment]
I've checked out the test branch

if I add "test=ResponsePicker" to the iframe url, it will use /test/ResponsePicker.php 
and I can make the necessary changes in this Class without messing the prod version

Perfect !

**Comment by SamMousa** [comment]
Great!
