### ISSUE TITLE
Graphic charter

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#425]
Gather elements we use 
- Icons 
- Logos 
- Fonts 
- Colors

**Comment by jeremiehelme** [comment]
@SamuelPetragallo 
Here is a folder with 
- Illustrator file containing the icons, logos and colors
- link to the font on google fonts
- Exports in png

![Capture d’écran 2020-05-05 à 16 18 37](https://user-images.githubusercontent.com/2345926/81076602-1bea7e00-8eec-11ea-97ec-39011d5fa376.png)

[Herams-elements.zip](https://github.com/HeRAMS-WHO/herams-backend/files/4581263/Herams-elements.zip)

Let me know if you need other elements

**Comment by SamMousa** [comment]
Put these in a resources folder in this repository please. That way we can version them as well!

**Comment by jeremiehelme** [comment]
Added in #445

**Comment by jeremiehelme** [comment]
@SamuelPetragallo would it be useful to have a page listing the files ?

**Comment by luna404** [comment]
I think for us it's enough to have them on the Google Drive folder. 
[Link ](https://drive.google.com/drive/folders/168D78HLrrCGnV1N6P1hY8RhKEHsqzrBj?usp=sharing)
