### ISSUE TITLE
Excel export / Arabic

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#428]
@SamMousa we're having issues with the excel export for Yemen when asking for headers and responses as text

We've looked at all possible options of why this may be breaking but couldn't find a satisfying answer, plus it actually works from ls which means this may be related with the frontend excel download itslef

Could you please look at that more specifically?

(Fairly high urgency)

**Comment by SamMousa** [comment]
Did you:

- Check if it works if you use CSV?
- Check if it works if you use a different language?

**Comment by SamMousa** [comment]
It works for me on staging.

**Comment by SamuelPetragallo** [comment]
> Did you:
> 
> * Check if it works if you use CSV?
> * Check if it works if you use a different language?

It works on csv (@jeff and @luna404 to confirm)
It works in english too

Arabic seems to be the issue

**Comment by SamuelPetragallo** [comment]
> It works for me on staging.

Have you tried on production?

**Comment by SamMousa** [comment]
> Have you tried on production?

I have not. Nothing in your issue mentions prod (or staging for that matter)...
Nor does it say what the issue is...

**Comment by SamuelPetragallo** [comment]
I've gotten rusty on this...

Excel download with text header and aswers in arabic for Yemen on production (https://herams.org/project/34/export)

The file downloads, but is impossible to open: Excel breaks.
Note that where Excel breaks, Numbers (Mac) works (@JeffDotingco ).

Also note that when downloading the same data through ls (with the same settings: headers and answers in arabic), opening it excel then works perfectly fine

**Comment by SamMousa** [comment]
Limesurvey doesn't have xlsx export. It exports csv renamed to xls if I remember correctly. That's not a proper solution.

I'll try to reproduce on excel; libreoffice works fine.

**Comment by SamMousa** [comment]
I have found yet another method for create XLSX files, it is also faster.

Please give it a go and let me know the results. @luna404 the full export for yemen now takes ~ 15 seconds for me.

**Comment by luna404** [comment]
This is great. It also seems to solve the issue we had with Excel crashing on Windows computers when you try to open the file.

@JeffDotingco I don't see any issue with the download, but you are much more familiar with Yemen. When you have time, can you check if this resolves the [issue #6](https://github.com/HeRAMS-WHO/herams-support/issues/6)

**Comment by SamMousa** [comment]
That's the exact same issue

**Comment by JeffDotingco** [comment]
> This is great. It also seems to solve the issue we had with Excel crashing on Windows computers when you try to open the file.
> 
> @JeffDotingco I don't see any issue with the download, but you are much more familiar with Yemen. When you have time, can you check if this resolves the [issue #6](https://github.com/HeRAMS-WHO/herams-support/issues/6)

Hi @luna404, agree there is nothing wrong with the excel export. Thanks @SamMousa for the support!. :) The issue still persists in opening the exported excel data wherein it can't be opened when you enable "TEXT HEADER", enable "ANSWERS AS TEXT" and enable Arabic as the language. Otherwise the excel file works fine if "Text Header" is disabled even if language is Arabic. 

However, I can open the file (enable "TEXT HEADER", enable "ANSWERS AS TEXT" and enable Arabic as the language) in Numbers (equivalent of excel in Mac). Please find below:

<img width="1680" alt="Screen Shot 2020-05-20 at 12 14 10 PM" src="https://user-images.githubusercontent.com/50957748/82404661-69dab680-9a94-11ea-937c-37d9ff130e5c.png">

**Comment by JeffDotingco** [comment]
BUT for STAGING, exported excel data wherein CAN BE OPENED in excel when you enable "TEXT HEADER", enable "ANSWERS AS TEXT" and enable Arabic as the language. 😃😃😃

<img width="1680" alt="Screen Shot 2020-05-20 at 12 32 00 PM" src="https://user-images.githubusercontent.com/50957748/82405351-36992700-9a96-11ea-804f-ecce79e7e561.png">

**Comment by JeffDotingco** [comment]
works on staging. Excel download of HeRAMS Yemen (TEXT HEADER: ON, ANSWERS AS TEXT, ARABIC language). Can already be opened in Excel. 
<img width="1680" alt="Screen Shot 2020-06-12 at 5 57 51 PM" src="https://user-images.githubusercontent.com/50957748/84490915-61158300-acd6-11ea-803f-4f823b008679.png">
