### ISSUE TITLE
Chart alignment

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#43]
Currently the pie chart, its title and its legend are all rendered on a canvas.
This gives us limited control and causes charts to not be aligned consistently:
![image](https://user-images.githubusercontent.com/547021/54427749-ad60c480-471b-11e9-86e7-b4483371c0e0.png)

Also, due to the nature of rendering text to a canvas, text may become blurry.

In a future release we should render the legend and title externally, this will give us more control.

**Comment by luna404** [comment]
To add to this, if legends are long, the chart itself is no longer visible. 

![image](https://user-images.githubusercontent.com/18245059/62924488-81239f80-bdb0-11e9-954c-6f5b97867f1a.png)

**Comment by SamMousa** [comment]
@jeremiehelme what's your view on this?

We could make the legend constant width, but that won't work if we don't know what the labels are in advance.
@SamuelPetragallo we could add a configurable legend width if you think that it'll be used.
