### ISSUE TITLE
Add to favorites error

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#430]
I get an error when I try to add a favorite on staging (and prod actually)
With Burkina Faso for example 
https://herams-staging.org/project/40/workspaces

![Capture d’écran 2020-05-06 à 10 43 45](https://user-images.githubusercontent.com/2345926/81156746-8c45dd80-8f86-11ea-9e22-31a32d51c307.png)

Also receiving a 403 error when trying to access the favorite page 
https://herams-staging.org/user/favorites
![Capture d’écran 2020-05-06 à 10 46 39](https://user-images.githubusercontent.com/2345926/81157126-f3639200-8f86-11ea-8df7-339fb714059e.png)

Probably just a problem with the rights ?

**Comment by SamMousa** [comment]
It seems I have not explicitly allowed all logged in users to use this action, meaning only admins have permission.

-- note for testing: be sure to use non-admins accounts when testing non-admin features.
