### ISSUE TITLE
Favorite feature not available to some users (PROD)

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#432]
I used the account of Mustafa in PROD environment: You can't click the favorite icon and error occurs if you click the favorites icon (beside your name)
![favorite 1](https://user-images.githubusercontent.com/50957748/81276623-d95ca900-9085-11ea-9a34-f1804d3bf2af.jpg)
![favorite 2](https://user-images.githubusercontent.com/50957748/81276646-dfeb2080-9085-11ea-8481-ee93d1b72d7d.jpg)

**Comment by jeremiehelme** [comment]
Probably related to #430 but let's keep both for now

**Comment by SamMousa** [comment]
Actually it's a duplicate.
