### ISSUE TITLE
Add % of total HF to pie charts displaying single choice questions

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#435]
Pie charts in the dashboard only display the number of responses available for a question. As the survey logic prevents some questions from appearing, users misinterpret the results displayed in these charts. 

For single choice questions, can we display the percentage of total facilities below the number of records included. 

![image](https://user-images.githubusercontent.com/18245059/81284836-ef0aa800-905e-11ea-99cb-bcda24d127bd.png)

**Comment by luna404** [comment]
@jeremiehelme can you remind me why this has been blocked?

**Comment by jeremiehelme** [comment]
@luna404 Because, so far, the library used to create the chart doesn't allow to display two lines at the center of the chart.
I have to check if there is a new version of the library that would allow that, or try another solution I have in mind

**Comment by luna404** [comment]
Let's park this for later then. If we are reviewing the library used we should should have broader discussion to make sure it also address other shortcomings.
