### ISSUE TITLE
Login first brings an error message before loading the worldmap

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#436]
On staging:

After clicking "Home" (refresh I guess) I got through

**Comment by SamMousa** [comment]
Did you click the login button twice?

**Comment by SamMousa** [comment]
Also @SamuelPetragallo you should make sure to crop you screenshots..

**Comment by SamuelPetragallo** [comment]
> Did you click the login button twice?

I don't think I did - ? But try to reproduce the bug both by clicking once and twice and was unable to do reproduce - ?

**Comment by SamMousa** [comment]
Yeah it happens when multiple requests fire at the same time.
