### ISSUE TITLE
HeRAMS Yemen : Filtering issue wherein dashboard does not show anything until WS is refreshed

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#439]
Filtering issue in HeRAMS Yemen wherein dashboard does not show anything (map and graph) until WS is refreshed in PROD. The filtering issue is also in STAGING for HeRAMS Yemen  

- Tried filtering to some districts, graphs / maps are not shown until you refresh that particular WS. 

- Tried filtering in HeRAMS NGA (PROD and STAGING), filtering works fine 

- Refreshed a WS first before going to the HeRAMS Yemen dashboard and used that district / WS as filter, working fine in PROD and STAGING

<img width="1680" alt="Screen Shot 2020-05-09 at 2 12 13 PM" src="https://user-images.githubusercontent.com/50957748/81465972-9541e380-9200-11ea-8fb5-838ff9d24ed0.png">
<img width="1680" alt="Screen Shot 2020-05-09 at 2 13 53 PM" src="https://user-images.githubusercontent.com/50957748/81465976-9e32b500-9200-11ea-8c27-6240b26384f9.png">
<img width="1680" alt="Screen Shot 2020-05-09 at 2 14 31 PM" src="https://user-images.githubusercontent.com/50957748/81465985-a68af000-9200-11ea-9475-71e9ee02ac53.png">

**Comment by SamMousa** [comment]
Hmm, I did a sync Friday; could be that something went wrong there.

**Comment by JeffDotingco** [comment]
Dashboard after filtering It is working now @Sam. Had to refresh all the WSs first
