### ISSUE TITLE
Provide a link from herams to the user guide

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#440]
Question mark or else from all pages to the user guide: https://docs.herams.org/

@jeremiehelme guess that will be one for you

**Comment by SamMousa** [comment]
Open in a new window

**Comment by jeremiehelme** [comment]
Added a question mark to the user menu #448 

<img width="1680" alt="Capture d’écran 2020-05-14 à 14 42 38" src="https://user-images.githubusercontent.com/2345926/81935605-3231c180-95f1-11ea-8e01-557ed938376a.png">

<img width="1680" alt="Capture d’écran 2020-05-14 à 14 42 44" src="https://user-images.githubusercontent.com/2345926/81935610-34941b80-95f1-11ea-892e-4944e04bf7f5.png">

**Comment by luna404** [comment]
Perfect, I also like the new arrangement of the icons.
