### ISSUE TITLE
Allow linking a project to an external dashboard (URL)

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#441]
When using other dashboarding software (e.g. PowerBI) would be good to be able to reference that URL in project settings and have that external dashboard displayed in an iframe (or like) when going to project dashboards

**Comment by SamMousa** [comment]
This now works, have configured it here:
https://www.herams-staging.org/project/43/external-dashboard

Please have a look at how the configuration works, it uses the project override feature.
