### ISSUE TITLE
Allow pre-filtering a download

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#442]
As a means of reducing burden of download on the system

**Comment by SamMousa** [comment]
It makes no measurable difference for the system; so the argument for this is invalid.

**Comment by SamuelPetragallo** [comment]
If I downloaded Hospitals only in Mali that would be 20 records instead of 2576, wouldn't that make a difference?

**Comment by SamMousa** [comment]
No, we need to get them all from the database to filter them. Regardless, these kind of optimizations are relevant for 10.000+ records and only for requests that happen often (like loading menu options on every page)
