### ISSUE TITLE
Data export inconsistencies for Yemen

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#443]
Data comparison of the front-end (HeRAMs) and back-end (LS) exports revealed a few issues. 
[Yemen Data Comparison.pdf](https://github.com/HeRAMS-WHO/herams-backend/files/4608977/Yemen.Data.Comparison.pdf)

- Workspaces are not correctly refreshed after updating or creating a new record. If you look at the attached pdf, there are 6 records that were created over the last two days that do not appear in the HeRAMS export.  Same issue for records that were edited over the weekend.

- For `GEO10`, `MoSD10.other` and `MoSD8` LS has values of 0 which are exported as empty cells in HeRAMS. I actually think the blank fields in HeRAMS are better than 0, but I'm curious to understand the logic used here. **Note** the majority of differences identified in section 4 are due to this difference and should therefore not be considered an issue. 

- Discrepancies in the number of columns created for ranking questions. E.g. in HeRAMS there are 8 columns for `HFFUNCTx` while there are only 5 in LS. It seems like LS ignores the value set for `Maximum columns for answers` if there are fewer answer options available. In my opinion this needs to be addressed on the business side. If we only allow users to select three answer options, why would we need to create more than 3 columns? This just creates empty columns in the exports. In the below example, the `Maximum columns for answers` should be set to 3. 
![image](https://user-images.githubusercontent.com/18245059/81550128-17a4e180-9380-11ea-9335-3ea58194477c.png)

- Workspace names in HeRAMS are not unique. @JeffDotingco there are three workspace all labelled as `Althwrh H`. In my opinion we should never use the same display text for multiple workspaces as this makes it impossible for users to distinguish these workspaces. **Note** the discrepancies in records for WS `Althwrh H` are due to my script not being able to distinguish workspaces with the same label. 
![image](https://user-images.githubusercontent.com/18245059/81547236-de6a7280-937b-11ea-80e8-27e2a4d1a1f6.png)

- On issue #439 : I thinks this was due to renaming the `GEO01` question to `GEO1` on Friday. @JeffDotingco did you refresh the workspaces after editing the survey structure? While this should be avoided by the person updating the survey, it can happen that we forget to refresh the workspaces (also it's a lot of work :) ). To limit the damage of errors like these, could we periodically refresh all data (e.g. over night)?

**Comment by JeffDotingco** [comment]
Thanks @luna404 for this. For Althwrh H, this is sorted by including district and governorate in the response table. Already refreshed all WSs in Yemen last Saturday, I also think that issue 439 was due to changing GEO01 to GEO1. :)

**Comment by SamuelPetragallo** [comment]
> * Discrepancies in the number of columns created for ranking questions. E.g. in HeRAMS there are 8 columns for `HFFUNCTx` while there are only 5 in LS. It seems like LS ignores the value set for `Maximum columns for answers` if there are fewer answer options available. In my opinion this needs to be addressed on the business side. If we only allow users to select three answer options, why would we need to create more than 3 columns? This just creates empty columns in the exports. In the below example, the `Maximum columns for answers` should be set to 3.
>   ![image](https://user-images.githubusercontent.com/18245059/81550128-17a4e180-9380-11ea-9335-3ea58194477c.png)

Agree: @JeffDotingco could you please review Yemen and ensure that for all ranking questions maximum number of answers (usually 3) = max number of columns please?

**Comment by JeffDotingco** [comment]
Yes @SamuelPetragallo, will do this later when no one is using HeRAMS Yemen

**Comment by luna404** [comment]
> Thanks @luna404 for this. For Althwrh H, this is sorted by including district and governorate in the response table. Already refreshed all WSs in Yemen last Saturday, I also think that issue 439 was due to changing GEO01 to GEO1. :)

@JeffDotingco including the governorate into the response table is not addressing my point. My issue is that all three workspaces have the same name in HeRAMS. So if you filter the list of workspaces for `Althwrh H` you get 3 workspace with the same name. How is a user supposed to know which of the three WS they are responsible for? (try this link https://herams.org/project/34/workspaces?Workspace%5Bid%5D=&Workspace%5Btitle%5D=Althwrh%20H) Why can't we change the WS name so that they are unique? If it's because they are all in the same district we could either add a lower admin level  to the WS name or simply label them as `Althwrh H 1`, `Althwrh H 2`, and `Althwrh H 3`.

**Comment by JeffDotingco** [comment]
Agree @luna404 . I'll just put Althwrh H (District, Governorate) for this. That way, easier for them to identify. :) Already deactivated the survey.

**Comment by SamMousa** [comment]
Note that columns in limesurvey are not related to ones in herams.

**Comment by SamMousa** [comment]
@luna404 I have create a raw data tool on staging.
For each workspace there's now a list button that takes you the list of responses for that WS.
For each response you can go to a compare page: https://www.herams-staging.org/response/105972/compare?survey_id=618734


It will show, in 3 columns:

- The data from the platform
- The latest LS data interpreted by the platform
- The latest LS data directly, freshly retrieved


Note that this does not do any data updating, it just retrieves the last version from LS and displays it, the goal is to identify problems.
I'm going to try it now on some of your identified responses

**Comment by SamMousa** [comment]
I identified one problem, that is now fixed (and also seems to be the primary one in your PDF): HeRAMS incorrectly concluded that a value of 0 is the same as empty.

I will push this to staging and refresh all data their.

**Comment by SamMousa** [comment]
I have now also added a table to the bottom of the page that shows what the response export would look like if exported, but then transposed.

The idea of the page is that any suspected error within a single response should be identifiable there. It is not meant to provide a quick overview of the data or be easily readable. The list of fields in LS is long (700) and this means the page is very very large.

**Comment by luna404** [comment]
There seem to be no data discrepancies on staging right now [link](https://drive.google.com/file/d/1GVKrc-Nkgat2W6F_08UU7QheNfFR7Abf/view?usp=sharing) , which mean the 0/empty difference is gone. However, my primary concern is the first point I made 
`Workspaces are not correctly refreshed after updating or creating a new record. If you look at the attached pdf, there are 6 records that were created over the last two days that do not appear in the HeRAMS export. Same issue for records that were edited over the weekend.`

Also, @JeffDotingco has made some changes to the survey structure, we now have 200 unused columns if you export the data from HeRAMs. Can we introduce some sort of check that columns that have been deleted from LS are also removed from the HeRAMS database or at least the export?

@JeffDotingco I rerun the data check script on production and there are **a lot** of discrepancies [link](https://drive.google.com/file/d/1Rv1kVYXbRW4D8XU4y2AfH4oUCj7ialn1/view?usp=sharing) for the MoSD1 variable. Have you made any changes to the data? It's no issue on staging where all workspaces were refreshed yesterday.

**Comment by JeffDotingco** [comment]
@luna404, I made some changes to MoSD1 to reflect UOID (HF code) but not the generated codes.

**Comment by luna404** [comment]
> @luna404, I made some changes to MoSD1 to reflect UOID (HF code) but not the generated codes.

@JeffDotingco  If you make changes to the data or the survey structure, you have to always refresh all workspaces or users understandably and rightly so complain that the LS export differs from the front-end export.

**Comment by JeffDotingco** [comment]
I made manual refresh of WSs after changing the data

**Comment by JeffDotingco** [comment]
> > @luna404, I made some changes to MoSD1 to reflect UOID (HF code) but not the generated codes.
> 
> @JeffDotingco If you make changes to the data or the survey structure, you have to always refresh all workspaces or users understandably and rightly so complain that the LS export differs from the front-end export.

You're right @luna404 , it is not yet reflected yet in the platform in reference to MoSD1. Prolly because I just replaced MoSD1 while survey is not deactivated. I sort this to reflect the new answers for MoSD1

**Comment by luna404** [comment]
@SamMousa can you have a look at this specific example.

https://herams.org/response/117797/compare?survey_id=618734

Variable HFHR01_SQ006_SQ001 = 1 in all three columns (`Our latest data`, `Our interpretation of the LS data`, and `Data fresh from LS`). 
![image](https://user-images.githubusercontent.com/18245059/82438852-fa67c580-9a99-11ea-8ea8-67e7c100469e.png)


However, in the `Response as it would be exported` table the corresponding field is empty. 
![image](https://user-images.githubusercontent.com/18245059/82438818-efad3080-9a99-11ea-8e72-0abc4c024470.png)


I have several cases with similar behavior all of which, according to the datestamp in LS, where edited yesterday after you refreshed the workspaces or today.

**Comment by SamMousa** [comment]
Can you check that this still happens on staging? 
When I look at, for example this one: https://herams-staging.org/response/74865/compare?survey_id=391149

It seems the same question type is exported properly (look for HR1)

**Comment by JeffDotingco** [comment]
The same responses for HR ([HR1[HR7_HR1]]==2, the rest 0) in Our latest data, Our interpretation of the LS data, Data fresh from LS, Response as it would be exported (but vertically) @SamMousa

**Comment by SamMousa** [comment]
So this works??

**Comment by JeffDotingco** [comment]
I'll check Yemen. This was NGA

**Comment by JeffDotingco** [comment]
Works in Staging: Compared a HF record raised in this issue (Sana'a / Bani Hushaysh, HF ID: 304023, ID: 117797) in PROD. Compared the record in PROD in Staging. Staging record for HR is already updated: 

PROD:
<img width="1317" alt="Screen Shot 2020-06-12 at 5 47 49 PM" src="https://user-images.githubusercontent.com/50957748/84489999-1f380d00-acd5-11ea-8cc5-08b7b28efe20.png">

STAGING:
<img width="1316" alt="Screen Shot 2020-06-12 at 5 43 08 PM" src="https://user-images.githubusercontent.com/50957748/84490021-27904800-acd5-11ea-819c-002df7803d70.png">

PROD: https://herams.org/response/117797/compare?survey_id=618734
SATGING: https://herams-staging.org/response/117797/compare?survey_id=618734

**Comment by SamMousa** [comment]
@luna404 let's create a new issue instead of compounding this issue, which is already an issue combining several issues, even more.
