### ISSUE TITLE
Add a text  / link dashboard element

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#444]
Add a new dashboard element for directing users to another link.

Settings:
- Title
- Description
- URL
- Open in new window 

- [ ] Create design (@jeremiehelme)

**Comment by SamuelPetragallo** [comment]
@SamMousa could that be part of the upcoming quick release?
@luna404 finalized the dashboard for Mali, t looks great and we'd like to be able to share it "through HeRAMS"

**Comment by SamuelPetragallo** [comment]
Also @SamMousa discussing this now we wondered whether it would actually be better to be able to "override" the dashboard URL (through project settings for example) so that the "dashboard" link from the popup or any other links to dashboards direclty redirects users to the external dashboard - ?

Thanks

**Comment by SamMousa** [comment]
I think that's a very bad idea.
As discussed this morning, advantages of doing this is a dashboard element:

- Allows you to link to more than just external reports
- Allows you to inform before he leaves the platform
- Allows hybrid reports where some charts are shown on the platform
- Properly fits in the dashboarding system

Reasons not to do the other approach:
- It only solves a very specific use case
- The user will no longer know what happens when he clicks the button
- Technically it's another override that will cause confusion and increased need for support later on.

I believe @luna404 said this:

> As long as there's a clear way for users to get there it should be fine

This constraint can definitely be satisfied and I don't see how reducing the path by 1 click is worth all the downsides.
