### ISSUE TITLE
Add an "ISO3 Code" field to projects so that they can be mapped against countries in the emergency dashboard

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#446]
WHO Emergency Dashboard which will display Project level data uses country lists in various formats to consolidate data from various sources.

We've chosen "Projects" over countries to avoid a lot of potential headaches. But being able to map projects against 1 or mutliple countries by simply referencing ISO3 Code would give HeRAMS more visibility on the ED

@SamMousa guess that's mostly for you

**Comment by luna404** [comment]
@SamuelPetragallo do we have say on how this data will be aggregated in the WHO Emergency Dashboard? For Sudan and Mali we have the same facilities in two different projects, if they simply sum projects with the same ISO3 code they will double count health facilities...

**Comment by SamuelPetragallo** [comment]
The projects remain as separate entities: so for Sudan there would be 2 HeRAMS projects listed wither respective names, url and metrics ;)

I've shared the link to the UAT with you so you can have a look. Took me a while to even find the layer... (graphically a lot can be done)

**Comment by SamMousa** [comment]
What about just using the GPS coordinates to find the country and return it it in the API?
That way you solve the problem of contradictory data..

**Comment by luna404** [comment]
There are some cases where the project might not be in the country of concern. For example, one could argue that Gaziantep should be part of Syria as it concern Syrian refugees rather than Turkey. For this reason prefer to set the country manually rather than having it based on the GPS coordinates of the project.

**Comment by SamuelPetragallo** [comment]
Just thought that this will also allow us communicate on the number of countries (# of unique ISO3) in which projects are active

**Comment by SamMousa** [comment]
Added support for 1 iso code per project. Should arrive on staging soon.

**Comment by luna404** [comment]
@SamMousa is the list of country names fixed or will this update if a country name changes?

**Comment by SamMousa** [comment]
It is based on the ISO3166 standard and will update when the standard changes
