### ISSUE TITLE
Error exporting responses from LS

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#453]
I can't export data from LS anymore using the LS API. 

Retrieving the session key works fine, but when I try to export the responses I get the below error.

`{"id":1,"result":null,"error":"CDbCommand n'a pas pu ex\u00e9cuter la commande SQL : SQLSTATE[HY000]: General error: 3 Error writing file '\/tmp\/MY6hrWNA' (Errcode: 28 - No space left on device)"}`

**Comment by SamMousa** [comment]
The API creates large temporary files which is why we're no longer using it.

**Comment by SamMousa** [comment]
Fixed for now... this will be a recurring issue.

**Comment by luna404** [comment]
I will need to reactivate the automatic dashboard sync again once it is embedded in the platform. Are there any options to avoid this issue in the future, e.g. by doing regular cleaning of temp files?

**Comment by SamMousa** [comment]
We're doing that now, but depending on how often it happens it will have a big impact on the system.

**Comment by luna404** [comment]
Noted, closing the issue as it's been resolved for now.
