### ISSUE TITLE
Unable to login to hermas.org

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#455]
There is an issue with the login preventing users from accessing the platform.

When you try to login, it the system seems to be checking the credentials (you get an error if you use wrong credentials) but it's not proceeding to the worldmap, but just reloading the login page.

**Comment by SamMousa** [comment]
This is because the disk is full again, very likely because PowerBI is hammering the API.

/related #453

**Comment by SamMousa** [comment]
I discovered another directory LS is trashing the disk and have cleaned that up, should give us a bit more breathing room while we phase out the LS API.

**Comment by luna404** [comment]
I deactivate all the PowerBI refreshes for now.

**Comment by SamuelPetragallo** [comment]
> I discovered another directory LS is trashing the disk and have cleaned that up, should give us a bit more breathing room while we phase out the LS API.

Is it worth having some sort of a regular cleanup of these disks or at least a warning that they are nearing overload while we phase out of ls?
