### ISSUE TITLE
External dashboard only works for admins

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#458]
It seems the link to the external dashboard only works for admins, other users get the below error.

![image](https://user-images.githubusercontent.com/18245059/82551233-1d5cad00-9b60-11ea-8b53-e17a3bbfb130.png)

Sorry, I know this is my mistake for not testing it before the release.

**Comment by SamMousa** [comment]
Try now

**Comment by luna404** [comment]
Thanks, it working now.
