### ISSUE TITLE
Remove link to LS for users with no access

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#459]
Would it be possible to  only show the `backend administration` link for users who don't have access to LS.

If a user with no access to LS click on the `backend administration link` the get the below error.

![image](https://user-images.githubusercontent.com/18245059/82644989-784edc80-9c12-11ea-9d8b-8b7cdc250af7.png)

**Comment by SamMousa** [comment]
Currently no, we don't know if the user has access until we try.

**Comment by luna404** [comment]
Could we add a "fake" project level permission so that the link is only displayed for users with `Access to LS` permission. Making sure they actually do have access to LS would be up to us to manage. There are only very few users with access to LS so granting "double" access would be manageable from our side.

**Comment by SamMousa** [comment]
We could do it at the global level; doesn't make much sense to do it a project level since having it on multiple projects doesn't mean anything.

**Comment by luna404** [comment]
Agreed, doing it at the global level makes much more sense.

**Comment by SamMousa** [comment]
This will resolve itself when we move away from LS

**Comment by luna404** [comment]
Has been resolved (#695)
