### ISSUE TITLE
Error in filtering health facility records in the new data comparison tool

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#462]
Error in filtering health facility records using DATE, HF ID, LAST UPDATED filters in the new data comparison tool in STAGING:
<img width="1680" alt="Screen Shot 2020-05-25 at 5 52 42 PM" src="https://user-images.githubusercontent.com/50957748/82801857-8e79c880-9eb0-11ea-8562-99523ac79e12.png">

**Comment by SamMousa** [comment]
@JeffDotingco please also put the URL in the issue next time.

**Comment by JeffDotingco** [comment]
issue on error in filtering still persists in STAGING.

https://herams-staging.org/workspace/6113/responses?Response%5Bid%5D=&Response%5Bdate%5D=&Response%5Bhf_id%5D=2308005&Response%5Blast_updated%5D=&response-data-provider-page=1&response-data-provider-per-page=10

**Comment by JeffDotingco** [comment]
Works in staging now using a HeRAMS YEM WS 

https://herams-staging.org/workspace/6110/responses?Response%5Bid%5D=&Response%5Bdate%5D=&Response%5Bhf_id%5D=2305009&Response%5Blast_updated%5D=&response-data-provider-page=3&response-data-provider-per-page=10
