### ISSUE TITLE
Page title translations

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#465]
We could use something like this to support translations for standardized page names:

![demo](https://user-images.githubusercontent.com/547021/82904833-4e275280-9f63-11ea-8e4d-067f11b26f9b.gif)

This allows users to pick default page names but also configure their own.

**Comment by SamMousa** [comment]
What do you think of this? This is simple to implement and can help users to pick default names without taking away their freedom.

**Comment by luna404** [comment]
My only concern with this is that we end up with multiple languages in the dashboard pages which might be more confusing than helping.

**Comment by SamuelPetragallo** [comment]
Same here, think it will create more issues than anything and an additionnal "standard" to maintain where flexibility is probably better. I think it shouldn't be an issue for country admins to add their language in when creating/managing the dashboard (provided all other translations will pretty much be automated)

**Comment by SamMousa** [comment]
> think it shouldn't be an issue for country admins to add their language in when creating/managing the dashboard 

The issue with this approach is that it effectively removes multi-language support from those dashboards. Local admin is very unlikely to speak all languages which means we'll have only partial translations and worse, we won't really know the source language.

If we want the data to be accessible in multiple languages standardization will be worth it, even if it is not available for all page titles.
Note that while I have proposed a specific list of page titles, we can always expand on this and make it a living standard. It doesn't even have to be an enforced standard; just suggesting things will direct users towards more uniform choices.

**Comment by SamuelPetragallo** [comment]
@SamMousa not sure where we stand with this - can you advise?

**Comment by SamMousa** [comment]
It is ready for testing as the label says

**Comment by luna404** [comment]
The drop-down works, but we need to add the following items to the list

- Building and equipment condition
- Management and support
- Basic Amenities
- Water
- Sanitation
- Communication
- Cold chain
- Power
- Service availability
- Waste management

@JeffDotingco please add if I missed anything

**Comment by JeffDotingco** [comment]
Health Information

**Comment by JeffDotingco** [comment]
I am also suggesting of another drop-down especially for Yemen which is only "Building Condition". We missed "Functionality status". :)

**Comment by luna404** [comment]
Would it be possible for the drop-down list to have a scroll bar so users can see all available pages names rather than having to filter for something that might or might not exist.

**Comment by SamMousa** [comment]
> Would it be possible for the drop-down list to have a scroll bar so users can see all available pages names rather than having to filter for something that might or might not exist.

Maybe, but let's put that in a new issue? It is unrelated to the original issue.
