### ISSUE TITLE
Weblate email notification not working

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#466]
There seems to be an issue with weblate not sending emails.

I tried inviting new users as well as resetting a password for an account and neither of the emails is going through. 

I also noticed that I have received any notifications from weblate since mid March. I used get an update on outstanding translations etc.

**Comment by SamMousa** [comment]
I think I fixed it; let me know if it works now.

**Comment by luna404** [comment]
Thanks, it seems to be working again.
