### ISSUE TITLE
Dashboard preview map does not zoom to project

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#467]
The preview map in the dashboard configurations does not zoom to the project, but seems to be fixed on Nigeria for all project.

Ideally, the preview map should have the same zoom level as the actual map displayed on the dashboard.

https://herams.org/element/84/update

**Comment by luna404** [comment]
The zoom is working, but depending on the legend size the preview can be relatively useless. Can we improve the layout of this a little? As the legend might always be an issue, could just remove it for the preview? I don't think it's necessary as the list of categories is already present in the element settings part of the page 

![image](https://user-images.githubusercontent.com/18245059/84494130-3e20aa00-aca9-11ea-95e7-6ac4bd9c8e53.png)

**Comment by SamMousa** [comment]
No we shouldn't. Purpose of the preview is to use the exact code as used in the dashboard. We van make it popup in a new window or enlarge it below the settings

**Comment by luna404** [comment]
Can we make the update element card smaller. The color bard don't need to be this wide. This would already give us some more space for the map.

**Comment by luna404** [comment]
The preview map is nice and big now, but at the cost of the entire layout, which to me isn't a good solution. 

![image](https://user-images.githubusercontent.com/18245059/85403551-da766680-b55d-11ea-8e8d-26751d5c360d.png)

What do you think of arranging the two sections vertically instead?

**Comment by SamMousa** [comment]
@jeremiehelme could you take this?
I have prepped the preview so that it should render properly whatever size you choose for its container. (I swapped the 8-4 ratio to 4-8, but more options are possible, as well as the one suggested by @luna404 ).

**Comment by jeremiehelme** [comment]
related to #519

**Comment by jeremiehelme** [comment]
Adapted the layout to use the grid system.
Now the element being updated is on top, and takes the space it should occupy when used in the dashboard

**Comment by luna404** [comment]
The layout is still not ideal. I'm also not sure what the best way is to improve this, but if you look at the screenshot below, half my screen is empty, but I'm still not able to view the settings and the preview at the same time (which would be the ideal case).

Maybe I was wrong and the horizontal arrangement is better after all.
In any case the settings should be given higher priority than the preview. Meaning if we stay with the vertical alignment, it would be preferable to the settings above the preview and if we go back to the horizontal alignment the settings should be on the left. 

![image](https://user-images.githubusercontent.com/18245059/87038889-a69e7080-c1ee-11ea-846c-dd19a33c75cc.png)

Also for the settings, is there a way you can make the widths more dynamic. There is a lot of empty space on my screen but it still breaks the category labels on two rows.

![image](https://user-images.githubusercontent.com/18245059/87038925-b4ec8c80-c1ee-11ea-9dd9-85bf5ecdc87c.png)

Feel free to make radical changes to this layout. For example some of the input fields (e.g. width and height) could be displayed in the same row. Similarly, the width of the color bar could be shortened if this helps avoiding the being spread across multiple columns, etc.

**Comment by jeremiehelme** [comment]
@luna404 I opened an issue specifically for the fields here #543

For this layout, I followed your suggestion :
- horizontal arrangement when possible, with the settings on the left and the preview on the right
- vertical arrangement otherwise, with the settings above the preview
