### ISSUE TITLE
Add array questions to dashboards

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#471]
Related to issue #271
The type of support provided by partner is collected as an array question. This question type is currently not support by the dashboard. This question type is also used extensively for the COVID surveys and would help to avoid having to use 3rd party dashboard applications. 

Would it be possible to add array questions with predefined answer options?

Here's a sample question. https://ls.herams.org/admin/survey/sa/view/surveyid/341175/gid/626/qid/9136

**Comment by SamMousa** [comment]
Note that the linked question uses EM expressions for question texts, so even if we support the question type, the question texts will not work like that.
Furthermore, each response will have different values for HFSUP3 so this means that the answers to the array questions can be about totally different values for.

Need a proper minimal English sample survey, not a full HeRAMS survey, just the bare minimum.

**Comment by luna404** [comment]
While in the long term it would be interesting to be able to filter by partner (HFSUP3), maybe for an initial version we could disregard the y-axis values. If we could map out the type of support (y-axis) by HF that would already be a good start.

The downside of this approach would be that it wouldn't work for the COVID-19 surveys. 


You can look at Nigeria as an example of an English questionnaire. https://ls.herams.org/admin/questions/sa/subquestions/surveyid/391149/gid/481/qid/7041

**Comment by luna404** [comment]
Depends on SurveyJS implementation
