### ISSUE TITLE
Add equation questions to dashboards

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#472]
Related to issue #271

Would it be possible to add equation questions to the type of questions supported by the dashboards? 

For example, it would be useful if we could map HF based on the expected service level which is depending on the type of HF. Here's an example equation question https://ls.herams.org/admin/survey/sa/view/surveyid/341175/gid/622/qid/9116

**Comment by SamMousa** [comment]
Equation types have no answer options so they are open text questions; this makes it hard to use them in our dashboards.

**Comment by SamMousa** [comment]
After thinking about it some more I do not think we should do this.
What we could do, on the platform side, is support derived data.
(ie we implement some kind of equation system in the platform)

If we go that route we must decide when we do it, when responses are added / updated, or when displaying the data.

Specifically, do we want to be able to filter by derived data? 
I'd use the twig templating language for this, it is very powerful yet easy to implement on our side. 

Advantages of this approach:
- Not dependent on LS specific expression language
- Truly dynamic, will work on existing data and new data
- More easy to reuse across different dataset
- Well documented language  https://twig.symfony.com/
- Easy to extend with custom functions

This could also solve things like data cascading (if the whole facility is not functional all services are not being provided). We could for example provide whole records to the twig template which can then alter one or more fields.

Let me know your thoughts

**Comment by luna404** [comment]
If I understand this right, this would mean we would have to recreate the same equation in HeRAMS, which is fine with me. 

> If we go that route we must decide when we do it, when responses are added / updated, or when displaying the data.

As we are still having some issue with the updating of the data I would have said when we display the data. But open to your suggestion.

> Specifically, do we want to be able to filter by derived data?
I'd use the twig templating language for this, it is very powerful yet easy to implement on our side.

Yes, definitely.
