### ISSUE TITLE
Platform text/strings / suggestions

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#475]
1.	Project status is shown on the world map (?)
2.	Refresh data from limesurvey (ref to ls)
3.	Sign up for the HeRAMS platform (obvious ref to HeRAMS platform to be removed)
4.	Survey (need to understand what this stands for – for now: Formulaire)
5.	The aggregate availability of services per HF (needs rephrasing - ?)
6.	the page you are looking for doesn't exist (add “or has been moved”)?
7.	This will reload the page losing all other changes!! / Warning! / Success! (remove exclamation marks?)
1.	Update / Update & go to dashboard (change to “Save” not to confuse)
2.	Update element (same problem as above: shall we combine edit and save for these functions? – I’ve used “modifier” in french
3.	Update password, project, token, etc.
4.	Espace de Travail (my bad – let’s remove caps to espace de travail where relevant)
5.	We use this field to store the country for the project. (remove points when there’s only one sentence? – lots of cases)
6.	Are you sure you want to switch to this user for the rest of this Session? (cap letter on Session?)
7.	Are you sure you want to switch to this user for the rest of this Session? (can we use something like: Etes-vous sûr de vouloir continuer la session en tant que {user} ?)
8.	Become this user (I prefered Impersonate and would also suggest we use {user if feasible} – in french: Continuez la navigation en tant que {user})
9.	Hello (? - )
10.	If you did not make this request you can ignore this email (If you did not make this request please ignore this message?)
11.	If you don't want to change your password or didn't request this, just ignore and delete this message (shall we simply use the same/standard message as the one before: If you did not make this request please ignore this message)
12: Typo: A password reset email has **beent** sent to your address
13: Typo: A verification email has **beent** sent to your address
14: Typo: Creating a new **acount** for email:
15. Rephrase? We use this field **to store the country for the project**.
12.	“The Prime Team” 😊

**Comment by SamuelPetragallo** [comment]
@luna404 would appreciate if you can go through quickly and confirm/suggest otherwise before we implement and get the Arabic done, merci!

**Comment by SamMousa** [comment]
I"m not sure what I'm supposed to do with this, but please have a look at how @luna404 created a similar issue: https://github.com/HeRAMS-WHO/herams-backend/issues/477

**Comment by SamuelPetragallo** [comment]
It's not always easy to know where they appear, which is part of the issue, making translations/refactoring difficult.

But for cases where this is clear, can't you search for the text in the code? Would take me a lot more time having to point to specific parts of the platform

**Comment by luna404** [comment]
These are two different issue. 

This is one is translations we found in weblate that should be changed. As we only get the text string in weblate we don't always know where exactly this corresponds to in HeRAMS. We could give the weblate id though if that helps.

Issue #477 is strings that are not included in the translations. As they were identified in HeRAMS it's possible to give a url.

**Comment by SamMousa** [comment]
> This is one is translations we found in weblate that should be changed. As we only get the text string in weblate we don't always know where exactly this corresponds to in HeRAMS. We could give the weblate id though if that helps.

Yes, IDs always help. The weblate ID is fine then i  can get the actual exact source and use searching.
