### ISSUE TITLE
Platfrom - missing translations

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#477]
Missing Translations

| Text String | URL | Comment |
| ------------- | ------------- | ------------- |
| The Health Resources and Services Availability Monitoring System is a collaborative process for the monitoring of essential health resources and services in support to the identification of needs, gaps and priorities  | https://herams-staging.org/user/account  |
| Latitude  | https://herams-staging.org/project/28/update  |
| Longitude  | https://herams-staging.org/project/28/update  |
| Status  | https://herams-staging.org/project/28/update  |
| Visibility  | https://herams-staging.org/project/28/update  |
| Typemap As Json | https://herams-staging.org/project/28/update  |
| Overrides As Json | https://herams-staging.org/project/28/update  |
| Token |  https://herams-staging.org/workspace/4893/update|
| User | https://herams-staging.org/project/28/share | Table header, same for workspace permissions |
| Allowed | https://herams-staging.org/project/28/share | Switch status, same for workspace permissions |
| Denied | https://herams-staging.org/project/28/share | Switch status, same for workspace permissions |
| Settings | https://herams-staging.org/project/40/export | Same for workspace download |
| Advanced Settings | https://herams-staging.org/project/40/export | Same for workspace download |
| Include Text Header | https://herams-staging.org/project/40/export | Same for workspace download |
| Answers As Text | https://herams-staging.org/project/40/export | Same for workspace download |
| Language | https://herams-staging.org/project/40/export | Same for workspace download |
| Language options (Drop-down values) | https://herams-staging.org/project/40/export | Same for workspace download |
| On | https://herams-staging.org/project/40/export | Switch status, same for workspace download |
| Off | https://herams-staging.org/project/40/export | Switch status, same for workspace download |
| ID | https://herams-staging.org/project/28/pages | Table Header |
| Title | https://herams-staging.org/project/28/pages | Table Header |
| Parent ID | https://herams-staging.org/project/28/pages | Table Header |
| Sort ID | https://herams-staging.org/project/28/pages | Table Header |
| Title | https://herams-staging.org/page/16/update | Page Settings |
| Parent ID | https://herams-staging.org/page/16/update | Page Settings |
| Sort ID | https://herams-staging.org/page/16/update | Page Settings |
| Transpose | https://herams-staging.org/element/48/update | Element update |
| Code| https://herams-staging.org/element/48/update | Element update |
| Sort | https://herams-staging.org/element/48/update | Element update |
| Width | https://herams-staging.org/element/48/update | Element update |
| Height | https://herams-staging.org/element/48/update | Element update |
| Marker Radius | https://herams-staging.org/element/48/update | Element update |

**Comment by SamMousa** [comment]
Very clear issue, took me a while but I think I've found all of them.
Also added some tests that will allow us to detect missing labels for tested classes (which is not all classes yet)

**Comment by luna404** [comment]
User (first column header) in the project/workspace share page is still missing (https://herams-staging.org/project/27/share)
