### ISSUE TITLE
Message appears in the wrong place

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#479]
On prod, the message from the export "Enter a date to limit the export to the last record before or equal to the selected date for each health facility. To export all historic records of a health facility, leave the field blank." also appears in the filter section of the dashboard

Not sure who between @SamMousa and @jeremiehelme is on this one.

We (the others) will need to draft something maybe

**Comment by SamMousa** [comment]
Add a link to the page, a screenshot.. more details the easier it is

**Comment by SamuelPetragallo** [comment]
No specific URL for filter pages. Filter page of any dashboard applies. See screenshot:

![Picture1](https://user-images.githubusercontent.com/15345099/83723277-b69ac180-a63e-11ea-8d76-9fd8ff7e0177.png)

**Comment by SamMousa** [comment]
@SamuelPetragallo is this working? If so, use works on staging.

**Comment by SamuelPetragallo** [comment]
@FatmaGiha test
