### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#481]
Ideally, the platform and limesurvey should allow data collection on mobile.

So far, it's not really usable, as the menu hides most of the screen on the platform, and doesn't display well on limesurvey

First step should be to use a select box instead for the menu, and place it at the top of the page
For LimeSurvey, investigate the mobile themes from the last version

**Comment by jeremiehelme** [comment]
It seems like an important one. There is a few things that can be done quickly and could greatly improve UX

**Comment by luna404** [comment]
@jeremiehelme as discussed yesterday. Any improvements would be create, especially if it would enable users to enter data on mobile devices. However, as the future of LS is not certain, please don't spend too much time on this.
