### ISSUE TITLE
Git / Managing users

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#482]
Seems not everyone can see/ping other users on Git (I can't see Fatma, Caroline can't see me, etc.) and Markus Virtanene is still there.

Anything that can be done on this?

**Comment by SamMousa** [comment]
I'm not sure if Fatma is on github. You should be able to ping eachother as long as everyone is participating. Can you trying pinging as a new comment in this issue?

Ping here for testing: @JeffDotingco @SamuelPetragallo @luna404 @jeremiehelme

**Comment by SamuelPetragallo** [comment]
This s what I get in options - weird (note: Joey seems to be back already :D)

![image](https://user-images.githubusercontent.com/15345099/84166814-ba32ac00-aa75-11ea-909f-e831333aad19.png)

**Comment by SamMousa** [comment]
Try typing, suggestions are just that, suggestions. They are not an exhaustive list

**Comment by SamuelPetragallo** [comment]
It doesn't come through suggestions either - but if I type it in full it's there.
So it works, just not practical really

**Comment by SamMousa** [comment]
You should create an issue at github for that
