### ISSUE TITLE
Data aggregation & visualization: Only display existing HF on the dashboard 

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#484]
We were having a discussion on ways we could improve the data displayed on the dashboard. The main point we were discussing is "unknown"  being unsatisfactory as a category as this also includes non-operational and inaccessible HF. I have tried to split the proposed enhancements into 7 distinct issues so we can discuss each point individually.

**Issue 1**
One of the first question in the survey is asking whether a HF is existing, planned or closed. If a facility is planned or closed, the questionnaire will stop. Thus, no information is available for any of the questions displayed in the dashboard.

**Current behavior**
Planned or closed facilities show as "unknown" on all maps.

**Desired behavior**
These facilities should be systematically excluded from all dashboard elements. To achieve this, only records where MoSD4==A1 should be included in the dashboard.

**Comment by SamMousa** [comment]
That would be weird though: if a facility is damaged the charts go down, but then when it is closed the numbers go back up?

**Comment by luna404** [comment]
Closed and damaged facilities are not directly related. A facility that is destroyed or not functional can still be considered "existent". 
A facility will only be marked as closed if it is definitely closed and will not be repaired or reopened. These faculties are no longer part of the MHFL, but we would like to keep them in HeRAMS for historical reasons. 
On the dashboard we only display the most recent information. Thus, it makes no sense to include historic information on closed facilities.
