### ISSUE TITLE
Data aggregation & visualization: Split "unknown" category on maps into "non-operational", "inaccessible" or "no data"

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#485]
**Issue 2**
Questions that were not answered by the user and questions that were skipped due to the survey logic are not distinguishable in the dashboard maps as both are shown as unknown. 

**Current behavior**
If for example, a health facility is not functioning the survey is condition to end after that question. This means all subsequent questions are empty. On the dashboard maps this results in all downstream questions to be displayed as "unknown". 

**Desired behavior**
By default, each dashboard map should have two additional categories, "non-operational" and "inaccessible". Empty records should be evaluated to see if they meet either of the conditions below, and if true classified accordingly. 

- Non-operational: CONDB==A3 or HFFUNCT==A3, 

- Inaccessible: HFACC == A3. 

HFs that have no response and do not meet either of the above criteria are considered as "truly" empty and should be labelled with "No data". 

**Exception**
An exception is required for the following questions

- CONDB: Neither of the two labels (non-operational, inaccessible) should be displayed. 

- CONDE and HFFUNCT: Only the first part of the non-operational condition (CONDB==A3) should be evaluated. In addition, the caption should be "Destroyed".

- HFACC: Only "non-operational" should be shown. Accessibility of HF is assessed with this question. Thus, inaccessible is already included. 

**Note**: the logic should be "if empty evaluate the above conditions" and not "display if none of the above condition are met". This is important for the exception mentioned above. A HF that is functioning but inaccessible should show as functioning on the map displaying "HFFUNCT".

**Comment by JeffDotingco** [comment]
Just a suggestion of using sankey to visualize the flow of responses from damage status to functionality and accessibility:

![sankey example for CONB, HFFUNCT and HFACC](https://user-images.githubusercontent.com/50957748/84246989-02b39d80-ab3a-11ea-9bf6-2ffa6cd01585.png)

**Comment by luna404** [comment]
I like it. Just wondering on the cost/benefit of developing this. @JeffDotingco do you have other scenarios/questions where you think this type of chart would make sense?

**Comment by JeffDotingco** [comment]
I don't know if there is a "package" for sankey @luna404. I came up with this while going through the dashboard [secretly using a DOH account ;)] of a Swiss company Dure technologies providing support to the contact tracing of DOH / WHO PHL. It will be too much if this will be applied to all the health services.;)

**Comment by luna404** [comment]
Depends on #633

**Comment by SamMousa** [comment]
We should look into this one again with the new approach of using expressions.
