### ISSUE TITLE
Data aggregation & visualization: Option to always exclude non-function and inaccessible HFs

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#489]
**Issue 6**

As we were having a lot of discussion on whether or not to included non-functioning and inaccessible HFs into chart. As an argument could be made either way, we would like to know if it were feasible to implement a an option (similar) to the filter that would exclude all non-functioning and inaccessible HFs if selected by the user.

**Comment by SamMousa** [comment]
Isn't this already possible?
By just selecting the other answers in the filter? If yes, then this question can be rephrased more generically:

> Can we have filter presets?

**Comment by luna404** [comment]
Rephrasing the question, can we have preset filters?
