### ISSUE TITLE
Data aggregation & visualization: Ranking questions

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#490]
**Issue 7**
It is not possible to know how many HF reported a cause/obstacle from the charts. In addition, from the below chart it is not possible to conclude the percentage of HF having reported a cause.

**Current behavior**
Results for ranking questions are displayed as percentage of all responses available for a question. In the example below, the 173 corresponds to the number of responses available for this questions and not the number of HF reporting causes.

![image](https://user-images.githubusercontent.com/18245059/84163242-8e152c00-aa71-11ea-9608-b66ce956fef6.png)

**Desired behavior**

- Display causes as bar chart. Each bar should represent the percentage of HFs having reported the cause.
![image](https://user-images.githubusercontent.com/18245059/84163521-df252000-aa71-11ea-8a0d-dcc50c5ce661.png)

- Add a disclaimer stating the number of HF having responded to the question

**Comment by SamMousa** [comment]
These are several unrelated sub-issues:

- Percentage display (this applies to pie charts as well)
- Bar chart instead of pie (already possible I think?)
- Center number in pie should be correct

**Comment by luna404** [comment]
> Percentage display (this applies to pie charts as well)

Whether you display a pie chart by percentage or actual number will result in the same chart. This would only be for these bar charts. We could start with numbers instead of percentages if that makes it easier.

> Bar chart instead of pie (already possible I think?)

No, it might have been possible previously, but at the moment you can only choose between map and chart which is always a pie chart

> Center number in pie should be correct

The challenge with the ranking questions is that users can select more than one answer. The number displayed is the total number of responses. It would be more meaningful if we include information on the number of HF that responded to the question.

**Comment by SamMousa** [comment]
> No, it might have been possible previously, but at the moment you can only choose between map and chart which is always a pie chart

Have added a chart type option to the chart, you can now set it to bar. (Note that the bar does not have a legend at this time)

**Comment by SamMousa** [comment]
> Current behavior
Results for ranking questions are displayed as percentage of all responses available for a question. In the example below, the 173 corresponds to the number of responses available for this questions and not the number of HF reporting causes.

This assumption is incorrect. The center text of the pie, is always the sum of its part, I've checked the code. At that point in the code we do not even know the number of responses. Could it be that your example happened to have 1 response (on average) per HF? 
![image](https://user-images.githubusercontent.com/547021/84365064-38f02c00-abd1-11ea-8da1-95353913044a.png)
https://herams-staging.org/project/30

Seems to work as expected as far as I can tell
