### ISSUE TITLE
Publish the Annual Report on the platform

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#494]
We currently don't have a webpage for the project (work ongoing) and need to publish the Annual Report. Thought it may be good to do that in relation to the platform, either in docs.herams or else.

Solution needed quite quickly here as dissemination is sort of dependant on it now

**Comment by SamMousa** [comment]
How are we sharing the URL? Does it make sense to just set up WordPress at Herams.org and move app to app.herams.org? This is simple and fast. I'm not sure what the requirements are

**Comment by SamuelPetragallo** [comment]
Longer term we'll have a page on who.int for the HeRAMS "Initiative" (we're growing :p) - so that will be covered.

(Very) short term we want a URL pointing to the pdf report that can be re-twitted etc. I was thinking ideally that URL would somehow be linked to herams.org for consistency

**Comment by SamuelPetragallo** [comment]
Found a way to have it on who.int
