### ISSUE TITLE
No return option on account settings page

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#496]
The return button on the account settings page is no longer visible on staging, but there is one on production. 

Any chance this can be resolved with today's release?

**Comment by jeremiehelme** [comment]
Fixed the popup layout and the close button 

![Capture d’écran 2020-06-12 à 16 19 31](https://user-images.githubusercontent.com/2345926/84512659-961ad900-acc8-11ea-969d-85742d8e66ed.png)

**Comment by luna404** [comment]
@jeremiehelme thanks, I'll mark this issue for release, but I will create a new one to address the jumping around of the tabs. In my opinion the tabs should have a fixed position so it's not jumping around if you move from one tab to another.
