### ISSUE TITLE
Align tabs on user account page

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#503]
The three tabs Profile, Password, Email, should be fixed on the same position regardless of which tab a users is on. Right now it changes from one tab to another.

https://herams-staging.org/user/account
![image](https://user-images.githubusercontent.com/18245059/84514022-a469f480-acca-11ea-990e-72633ad922c0.png)

![image](https://user-images.githubusercontent.com/18245059/84514001-9a47f600-acca-11ea-9881-8a5d20f65a2b.png)

**Comment by jeremiehelme** [comment]
Thank you @luna404, It should work now

![Capture d’écran 2020-06-12 à 17 31 35](https://user-images.githubusercontent.com/2345926/84519625-a5068900-acd2-11ea-9c92-30aa1ebba9c9.png)
