### ISSUE TITLE
Password reset is also not working in STAGING 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#504]
Password reset is not working in STAGING: https://herams-staging.org/user/request-reset
But STAGING platform could still identify if entered email for password reset is not known or not yet verified.

**Comment by SamuelPetragallo** [comment]
From what you describe I think it's the same issue as https://github.com/HeRAMS-WHO/herams-backend/issues/502 (problem with the emailing system)

**Comment by SamMousa** [comment]
@JeffDotingco, what does "not working" mean?

**Comment by JeffDotingco** [comment]
Agree @SamuelPetragallo this is related to #502. I just raised this to also consider password reset when fixing #502. The issue is about having an error when you request for a password reset after putting your email address in the field. 

https://herams-staging.org/user/request-reset

<img width="1680" alt="Screen Shot 2020-06-15 at 2 15 20 PM" src="https://user-images.githubusercontent.com/50957748/84623876-d1104d00-af12-11ea-8014-1c7b8398949e.png">

**Comment by SamMousa** [comment]
Duplicate of #502
