### ISSUE TITLE
WS sharing bug

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#507]
Have shared https://herams-staging.org/workspace/4893/share with user 10164 - user appears as "Deleted user"

**Comment by SamMousa** [comment]
Did you check after my comment?  The permission is gone

**Comment by SamuelPetragallo** [comment]
Still shows "Deleted user" instead of user's name, while the user shows in the user list (both in staging and dev)

![image](https://user-images.githubusercontent.com/15345099/84623410-7dd0d700-aedf-11ea-8684-22eb5a59b324.png)

**Comment by SamMousa** [comment]
The user doesn't have a name; which is why it defaults to Deleted User.
