### ISSUE TITLE
Project settings: Improve action button layout

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#510]
@jeremiehelme can you change the layout of the two action button at the bottom of the page to make them appear on one line and center align the text for both buttons?

https://herams.org/project/16/update

![image](https://user-images.githubusercontent.com/18245059/84643189-c6978880-aefd-11ea-845c-e2dbd749ed84.png)

**Comment by jeremiehelme** [comment]
related to #493
