### ISSUE TITLE
Error in exporting excel file in PROD

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#511]
Error in exporting excel file in PROD. I tried HeRAMS Yemen and Cox's Bazar. But downloading excel file is working in STAGING.

https://herams.org/project/34/export
<img width="1680" alt="Screen Shot 2020-06-15 at 5 59 05 PM" src="https://user-images.githubusercontent.com/50957748/84644701-15f7ac00-af32-11ea-9eed-aafc71f51cd5.png">

**Comment by SamMousa** [comment]
Fixed!
