### ISSUE TITLE
Functionality and service availability not showing for languages other than English

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#512]
The functionality and service availability pie charts only show in English

english
![image](https://user-images.githubusercontent.com/18245059/84645926-a4076e80-af01-11ea-8766-90aeef1d1e7e.png)

french
![image](https://user-images.githubusercontent.com/18245059/84646012-c4cfc400-af01-11ea-832b-cf7cb2d745d2.png)

**Comment by SamMousa** [comment]
On which environments?

**Comment by luna404** [comment]
Both

**Comment by jeremiehelme** [comment]
@SamMousa I left untranslated strings in the popup js.
I can create the translated strings in php and give them to the popup.
Is it the correct way, or is there a better way ?

**Comment by SamMousa** [comment]
> Is it the correct way, or is there a better way ?

For now that's the easiest.
