### ISSUE TITLE
Missing translations: Worldmap pop-up

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#513]
Missing elements:

- Health facilities
- Contributors
- Chart titles and legends

![image](https://user-images.githubusercontent.com/18245059/84646418-5d664400-af02-11ea-8284-481a7e0081c8.png)

**Comment by jeremiehelme** [comment]
Related to #512

**Comment by luna404** [comment]
The (missing) translations are there, but while it's loading the pop-up users sees the below message. Is this just because of the missing translation?

![image](https://user-images.githubusercontent.com/18245059/85373067-04666380-b533-11ea-8979-050cdcda5370.png)

**Comment by SamMousa** [comment]
They might not have been updated on the platform yet
