### ISSUE TITLE
Pop-up hidden behind menu

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#514]
I think this has been resolved previously but might have been reintroduced with the aggregation of the points.

If you load a pop-up on the worldmap it no longer zooms in. This results in the pop-up for some countries hiding behind the menu. It's not affecting aggregated points. 

![image](https://user-images.githubusercontent.com/18245059/84647843-49234680-af04-11ea-9868-d7694838ca55.png)

**Comment by jeremiehelme** [comment]
I think this is resolved, as the map moves and zoom when clicking on a cluster
Reopen if needed
