### ISSUE TITLE
ParseError on localhost

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#515]
On localhost, I have a ParseError for variable type declaration

It doesn't like the type declaration (removing the variable type solves the issue)
I though it was because of the php version, but php -v says 7.4.6
I'm not sure what causes that

<img width="1680" alt="Capture d’écran 2020-06-15 à 14 31 52" src="https://user-images.githubusercontent.com/2345926/84657759-15045180-af15-11ea-8e85-21d7172699bf.png">

SelfRules.php line 13 is :
   private array $permissions;

Thanks,

**Comment by SamMousa** [comment]
This looks like an issue with the php version of your docker containers, try rebuilding the images.

**Comment by jeremiehelme** [comment]
Thanks, I tried 
`docker-compose build --no-cache`

After restarting docker, I used, as usual
`docker-compose up serve`

Now I have
<img width="1680" alt="Capture d’écran 2020-06-15 à 16 16 54" src="https://user-images.githubusercontent.com/2345926/84668549-11c49200-af24-11ea-96b8-d53f5bafcbd8.png">

**Comment by SamMousa** [comment]
Did you remove your containers? Please check the docker-compose docs

**Comment by jeremiehelme** [comment]
Sorry, I wish it would solve the issue
I tried these 

docker-compose down // to stop the containers
docker system prune -a //to remove the containers
docker-compose build --no-cache // to build the containers
docker-compose up serve

But still the same issue

**Comment by SamMousa** [comment]
The 2nd error; it says it is missing a file; that is not the same error.
What did you do with that file? Did you remove it?

**Comment by jeremiehelme** [comment]
Thank you for your help !

I haven't removed it, the issue appeared after rebuilding the containers

From what I understand, it is used for limesurveySSo ?
Creating a blank file solves the issue for now

Thanks,
