### ISSUE TITLE
Response Picker > configurable columns for list of responses

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#516]
<img width="1680" alt="Capture d’écran 2020-06-16 à 14 49 40" src="https://user-images.githubusercontent.com/2345926/84776536-b4dae180-afe0-11ea-8225-b53be76ee3df.png">

In the new response picker we now display only the last responses
When you click it, it opens the list of all responses

The column for the last responses are configurable
Is there a way to configure the columns for the list of responses as well ?

We were thinking adding a prefix to the name of the column, that way I can filter them

@SamMousa What's your view on this ? there is no other easy / better way right ?
@luna404 is it ok to add a prefix to the column name ?

Thanks

**Comment by SamMousa** [comment]
>  What's your view on this ? there is no other easy / better way right ?

Go ahead and do what you think is best.

**Comment by jeremiehelme** [comment]
Ok, I'll try that way then, thanks
