### ISSUE TITLE
Manual / batch sync no longer includes incomplete responses

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#521]
Manual & batch syncs should not sync responses without submitdate.
This brings it in line with the live sync feature.

- [x] Disable sync without submitdate on staging (Ready for testing)
- [x] Mark all responses in LS as completed by setting submitdate to date of update
- [ ] Deploy this change to prod

Please confirm that as expected, any update of a completed record will update the response immediately in the platform only when going through the final submit page.

**Comment by SamMousa** [comment]
> Please confirm that as expected, any update of a completed record will update the response immediately in the platform only when going through the final submit page.

@JeffDotingco @luna404 could one of you confirm this? As far as I can tell that works correctly. 

- [ ] New / updated record without submitdate is not synced after closing the survey without submitting.
- [ ] New / updated record is not synced when using workspace refresh
- [ ] After completing the record is updated immediately

**Comment by JeffDotingco** [comment]
@SamMousa This is also working in PROD?

**Comment by SamMousa** [comment]
Test it on staging for now.

**Comment by JeffDotingco** [comment]
This is just a preliminary testing:

1. Downloaded the dataset from STAGING composed of 7,294 records
2. Also downloaded the dataset from LS with INCOMPLETE RESPONSES (n=34)
3. Merged these files in Stata using external_ID. The 34 incomplete responses should not be matched (_m==3). However, 24 incomplete responses from LS have a match in Stata, please below:

<img width="1295" alt="Screen Shot 2020-06-18 at 8 15 11 PM" src="https://user-images.githubusercontent.com/50957748/85018922-8c014a80-b1a0-11ea-9abe-c0256ead1571.png">

Still for further testing.

**Comment by luna404** [comment]
@JeffDotingco do the 10 incomplete records form LS have a date of update?

**Comment by JeffDotingco** [comment]
Three records have dates of update (I just renamed update to update_old for merging purposes):
<img width="522" alt="Screen Shot 2020-06-19 at 7 07 38 PM" src="https://user-images.githubusercontent.com/50957748/85126513-37bd9f80-b260-11ea-878b-e917f3840bb0.png">

**Comment by luna404** [comment]
@JeffDotingco sorry I think I misread your previous post. Would I assume the reason for you finding the 24 records is that we manually synced some of the workspaces which would have included records with no submitted date.

The fact that the last two records where created 2 days ago sounds like the new way of not syncing these records is working. 

>  New / updated record is not synced when using workspace refresh
@SamMousa I assume you only mean records with no submitted date. All others should be refreshed when manually syncing a workspace

**Comment by JeffDotingco** [comment]
another testing was done by merging dataset from STAGING and incomplete responses from LS, same procedure made before:

- 13 incomplete responses from LS have no records in the downloaded dataset from STAGING (_m==2)

- 21 incomplete responses from LS have records in the downloaded dataset from STAGING (_m==3)

<img width="579" alt="Screen Shot 2020-06-23 at 6 02 47 PM" src="https://user-images.githubusercontent.com/50957748/85390913-0ef91b00-b57c-11ea-8e9c-6bc5494e5451.png">

**Comment by SamMousa** [comment]
Please just tell me the conclusion, the 3 points I mentioned above, have you verified them? Yes or no question

**Comment by JeffDotingco** [comment]
> Please just tell me the conclusion, the 3 points I mentioned above, have you verified them? Yes or no question

doing the testing you suggested in the meeting now.:)

**Comment by JeffDotingco** [comment]
I added a new HF record for HeRAMS YEM (ID: 118986,  HF Code: 2557Yb, No SUBMIT DATE, Incomplete). 

- It appears in the response table for workspace Raymah / Al Jabin and LS as well as incomplete response

- BUT it does not appear in the validation and downloaded dataset (even after WS refresh)

- BUT after you completed that record and submitting it in STAGING, it appears in the validation and exported dataset (even without refreshing the WS)

- So yes, working in STAGING in terms of:
1. New / updated record without submitdate is not synced after closing the survey without submitting.
2. New / updated record is not synced when using workspace refresh
3. After completing the record is updated immediately

**Comment by SamMousa** [comment]
Okay, I have now updated all limesurvey records so that they have a submitdate. Running full sync on staging now.

**Comment by JeffDotingco** [comment]
Will be deleting records used for testing also in LS

**Comment by luna404** [comment]
It seems to have solved the sync issue. I haven't heard of any issues since this has been implemented.
