### ISSUE TITLE
New response picker shows wrong date of update

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#526]
There seems to be an issue with the date of update. I created a new response during the training today with date of update of today. In the response picker both records now show the date of today as update, but if you check in LS the date of update of the first resopnse should be 2019-12-03.

https://ls.herams.org/survey/index/sid/996483/token/OyfIw74xCu6gpQk/newtest/Y?test=ResponsePicker
![image](https://user-images.githubusercontent.com/18245059/85700381-9cec1780-b6dc-11ea-81a6-f151500f4ad4.png)

https://ls.herams.org/admin/responses/sa/browse/surveyid/996483/browselang/fr
![image](https://user-images.githubusercontent.com/18245059/85700771-fe13eb00-b6dc-11ea-8532-534e26e5e408.png)

Same issue for other countries 
https://ls.herams.org/survey/index/sid/618734/token/7iZdKx3RiQjzlMb1/newtest/Y?test=ResponsePicker

**Comment by jeremiehelme** [comment]
Thanks @luna404, it should be ok now

**Comment by jeremiehelme** [comment]
https://ls.herams.org/survey/index/sid/996483/token/OyfIw74xCu6gpQk/newtest/Y?test=ResponsePicker

if you look a the first HF, there is two responses (17472 and 17358)

<img width="1408" alt="Capture d’écran 2020-06-25 à 16 28 05" src="https://user-images.githubusercontent.com/2345926/85739265-ef3f2f80-b700-11ea-8851-6a5fb4c3cd6a.png">

I thought that the first one was the most recent, as the response ID is higher, but it seems it's not always the case.

I have several dates, which one is the correct one ?

<img width="236" alt="Capture d’écran 2020-06-25 à 16 24 47" src="https://user-images.githubusercontent.com/2345926/85740312-d08d6880-b701-11ea-98e6-423f25d3f9c6.png">

**Comment by jeremiehelme** [comment]
Ok, it is fixed for the other columns too
