### ISSUE TITLE
Display applied filters on dashbaords

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#529]
@jeremiehelme I think this is part of the mock-ups and you might already be working on this, but it came up again during the training with Mali and BF.

There is currently no options for users to know if any filters are applied to the dashboard. As we now display applied filters in the export, they would like to also see them on the dashboard or have an option where they could view applied filter without having to go to the filters options and search for applied filters.

**Comment by jeremiehelme** [comment]
this is done for pdf export but requires some improvements (the list can be very long). it can be done relatively easily for dashboard filters

**Comment by luna404** [comment]
As discussed yesterday, depending on the number of filters applied, we might have the same issue as on the pdf, whereby the filter text takes away too much space. I would suggest to initially only display the number of filters applied (as shown in the mock-up). In a second step it would be nice to review individual filters applied, but ideally don't display them by default (e.g. place them in a pop-up that user can click on to review applied filters).

**Comment by jeremiehelme** [comment]
Display a list of filters selected on top of the filter form
Add a remove filters button

**Comment by jeremiehelme** [comment]
Displayed the number of filters selected in the filter button and added the list on top of the filter form
Added a remove all filters button next to the list, and centered the action button at the bottom to make them more visible

<img width="1680" alt="Capture d’écran 2020-07-27 à 13 33 37" src="https://user-images.githubusercontent.com/2345926/88537728-645a9900-d00e-11ea-89aa-7feb3d9c7640.png">

<img width="1680" alt="Capture d’écran 2020-07-27 à 13 36 26" src="https://user-images.githubusercontent.com/2345926/88537736-67558980-d00e-11ea-87d8-7f836352b309.png">

**Comment by luna404** [comment]
Looks great, it's much more readable like with the group headers.

- There is a lot of white space on the right, could you make the pop-up a less wide so users still see the dashboard in the background?
- If you use the search box and hit enter it closes the filter display. Is this on purpose? I think a lot of user might not realize it filters dynamically and hit enter by accident.

**Comment by luna404** [comment]
I like the option you added to remove all filters. Would it be possible to extend this so users could either delete all or just select ones?

In the example below, would it be possible to allow user to remove the filter on the Territory only?

![image](https://user-images.githubusercontent.com/18245059/88639551-32ecd680-d0bd-11ea-9308-7f99852a1fd9.png)
