### ISSUE TITLE
Last page of questionnaire not saved

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#530]
There is an issue with the saving of responses. It seems that if you create or edit a record it always fails to save the last page a user edited. I tried multiple times and every time it fails on the last page of the questionnaire I edited.

**Comment by SamMousa** [comment]
Is this true for every survey?

**Comment by luna404** [comment]
I have only tested it for one so far 
https://ls.herams.org/admin/survey/sa/editsurveysettings/surveyid/996483

**Comment by SamMousa** [comment]
I can't reproduce this.
The way I tested it: 
- Open 1 response in the LS backend:  https://ls.herams.org/admin/responses?sa=view&surveyid=996483&id=15306
- Open that same response via the response picker (no link here because these are not secured)
- Change `Nom de la localité` from empty to `test`.
- Click on any other page on the left
- Refresh the backend, see that the data has been updated
- Change `Nom de la localité` from `test` to empty.
- Click on any other page on the left
- Refresh the backend, see that the data has been updated

**Comment by luna404** [comment]
Here's an example,

- I create a new record in workspace https://herams.org/workspace/9621/limesurvey
- Complete the first few pages until functionality and set functionality to not functioning which will end the questionnaire.
- If I advance to the validate page I get an error that it could not save my record

![image](https://user-images.githubusercontent.com/18245059/85723322-68d02100-b6f3-11ea-8afb-9d09a9322968.png)


In LS the record also has no information for the two questions in the functionality group
https://ls.herams.org/admin/dataentry?sa=editdata&subaction=edit&surveyid=996483&id=15333

**Comment by SamMousa** [comment]
I'm not convinced there is an actual error in LS here.
Please reproduce it in an English survey and test it outside of the platform, that way we can exclude some things if it turns out to be an issue.

**Comment by luna404** [comment]
It seems to only be an issue with this particular survey. I can't reproduce it in any other survey, but the issue for Mali remains if you create a new record outside of the platform


![image](https://user-images.githubusercontent.com/18245059/85726578-8488f680-b6f6-11ea-9f1d-3c9ce2b52675.png)

**Comment by SamMousa** [comment]
Could be that the number of fields is hitting a limit; that tends to cause weird issues like this. Also on the image you just posted, there could be an error at the end of the SQL statement (but that is not in your screenshot).

**Comment by luna404** [comment]
Here's the entire error message

Update failed:

UPDATE {{survey_996483}} SET `submitdate` = '2020-06-25 12:49:21', `startlanguage` = 'fr', `token` = '123', `startdate` = '2020-06-25 12:48:27', `datestamp` = '2020-06-25 12:48:58', `996483X441X6579` = '2020-06-25 00:00:00', `996483X441X6470` = '2892PL', `996483X544X7917` = 'M0901', `996483X544X7919` = 'test', `996483X544X7918` = '', `996483X544X7918other` = '', `996483X544X7925` = 'test', `996483X544X7920SQ001` = '', `996483X544X7920SQ002` = '', `996483X544X7923` = '0.0000000000', `996483X544X7924` = '', `996483X544X7940` = '', `996483X443X6568` = 'test', `996483X443X6569` = 'test', `996483X443X6570` = 'A1', `996483X443X6570other` = '', `996483X443X6571` = 'A1', `996483X443X6572` = 'A2', `996483X443X6574` = '', `996483X443X7928SQ001` = '', `996483X443X7928SQ002` = '', `996483X443X8612` = NULL, `996483X443X6575` = 'A1', `996483X443X6575other` = '', `996483X443X6576` = '', `996483X443X6593` = '', `996483X443X6577` = '', `996483X443X7123` = '', `996483X445X6583` = 'A1', `996483X445X65841` = '', `996483X445X65842` = '', `996483X445X65843` = '', `996483X445X8613` = 'A1', `996483X445X86141` = '', `996483X445X86142` = '', `996483X445X86143` = '', `996483X446X6585` = 'A3', `996483X446X65861` = 'A1', `996483X446X65862` = '', `996483X446X65863` = '', `996483X444X6580` = '', `996483X444X65811` = '', `996483X444X65812` = '', `996483X444X65813` = '', `996483X447X6587` = '', `996483X447X6587other` = '', `996483X447X6588` = '', `996483X447X6589` = NULL, `996483X447X6590SQ001` = '', `996483X447X6590SQ002` = '', `996483X447X6590SQ003` = '', `996483X447X6590SQ004` = '', `996483X447X6590SQ005` = '', `996483X447X6590SQ006` = '', `996483X447X6590SQ007` = '', `996483X447X6590SQ008` = '', `996483X447X6590SQ009` = '', `996483X447X6590SQ010` = '', `996483X447X6591SQ001_SQ001` = '0', `996483X447X6591SQ001_SQ002` = '0', `996483X447X6591SQ001_SQ003` = '0', `996483X447X6591SQ001_SQ007` = '0', `996483X447X6591SQ001_SQ004` = '0', `996483X447X6591SQ001_SQ005` = '0', `996483X447X6591SQ002_SQ001` = '0', `996483X447X6591SQ002_SQ002` = '0', `996483X447X6591SQ002_SQ003` = '0', `996483X447X6591SQ002_SQ007` = '0', `996483X447X6591SQ002_SQ004` = '0', `996483X447X6591SQ002_SQ005` = '0', `996483X447X6591SQ003_SQ001` = '0', `996483X447X6591SQ003_SQ002` = '0', `996483X447X6591SQ003_SQ003` = '0', `996483X447X6591SQ003_SQ007` = '0', `996483X447X6591SQ003_SQ004` = '0', `996483X447X6591SQ003_SQ005` = '0', `996483X447X6591SQ004_SQ001` = '0', `996483X447X6591SQ004_SQ002` = '0', `996483X447X6591SQ004_SQ003` = '0', `996483X447X6591SQ004_SQ007` = '0', `996483X447X6591SQ004_SQ004` = '0', `996483X447X6591SQ004_SQ005` = '0', `996483X447X6591SQ005_SQ001` = '0', `996483X447X6591SQ005_SQ002` = '0', `996483X447X6591SQ005_SQ003` = '0', `996483X447X6591SQ005_SQ007` = '0', `996483X447X6591SQ005_SQ004` = '0', `996483X447X6591SQ005_SQ005` = '0', `996483X447X6591SQ006_SQ001` = '0', `996483X447X6591SQ006_SQ002` = '0', `996483X447X6591SQ006_SQ003` = '0', `996483X447X6591SQ006_SQ007` = '0', `996483X447X6591SQ006_SQ004` = '0', `996483X447X6591SQ006_SQ005` = '0', `996483X447X6591SQ007_SQ001` = '0', `996483X447X6591SQ007_SQ002` = '0', `996483X447X6591SQ007_SQ003` = '0', `996483X447X6591SQ007_SQ007` = '0', `996483X447X6591SQ007_SQ004` = '0', `996483X447X6591SQ007_SQ005` = '0', `996483X447X6591SQ008_SQ001` = '0', `996483X447X6591SQ008_SQ002` = '0', `996483X447X6591SQ008_SQ003` = '0', `996483X447X6591SQ008_SQ007` = '0', `996483X447X6591SQ008_SQ004` = '0', `996483X447X6591SQ008_SQ005` = '0', `996483X447X6591SQ009_SQ001` = '0', `996483X447X6591SQ009_SQ002` = '0', `996483X447X6591SQ009_SQ003` = '0', `996483X447X6591SQ009_SQ007` = '0', `996483X447X6591SQ009_SQ004` = '0', `996483X447X6591SQ009_SQ005` = '0', `996483X447X6591SQ010_SQ001` = '0', `996483X447X6591SQ010_SQ002` = '0', `996483X447X6591SQ010_SQ003` = '0', `996483X447X6591SQ010_SQ007` = '0', `996483X447X6591SQ010_SQ004` = '0', `996483X447X6591SQ010_SQ005` = '0', `996483X630X9222` = NULL, `996483X630X9223` = '', `996483X630X92241` = '', `996483X630X92242` = '', `996483X630X92243` = '', `996483X630X9225` = '', `996483X630X92261` = '', `996483X630X92262` = '', `996483X630X92263` = '', `996483X630X92264` = '', `996483X630X92265` = '', `996483X630X92266` = '', `996483X630X9227` = '', `996483X630X9228` = '', `996483X630X92291` = '', `996483X630X92292` = '', `996483X630X92293` = '', `996483X630X9230` = '', `996483X630X92311` = '', `996483X630X92312` = '', `996483X630X92313` = '', `996483X630X9232` = '', `996483X630X92331` = '', `996483X630X92332` = '', `996483X630X92333` = '', `996483X630X9234` = '', `996483X630X92351` = '', `996483X630X92352` = '', `996483X630X92353` = '', `996483X630X9236` = '', `996483X630X92371` = '', `996483X630X92372` = '', `996483X630X92373` = '', `996483X440X7934` = '', `996483X440X7935` = '', `996483X440X6484` = '', `996483X440X6628` = '', `996483X440X6582` = '', `996483X440X6626` = '', `996483X637X9350` = '', `996483X637X93511` = '', `996483X637X93512` = '', `996483X637X93513` = '', `996483X637X9352` = '', `996483X637X93531` = '', `996483X637X93532` = '', `996483X637X93533` = '', `996483X637X9354` = '', `996483X637X93551` = '', `996483X637X93552` = '', `996483X637X93553` = '', `996483X637X9356` = '', `996483X637X93571` = '', `996483X637X93572` = '', `996483X637X93573` = '', `996483X637X9358` = '', `996483X637X93591` = '', `996483X637X93592` = '', `996483X637X93593` = '', `996483X637X9360` = '', `996483X637X93611` = '', `996483X637X93612` = '', `996483X637X93613` = '', `996483X637X9362` = '', `996483X637X93631` = '', `996483X637X93632` = '', `996483X637X93633` = '', `996483X637X9364` = '', `996483X637X93651` = '', `996483X637X93652` = '', `996483X637X93653` = '', `996483X637X9366` = '', `996483X637X93671` = '', `996483X637X93672` = '', `996483X637X93673` = '', `996483X637X9368` = '', `996483X637X93691` = '', `996483X637X93692` = '', `996483X637X93693` = '', `996483X637X9370` = '', `996483X637X93711` = '', `996483X637X93712` = '', `996483X637X93713` = '', `996483X637X9372` = '', `996483X637X93731` = '', `996483X637X93732` = '', `996483X637X93733` = '', `996483X637X9564` = '', `996483X637X95651` = '', `996483X637X95652` = '', `996483X637X95653` = '', `996483X637X9374` = '', `996483X637X93751` = '', `996483X637X93752` = '', `996483X637X93753` = '', `996483X637X9376` = '', `996483X637X93771` = '', `996483X637X93772` = '', `996483X637X93773` = '', `996483X637X9378` = '', `996483X637X93791` = '', `996483X637X93792` = '', `996483X637X93793` = '', `996483X637X9380` = '', `996483X637X93811` = '', `996483X637X93812` = '', `996483X637X93813` = '', `996483X637X9382` = '', `996483X637X93831` = '', `996483X637X93832` = '', `996483X637X93833` = '', `996483X637X9384` = '', `996483X637X93851` = '', `996483X637X93852` = '', `996483X637X93853` = '', `996483X637X9386` = '', `996483X637X93871` = '', `996483X637X93872` = '', `996483X637X93873` = '', `996483X637X9388` = '', `996483X637X93891` = '', `996483X637X93892` = '', `996483X637X93893` = '', `996483X637X9390` = '', `996483X637X93911` = '', `996483X637X93912` = '', `996483X637X93913` = '', `996483X637X9392` = '', `996483X637X93931` = '', `996483X637X93932` = '', `996483X637X93933` = '', `996483X637X9394` = '', `996483X637X93951` = '', `996483X637X93952` = '', `996483X637X93953` = '', `996483X637X9396` = '', `996483X637X93971` = '', `996483X637X93972` = '', `996483X637X93973` = '', `996483X637X9398` = '', `996483X637X93991` = '', `996483X637X93992` = '', `996483X637X93993` = '', `996483X631X9238` = '', `996483X631X92391` = '', `996483X631X92392` = '', `996483X631X92393` = '', `996483X631X9240` = '', `996483X631X92411` = '', `996483X631X92412` = '', `996483X631X92413` = '', `996483X631X9242` = '', `996483X631X92431` = '', `996483X631X92432` = '', `996483X631X92433` = '', `996483X631X9244` = '', `996483X631X92451` = '', `996483X631X92452` = '', `996483X631X92453` = '', `996483X631X9246` = '', `996483X631X92471` = '', `996483X631X92472` = '', `996483X631X92473` = '', `996483X631X9248` = '', `996483X631X92491` = '', `996483X631X92492` = '', `996483X631X92493` = '', `996483X631X9250` = '', `996483X631X92511` = '', `996483X631X92512` = '', `996483X631X92513` = '', `996483X631X9252` = '', `996483X631X92531` = '', `996483X631X92532` = '', `996483X631X92533` = '', `996483X631X9254` = '', `996483X631X92551` = '', `996483X631X92552` = '', `996483X631X92553` = '', `996483X631X9256` = '', `996483X631X92571` = '', `996483X631X92572` = '', `996483X631X92573` = '', `996483X631X9258` = '', `996483X631X92591` = '', `996483X631X92592` = '', `996483X631X92593` = '', `996483X631X9260` = '', `996483X631X92611` = '', `996483X631X92612` = '', `996483X631X92613` = '', `996483X632X9262` = '', `996483X632X92631` = '', `996483X632X92632` = '', `996483X632X92633` = '', `996483X632X9264` = '', `996483X632X92651` = '', `996483X632X92652` = '', `996483X632X92653` = '', `996483X632X9266` = '', `996483X632X92671` = '', `996483X632X92672` = '', `996483X632X92673` = '', `996483X632X9268` = '', `996483X632X92691` = '', `996483X632X92692` = '', `996483X632X92693` = '', `996483X632X9270` = '', `996483X632X92711` = '', `996483X632X92712` = '', `996483X632X92713` = '', `996483X632X9272` = '', `996483X632X92731` = '', `996483X632X92732` = '', `996483X632X92733` = '', `996483X632X9274` = '', `996483X632X92751` = '', `996483X632X92752` = '', `996483X632X92753` = '', `996483X632X9276` = '', `996483X632X92771` = '', `996483X632X92772` = '', `996483X632X92773` = '', `996483X632X9278` = '', `996483X632X92791` = '', `996483X632X92792` = '', `996483X632X92793` = '', `996483X632X9280` = '', `996483X632X92811` = '', `996483X632X92812` = '', `996483X632X92813` = '', `996483X632X9282` = '', `996483X632X92831` = '', `996483X632X92832` = '', `996483X632X92833` = '', `996483X633X9284` = '', `996483X633X92851` = '', `996483X633X92852` = '', `996483X633X92853` = '', `996483X633X9286` = '', `996483X633X92871` = '', `996483X633X92872` = '', `996483X633X92873` = '', `996483X633X9288` = '', `996483X633X92891` = '', `996483X633X92892` = '', `996483X633X92893` = '', `996483X633X9290` = '', `996483X633X92911` = '', `996483X633X92912` = '', `996483X633X92913` = '', `996483X633X9292` = '', `996483X633X92931` = '', `996483X633X92932` = '', `996483X633X92933` = '', `996483X633X9294` = '', `996483X633X92951` = '', `996483X633X92952` = '', `996483X633X92953` = '', `996483X633X9296` = '', `996483X633X92971` = '', `996483X633X92972` = '', `996483X633X92973` = '', `996483X633X9300` = '', `996483X633X93011` = '', `996483X633X93012` = '', `996483X633X93013` = '', `996483X634X9302` = '', `996483X634X93031` = '', `996483X634X93032` = '', `996483X634X93033` = '', `996483X634X9304` = '', `996483X634X93051` = '', `996483X634X93052` = '', `996483X634X93053` = '', `996483X634X9306` = '', `996483X634X93071` = '', `996483X634X93072` = '', `996483X634X93073` = '', `996483X634X9308` = '', `996483X634X93091` = '', `996483X634X93092` = '', `996483X634X93093` = '', `996483X634X9310` = '', `996483X634X93111` = '', `996483X634X93112` = '', `996483X634X93113` = '', `996483X634X9312` = '', `996483X634X93131` = '', `996483X634X93132` = '', `996483X634X93133` = '', `996483X634X9314` = '', `996483X634X93151` = '', `996483X634X93152` = '', `996483X634X93153` = '', `996483X634X9316` = '', `996483X634X93171` = '', `996483X634X93172` = '', `996483X634X93173` = '', `996483X635X9318` = '', `996483X635X93191` = '', `996483X635X93192` = '', `996483X635X93193` = '', `996483X635X9320` = '', `996483X635X93211` = '', `996483X635X93212` = '', `996483X635X93213` = '', `996483X635X9322` = '', `996483X635X93231` = '', `996483X635X93232` = '', `996483X635X93233` = '', `996483X636X9324` = '', `996483X636X93251` = '', `996483X636X93252` = '', `996483X636X93253` = '', `996483X636X9326` = '', `996483X636X93271` = '', `996483X636X93272` = '', `996483X636X93273` = '', `996483X636X9328` = '', `996483X636X93291` = '', `996483X636X93292` = '', `996483X636X93293` = '', `996483X636X9330` = '', `996483X636X93311` = '', `996483X636X93312` = '', `996483X636X93313` = '', `996483X636X9332` = '', `996483X636X93331` = '', `996483X636X93332` = '', `996483X636X93333` = '', `996483X636X9334` = '', `996483X636X93351` = '', `996483X636X93352` = '', `996483X636X93353` = '', `996483X636X9336` = '', `996483X636X93371` = '', `996483X636X93372` = '', `996483X636X93373` = '', `996483X636X9338` = '', `996483X636X93391` = '', `996483X636X93392` = '', `996483X636X93393` = '', `996483X636X9340` = '', `996483X636X93411` = '', `996483X636X93412` = '', `996483X636X93413` = '', `996483X636X9342` = '', `996483X636X93431` = '', `996483X636X93432` = '', `996483X636X93433` = '', `996483X636X9344` = '', `996483X636X93451` = '', `996483X636X93452` = '', `996483X636X93453` = '', `996483X636X9346` = '', `996483X636X93471` = '', `996483X636X93472` = '', `996483X636X93473` = '', `996483X636X9348` = '', `996483X636X93491` = '', `996483X636X93492` = '', `996483X636X93493` = '', `996483X449X6622` = '' WHERE id=15333

**Comment by SamMousa** [comment]
It is trying to update a column that doesn't exist; you may try to deactivate & reactive the survey. This can also be caused by hitting the column limit.

**Comment by luna404** [comment]
I did what you suggested and deactivated and reactivated the survey. This seems to have resolved the issue. - Thanks
