### ISSUE TITLE
Response picker: text display

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#532]
@jeremiehelme would it be possible to make the following changes to the way the reponse picker is displaying results?

1.  Text (header and actual data) should be truncated after ( and : 

Example: Instead of showing the entire response for builduing condition, it should only show "substantially damaged"/"Not damaged". Same logic should be used for headers.
https://herams.org/workspace/6895/limesurvey
![image](https://user-images.githubusercontent.com/18245059/86018429-a3a0c480-ba25-11ea-8024-68021895aae7.png)

2. Headers and text should always use the default language of the survey. Ideally this would also be applied to response id and update. We can always add these fields if that would make it easier to implement 

Example : For surveys who do not have English as default, there is currently a mix of English and French/Arabic labels.
https://herams.org/workspace/7063/limesurvey
![image](https://user-images.githubusercontent.com/18245059/86018265-63414680-ba25-11ea-85e3-d78243655795.png)

3. Change `not text found` to empty string.

Example: If a question has not been answered it shows as  `not text found`. I don't find this the most intuitive message and would prefer we we could just leave the field black or write `no data`.
https://herams.org/workspace/509/limesurvey
![image](https://user-images.githubusercontent.com/18245059/86019162-8ddfcf00-ba26-11ea-8b21-a3482a877845.png)

**Comment by jeremiehelme** [comment]
Thanks,

Ok for 1 and 3
I still have to figure out how to translate headers and text

**Comment by jeremiehelme** [comment]
About the second point, here is what we have now 
The headers of the columns are now translated, except for the response id column

<img width="1680" alt="Capture d’écran 2020-07-01 à 10 37 55" src="https://user-images.githubusercontent.com/2345926/86222795-fe056680-bb86-11ea-939c-0c6fcc4afa3a.png">

@luna404 What is the code for the response id ? is it qid ?
 I'd like to add it as a column to test

Thanks

**Comment by luna404** [comment]
There seems to still be a mix of languages in your screenshot. Why is building condition in Arabic? The base language for Yemen is English so all question headers should be in English. I looked at another project, there is also still a mix of languages (https://herams.org/workspace/7104/limesurvey)

I think its just id. The field automatically created and translated by LimeSurvey

**Comment by jeremiehelme** [comment]
Just to understand a bit better where the error is  

Here is the list of columns I receive
Array ( [0] => Update [1] => text )
Array ( [0] => Month [1] => select [2] => Month of reporting )
Array ( [0] => UOID [1] => text [2] => HF Code )
Array ( [0] => MoSD2 [1] => text [2] => Name )
Array ( [0] => MoSD2a [1] => text [2] => Name (Arabic) )
Array ( [0] => MoSD3 [1] => select [2] => Type )
Array ( [0] => GEO03 [1] => text [2] => Governorate )
Array ( [0] => GEO06 [1] => text [2] => District )
**Array ( [0] => CONDB [1] => text )
Array ( [0] => HFFUNCT [1] => text )**

The last two columns don't have a header specified
In this case, we use the question as a header, and the question is in Arabic for CONDB

I reverted the response picker to the last version, it seems that it was already the case before 
https://ls.herams.org/survey/index/sid/618734/token/7iZdKx3RiQjzlMb1/newtest/Y?test=ResponsePicker

I'm not sure what to do next ? We can call if needed

**Comment by luna404** [comment]
The survey for Yemen (like most others) is  bilingual, whereby the base language is English. Both CONDB and HFFUNCT have a question text available in English and Arabic. Please have a look at the questionnaire if this is still unclear. If you don't have access to the survey please ask @SamuelPetragallo to grant you access or look at another survey (e.g. Burkina Faso, Mali). It's the same principle there just with different languages.

Ideally the logic should be as follows:
1. If we specify a text after the filed type it should display this regardless of the language (e.g. MoSD2a : text : Name (Arabic))
2. For any field where we don't specify the field name, it should take the question label from the base language and truncate the label to only show the text before : or )
3. Ideally (and please don't waste to much time on this point), the language selected by the users should mimic the one used in the response picker. So if a users selects Arabic or has default language Arabic, the response picker should also display Arabic field names if available. In case this is not possible (or takes to much development) would it possible to have the same language switch available on the response picker than on the questionnaire itself?

**Comment by jeremiehelme** [comment]
I think the last point to clarify is the language of the field name. I need to understand why I receive one language instead of the base one

**Comment by jeremiehelme** [comment]
So, I can query a question with a language parameter
What is strange is that without that parameter, it doesn't return the question in the base language.

I'm looking for a way to get the survey base language. 
For now, I get the start language of the first question and display the fields in that language

**Comment by jeremiehelme** [comment]
Ok, I found how to get the available languages for the survey
So now, I display the survey in the user language if available, or in the survey default language

A few examples
https://ls.herams.org/survey/index/sid/996483/token/OyfIw74xCu6gpQk/newtest/Y?test=ResponsePicker
https://ls.herams.org/survey/index/sid/618734/token/7iZdKx3RiQjzlMb1/newtest/Y/lang/fr?test=ResponsePicker
https://ls.herams.org/survey/index/sid/391149/token/AfHsQ82ri7Pedn3/newtest/Y?test=ResponsePicker

For the interface, I translated the text in French.
Here are the translations I would need in other languages 
- No text found for
- Add a response
- Response id _(not needed if column exists in the survey)_
- Date of update _(not needed if column exists in the survey)_

**Comment by luna404** [comment]
Great work on figuring the issue out!

This might be me not doing it right but I thought if you change the language in the url it should now adjust the language dispalyed. When I change the first link to English, it still shows in French. Is this as expected?  

https://ls.herams.org/survey/index/sid/996483/token/OyfIw74xCu6gpQk/newtest/Y/lang/en?test=ResponsePicker
![image](https://user-images.githubusercontent.com/18245059/87929447-ba679380-ca86-11ea-93aa-dcddc2491f34.png)

I'll ask Fatma for the two Arabic translations.

**Comment by luna404** [comment]
Just a thought on the translations, would ti be possible to add them to the other text strings from the platform and translate them through weblate. Would be easier to manage should we ever add another language.

**Comment by jeremiehelme** [comment]
Ok, I'll take the language from the url first if specified, and the browser language otherwise

**Comment by jeremiehelme** [comment]
Here it is, I've let the debug information to explain the process :

https://ls.herams.org/survey/index/sid/618734/token/7iZdKx3RiQjzlMb1/newtest/Y?test=ResponsePicker
https://ls.herams.org/survey/index/sid/618734/token/7iZdKx3RiQjzlMb1/newtest/Y/lang/fr?test=ResponsePicker
https://ls.herams.org/survey/index/sid/618734/token/7iZdKx3RiQjzlMb1/newtest/Y/lang/en?test=ResponsePicker

**Comment by luna404** [comment]
Given that you have the list of available languages, would it be possible to mimic the behavior of the survey itself and add a drop-down list where user can change the display language themselves?

**Comment by jeremiehelme** [comment]
Yes sure, it's added
I still have to check how it behave within an iframe

**Comment by jeremiehelme** [comment]
Translate the content as well (test with Arabic)

**Comment by jeremiehelme** [comment]
Ok found it. You can ask the model to return the answer in a given language.
Now that I'm sure that we use a language that is supported by the survey, I can ask for the answer in the correct language

https://ls.herams.org/618734?token=7iZdKx3RiQjzlMb1&newtest=Y&lang=en&test=ResponsePicker
https://ls.herams.org/618734?token=7iZdKx3RiQjzlMb1&newtest=Y&lang=ar&test=ResponsePicker

**Comment by jeremiehelme** [comment]
Just added the lang parameter to the URL when accessing the response picker from the platform. That way it shows it in the user language if available

**Comment by luna404** [comment]
You only seem to be considering two language option per survey. There are surveys with more than two language options (even though we don't have the questionnaires fully translated)

If you look at Mali, the language drop-down shows fr and combines ar and en, resulting in an interesting display if you select "ar en".
https://ls.herams.org/996483?token=OyfIw74xCu6gpQk&newtest=Y&lang=fr

For the missing Arabic translations,
 "Response ID" (رقم الاستجابة) should be available through LS (https://ls.herams.org/admin/responses/sa/browse/surveyid/618734/browselang/ar). The others are with Fatma for confirmations

**Comment by jeremiehelme** [comment]
Ah, nice catch, thanks, I though it would be an array of language code, not a concatened string.
It's fixed
