### ISSUE TITLE
LS transition / list of LS functions beyond Form Building

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#537]
To start a list of the functions we are using in LS that we may lose when transitioning:

1. Export forms in printable/pdf format

**Comment by luna404** [comment]
1. Support multilingual questionnaires
2. Field types used in the SDM need to be supported (text, numeric, GPS?, single choice, multiple choice, ranking, array, calculated questions (equations))
3. Support grouping / pagination of questionnaire
4. Data validation: It must be possible to use basic validation rules including displaying custom messages to users.
5. Depended drop-down list. (This one of the major disadvantages of LS)
6. Advanced survey logic: It must be possible to skip questions based on user response to previous questions.
7. Print friendly version: Ideally, it should be possible to export questionnaire for different languages and formatted so it can be used for offline data collection. (I like how this is done in Enketo https://enke.to/x/fatal)
8. Pre-populating form: Similar to LS it should be possible to pre-populated certain questions
9. Offline data collection
10. Mobile friendly version: It should be possible to enter data on tablets and mobile phones
11. Form builder: It should be possible to rapidly create a new form without any programming knowledge. Support of xlsFroms would be a plus. At the very least, it must be possible to copy/import a questionnaire from a template.
