### ISSUE TITLE
Form fields layout

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#543]
For the settings, is there a way you can make the widths more dynamic. There is a lot of empty space on my screen but it still breaks the category labels on two rows.

![87038925-b4ec8c80-c1ee-11ea-9dd9-85bf5ecdc87c](https://user-images.githubusercontent.com/2345926/87130531-5d542c80-c293-11ea-904e-c5f229fdd027.png)

Feel free to make radical changes to this layout. For example some of the input fields (e.g. width and height) could be displayed in the same row. Similarly, the width of the color bar could be shortened if this helps avoiding the being spread across multiple columns, etc.

**Comment by jeremiehelme** [comment]
I adapted the size and positioning of the different elements, and changed the action button colors to better represent what they do
<img width="1680" alt="Capture d’écran 2020-07-27 à 13 31 17" src="https://user-images.githubusercontent.com/2345926/88537317-a33c1f00-d00d-11ea-8007-284a332a8665.png">

**Comment by luna404** [comment]
Can we add a button to return to the list of elements? (https://herams-staging.org/page/280/update)
It's already possible to do this using the breadcrumbs, but for all the other pages related to modifying the dashboard we always have a button to return to the parent page.

**Comment by jeremiehelme** [comment]
@luna404 Do you have an example of what you need ?
I ask because I'm not sure if you want a new button, above the form for example, or that we change the action of the "Annuler / Retourner au tableau de bord" button depending on the page we come from

**Comment by luna404** [comment]
I'll the button as a new issue, as the rest is good for today's release.
