### ISSUE TITLE
Add "return to list" button to dashboard element update page

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#557]
Can we add a button to return to the list of elements? (https://herams-staging.org/page/280/update)
It's already possible to do this using the breadcrumbs, but for all the other pages related to modifying the dashboard we always have a button to return to the parent page.

_Originally posted by @luna404 in https://github.com/HeRAMS-WHO/herams-backend/issues/543#issuecomment-664841578_

**Comment by jeremiehelme** [comment]
@luna404 Do you have an example of what you need ?
I ask because I'm not sure if you want a new button, above the form for example, or that we change the action of the "Annuler / Retourner au tableau de bord" button depending on the page we come from

**Comment by luna404** [comment]
In other dashboard admin pages there is an option to return to the next higher level (see return to list below). Same option should be available on the dashboard edit page, allowing users to return to this page
https://herams-staging.org/page/27/update

![image](https://user-images.githubusercontent.com/18245059/88658940-933b4280-d0d4-11ea-996d-5b6fff972b6b.png)

**Comment by jeremiehelme** [comment]
Ok I understand,
I changed the "Cancel and go back" button action to go back to the previous page. That way you return to the dashboard if  you edited the element from there, and to the list of element otherwise

I'm adding the same behavior to the "Update and go back" button

**Comment by jeremiehelme** [comment]
I'm a bit stuck on the "Update & go back" action

When you click the button it first reload the page to update the element, then tries to redirect to the previous page. But the previous page is then the element update page, because of the reload. 

I tried adding a hidden field containing the previous page url, but the way I add it causes a problem (it adds it to the element, and then expect the property to be declared in the model). I haven't found a way to add it to the form only yet

**Comment by luna404** [comment]
If it doesn't work then forget about it. It's not the most important issue. Users can always use the breadcrumbs to achieve this. I just thought it would be nice of all the page have the same structure and the possibility of returning to the next "higher" level, but as we have a working solution, it's not worth spending too much time on this.

**Comment by jeremiehelme** [comment]
@SamMousa I'll need help on this one 

We would like that the "Update & go back" button redirect to the previous page after saving the form

I tried adding a hidden field containing the previous page url, but the way I add it causes a problem (it adds it to the Element, and then expect the property to be declared in the Element's model). I haven't found a way to add it to the form only

Thanks for your help,
