### ISSUE TITLE
Login issue (prod): page indefinitely loads until manually refreshed

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#569]
On prod, once credentials have been entered, the page indefinitely loads...
Only after refreshing user is let in

**Comment by SamMousa** [comment]
Try deleting your cookies / clearing your browser history.

Quick way to try this: start incognito mode (ctrl + shift + N) in chrome.

**Comment by luna404** [comment]
@SamuelPetragallo is this still an issue?

**Comment by SamuelPetragallo** [comment]
No has no been an issue since

**Comment by luna404** [comment]
I haven't seen this happening since we resolved the hosting issue, so let's hope it's been resolved.
