### ISSUE TITLE
HeRAMS SurveyJS transformation plan

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#570]
# Introduction

## Disclaimer

This is an early draft; any part can and will be revised if needed. All feedback is welcome!

## Problem statement

Currently we use LS and have several issues:

- Data submission is unstable, it is hard to make guarantees about data being pushed to HeRAMS successfully
- Data retrieval via the API is slow and trashes the hard disk
- The platform is not (very) knowledgeable about the survey structure since it deals with an abstraction
- The platform is not notified when structure changes and can't automate any sanity checks
- Response picker is an integration into the LS logic that makes it hard to upgrade and keep things reliable

In the near future we might also need one or more of these features:

- Offline data collection where the survey (and its logic) need to run without internet access
- Data confirmation, where we differentiate the act of updating a single field form revalidating all other fields in the survey
- Security settings for individual HFs as opposed to whole workspaces
- More granular workspace permissions (ie can edit & update but not delete responses)

By moving away from a separate platform that executes the survey and to an integrated system we can better integrate the data collection process in the platform.
Since the platform is in production and data collection is ongoing, any changes must not interrupt availability for current users and projects.

# Proposed solution: move to SurveyJS

- Introduce a new type of project: SurveyJS Project
- Create separate data store for SurveyJS data, the data is stored in a local table for easier access and no need for syncing of any kind
- Introduce new entity Health Facility, child of Workspace
- Introduce new entity SurveyJSResponse, child of HF
- Implement SurveyJS JSON parser, this will translate the JSON survey structure to something that we can easily interact with in PHP
- Integrate SurveyJS Creator as a Yii2 Widget for easy integration in the app. Will need a license for this.
- Implement page browser for SurveyJS, it will be able to hide or disable pages that are not visible due to routing
- Implement a theme for SurveyJS so that it fits the HeRAMS design
- Automatically attempt to save data everytime page navigation occurs, show the result of this somewhere on the page, if it fails this does not interrupt the user
- When finalizing the survey the user will see whether submission has succeeded, if not an option to retry will be available
- Implement (more) intelligent data export dat gets the data from the SurveyJS survey definition

## Page browser

The current implementation in LS offers limited functionality, since SurveyJS runs fully in the browser we can actually do advanced stuff like highlighting all pages that contain errors.

# Optional / future work:

- On completion ask the user whether to update everything (ie data verification) or just store the changes
- If submission does not succeed offer the user to save it to his browser so that submission can be retried later. We would need a page on the platform to browse locally saved responses for submission
- Survey composition
- Data exploration

## Survey composition

Since SurveyJS surveys are JSON documents we can easily compose surveys from different survey pages allowing us to dynamically generate a survey based on project configuration.
This would allow full freedom of custom questions and standardization of a standard part of the survey.

## Data exploration

While the dashboard system allows users to have a look at predefined data, it is not ideal for data exploration. We could implement something like PivotTable.js to allow for dynamic filtering and analysis, demo here: https://pivottable.js.org/examples/fully_loaded.html

# Conclusion

There is definitely a path that allows us to move away from LS without impacting ongoing projects. Integrating the survey engine as a library instead of a separate platform has benefits both now and in the future when it comes to features, stability and maintainability.

**Comment by SamuelPetragallo** [comment]
Question:

Introduce new entity Health Facility, child of Workspace
Introduce new entity SurveyJSResponse, child of HF

Will that (the split between a "HeRAMS-based HF layer" and associated responses also apply to ls?

**Comment by SamMousa** [comment]
It doesn't have to, if we want the least disruption possible we don't split it.
That way the flow for LS doesn't change, which saves us a lot of trouble.
