### ISSUE TITLE
Automated updating the map embedded in the WHO website

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#572]
The experience dashboard embedded in the [HeRAMS WHO website](https://www.who.int/initiatives/herams) requires to be manually updated. This is not ideal as it means the map is not in sync with the platform. 

The data for the map is taken form the projets/api but due to Esri's limitations on reading sources from the web, the  [feature layer](https://services.arcgis.com/5T5nSi527N4F7luB/ArcGIS/rest/services/HeRAMS_project_overview/FeatureServer) is updated manually using a python script. Ideally this should be improved, either by scheduling the script to run daily or by finding a different way of importing the data (i.e. API would have to be made available in a ESRI compatible format).

**Comment by SamMousa** [comment]
Does this mean that we're currently free to change the default response format, as long as it contains the same information?
Since you can simply adapt the python script?

Also, what is an ESRI compatible format? I think GeoJSON would be fine.
How does your script currently push the changes to the system?

**Comment by luna404** [comment]
`Does this mean that we're currently free to change the default response format, as long as it contains the same information?
Since you can simply adapt the python script?`
Yes

`Also, what is an ESRI compatible format? I think GeoJSON would be fine.`
Surprisingly GeoJSON is not supported. Here's a list of the supported file formats. I think CSV would be the easiest.
![image](https://user-images.githubusercontent.com/18245059/95831012-c9ce4400-0d38-11eb-8229-fc90167c05a1.png)


`How does your script currently push the changes to the system?`
It is updating a hosted feature layer https://who.maps.arcgis.com/home/item.html?id=e96ad71b4ef445eca2bf0c6c9f4dc3e1
