### ISSUE TITLE
ls / ResponsePicker Plugin / user can't see "save" buttons

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#576]
On ls, user (11078) can't save when changing settings of the plugin (the save button doesn't show) on Yemen (https://ls.herams.org/admin/survey/sa/editsurveysettings/surveyid/618734#pluginsettings) - verified through impersonation

I can myself access those (so can Jeff)

Only current workaround is to have global admins do it on behalf of country admin

**Comment by jeremiehelme** [comment]
You've probably already checked that, but just in case :
- I can see the buttons for Yemen 
- I can't see the buttons for Tchad and Nigeria

You probably gave me the rights for Yemen, and I probably don't have the required rights for Tchad and Nigeria
Maybe it's the same problem for the user 11078 ?

Can he see the buttons on the others tabs ?

**Comment by SamuelPetragallo** [comment]
I don't recall that there were rights associated with that. Assumption from my side is if you can access the plugin then you can tweak it. @SamMousa / @luna404 have I missed something there?

**Comment by luna404** [comment]
@SamuelPetragallo I can't see permissions of users I haven't created myself so I can't verify this, but have you check what permissions Ahmed has? 

If he doesn't have "update" permission for the the survey settings he can see the plugin but is not allowed to save. This would explain the issue he encountered.

![image](https://user-images.githubusercontent.com/18245059/91274326-ca0d8280-e77e-11ea-9b70-5bed764e7194.png)
