### ISSUE TITLE
Support for batch syncing of 1648 WSs of HeRAMS PHL 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#578]
Support for batch syncing of 1648 WSs of HeRAMS PHL after being deactivated due to MOH requests of changing some questions.

**Comment by SamMousa** [comment]
What is the project ID on the platform?

**Comment by JeffDotingco** [comment]
HeRAMS Philippines (ID 956391)

**Comment by SamMousa** [comment]
That looks like a survey ID, not a project ID

**Comment by JeffDotingco** [comment]
Project ID in platform is 23

**Comment by SamMousa** [comment]
It's busy, will finish automatically in a few minutes. Closing this, reopen if it is not synced in ~ 1 hour.
