### ISSUE TITLE
User management table uses wrong template

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#583]
The `Manage user` table should span the entire screen. There is no need for it to be limited to half the page as there is no other element on this page.

https://herams-staging.org/user/index

**Comment by jeremiehelme** [comment]
I've pushed a fix
I don't have access to this page on staging, do you have the rights to give me the access ?
Thank you

**Comment by luna404** [comment]
No, you have to ask @SamMousa

**Comment by jeremiehelme** [comment]
@SamMousa when you have a minute, can you give me the rights to access the user management pages on staging ?
Thanks

**Comment by SamMousa** [comment]
I can't, the feature to share admin permissions was removed. Making someone a global admin requires that to be re-added.

Possibly if you re-add it in `controllers/admin/Share.php` me (and other global admins) will be able to do it.

**Comment by jeremiehelme** [comment]
ok thanks,
I've added the PERMISSION_ADMIN, can you @SamMousa or @luna404 give me the right ?
Then I'll remove it

**Comment by luna404** [comment]
@jeremiehelme I just granted you full admin permissions. Do you have access now?

**Comment by jeremiehelme** [comment]
Yes, perfect, thank you both !
