### ISSUE TITLE
Creating questionnaires in SurveyJS - Initial testing

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#590]
Related to #570 
I tried to recreate the standard HeRAMS questionnaire in SurveyJS to explore a little how SurveyJS works and to see where we might encounter some challenges.

https://surveyjs.io/published?id=6c8848a9-865d-48dc-85ab-3bfcec972945

### 1. Overall impressions
:heavy_plus_sign:
- Modern user interface, easy to add/remove questions
- I like the ability to switch between the form builder and the JSON editor. 

:heavy_minus_sign:
- Less well documented than LS for things like expressions, validation rules etc.
- It is very easy to edit the wrong question, especially on pages with lots of similar questions or when you copy questions. This will take a little bit of time to get used to.
- The JSON of the questionnaire becomes relatively long. This is partially due to the way I created the ranking questions, but I'm already on 3000 lines without the services. @JeffDotingco and @SamuelPetragallo how comfortable are you doing edits directly in JSON?

:grey_question:
- Will users who create surveys be able to customize them using JS?
- In LS we have very granular permissions (e.g. e.g. allow user to only edit translations), how will that work in SurveryJS?

### 2. Question types
:heavy_plus_sign:
- Supports dependent drop down list (see region/district on page 2)
- Partner support could be simplified (see page 8)
- Improved flexibility might enable other improvements (see alternative layout for services on page 10)
- Supports array questions with different types
- Drop-downs support randomization, this would improve the ranking questions
- Supports multiple short questions of different types
- For sub-questions (array, multiple short questions) it is possible to decided for each sub-question whether or not it should be mandatory. This provides much more flexibility compared to LS and simplifies a lot of the complex validation rules currently in use.

:heavy_minus_sign: Does not support ranking questions: I created a potential solution that would give a similar feeling to users, but is more tedious to implement (see any of the ranking questions)

:grey_question: As we don't have the exact same question types, the survey structure is likely to change. How will this affect dashboards/data export?

### 3. Text styling and formatting
 In LS we are able to style and format text elements (i.e. help text and question labels). This could not be reproduced in SurveyJS.
 Examples of styling used in LS include multi-line help text, use of bullet points, bold and italic text, background and text color)
 
Solution 1: In some cases help text could be moved to a HTML field which allows for more styling option (see *Observed precision* on page 4 for an example). Needs more testing to know if all use cases can be replicated.
Solution 2: There seems to be some level of markdown supported ([link](https://surveyjs.io/Examples/Library/?id=survey-markdown-matrix&platform=jQuery&theme=modern#content-js)), but I can't implement this in the standard test environment. 

### 4. Validation 
Basic validation seems to be working, but this requires more testing. I can't find a good equivalent to the LS manual which gives lots of examples on how to use expressions. This also goes back to the question about survey creators being allowed to write custom JS validation rules.

:heavy_minus_sign: 
- Can't reproduce date validation for *Date of update*. Date should not be after today. (It should be fairly easy to do this with JS though)
- Can't reproduce validation for GPS precision. This not possible with the standard operators available but could be achieved using JS.

### 5. Survey logic
:heavy_plus_sign: No issues encountered, I was able to reproduce the survey logic for the standard HeRAMS questionnaire. 

:heavy_minus_sign: Not possible to copy logic form one question to multiple other questions. It is however possible to copy survey logic from one question to another using the JSON editor.

### 6. Relevance
Seems to be similar to LS, no issues encountered. 

### 7. Copying / importing questions
:heavy_plus_sign: Pages and questions can easily be duplicated. It is also possible to create "template" questions.

:heavy_minus_sign: Import of questions/groups from another survey requires a some understanding of JSON.

### 8. Expressions / equations
Needs further testing. So far I don't know how to:
- reference a question label or code
- reference the record id/UOID (this is used to create HF pcodes)
- use functions such as `substr`

### 9. Translations
Not tested, but seems to be straight forward. 

:heavy_plus_sign: Ability to export translations to CSV and re-import.

:grey_question: Need to test if validation error messages can be translated.

**Comment by SamuelPetragallo** [comment]
@luna404 thanks a lot for this initial, very comprehensive, round of Survey.JS , great!

@SamMousa how do you suggest we tackle some of thee questions? Assuming a lot of these are probably due to the lack of time documenting their work for end users as Caro highlighted, woldn't it be easier to connect with them and discuss those points directly? If so, anyone you can suggest?

**Comment by SamMousa** [comment]
> Assuming a lot of these are probably due to the lack of time documenting their work for end users as Caro highlighted, woldn't it be easier to connect with them and discuss those points directly? If so, anyone you can suggest?

I don't think this is the way forward. They put out the work open source, so the very least we can do is invest our time and do some research (possibly even contributing improvements to the docs). Only if that doesn't yield results we should ask them to spend time on it.

Regarding the questions posed, anything is possible. We can have permissions as specific as we want, all we must do is decide what we really need.

**Comment by SamMousa** [comment]
I think most of the missing features mentioned are actually present (like ranking questions or date validation)

**Comment by luna404** [comment]
Neither of the two option exist in the free version, but if they exist fine.

Question on the survey structure. How much flexibility do we have in redesigning the questionnaire without breaking everything else? For example, if we were to change the service availability questions (QHeRAMSXXX) from multiple single choice questions to an array questions would this completely break the dashboards and worldmap pop-ups?

**Comment by SamMousa** [comment]
> Neither of the two option exist in the free version, but if they exist fine.

There is no difference between free & commercial version other than how you use them, it's the exact same code.

Ranking: https://surveyjs.io/Examples/Library?id=custom-widget-sortablejs&platform=jQuery&theme=modern

Date validation with dynamic maximum: 
![image](https://user-images.githubusercontent.com/547021/99264089-54b2ca80-2820-11eb-9998-76f552677cd0.png)

For date validation we would need to add a function that exposes today's date, but that's something that SurveyJS supports in a very simple way.

**Comment by SamMousa** [comment]
> Question on the survey structure. How much flexibility do we have in redesigning the questionnaire without breaking everything else? For example, if we were to change the service availability questions (QHeRAMSXXX) from multiple single choice questions to an array questions would this completely break the dashboards and worldmap pop-ups?

As long as the data type remains the same we could generally make it work...
So don't change multiple choice to single choice (from an analytics point of view it would also invalidate your data anyway).

Your example is more about the way questions are stored, SurveyJS allows you to configure that separate from the variable name.
So you could have a question that stores its value in a variable with a different name.
Not specifically sure about how that would work with an array question, but regardless with panels and things like that you have way more freedom. 
I don't think it'll be an issue

**Comment by luna404** [comment]
`Ranking: https://surveyjs.io/Examples/Library?id=custom-widget-sortablejs&platform=jQuery&theme=modern`
This is not ranking question in the same sense than we have it in LS. This one only allows to sort all answer option. We need both select and sort.

`Date validation with dynamic maximum:`
Can you show me where this is. I only see the min and max date options
![image](https://user-images.githubusercontent.com/18245059/99363921-9e012980-28b5-11eb-9d9d-61e848b5da76.png)

`For date validation we would need to add a function that exposes today's date, but that's something that SurveyJS supports in a very simple way.`
Ok. 

We would also need a validation rule for the GPS coordinates. Coordinates need to fall within the bounding box of the country/area and need to have at least 4 decimal places. The first part of the validation formula should be doable with the basic expressions available but I don't know how to do the 4 decimal part with the basic expressions available. Should be fairly straight forward to do in JS though.

**Comment by SamMousa** [comment]
>This one only allows to sort all answer option. 

That's correct: https://surveyjs.io/Examples/Survey-Creator?id=customwidgets&theme=bootstrap you can configure it in many ways...

>  I don't know how to do the 4 decimal part with the basic expressions available

Regex validation with `\d+\.\d{4}`. Bounding box is also fairly simple using a regex.

**Comment by luna404** [comment]
`Regex validation with \d+\.\d{4}. Bounding box is also fairly simple using a regex.`
Thanks
