### ISSUE TITLE
How to delete users in individual WSs?

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#596]
I am trying to delete individual users for WSs but I couldn't delete users (e.g., TOM HIATT) in the WS screenshot below (WS refresh done after disabling all permissions) :

<img width="1680" alt="Screen Shot 2020-08-28 at 9 01 04 PM" src="https://user-images.githubusercontent.com/50957748/91563669-d73e9300-e971-11ea-97c6-52bdbb59df97.png">

**Comment by luna404** [comment]
@JeffDotingco are these newly added user or users that used have access to this workspace before we implemented the new permissions?

**Comment by JeffDotingco** [comment]
Hi @luna404, the user was provided access last year, before we implemented the new WS permissions

**Comment by luna404** [comment]
My guess is that these users used to have "allow everything" permissions which is still assigned and therefore they don't disappear.

@SamMousa I thought we deleted all the "allow everything" permissions to avoid this issue?

**Comment by SamMousa** [comment]
Apparently not? 

I can remove them now and it should resolve this issue at least.

**Comment by luna404** [comment]
Yes, please remove the "allow everything" permission from all users

**Comment by SamMousa** [comment]
done

**Comment by luna404** [comment]
@JeffDotingco can you confirm that this resolved your issue so we can close this?

**Comment by JeffDotingco** [comment]
working now
