### ISSUE TITLE
ERROR in data entry in HERAMS YEMEN

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#599]
You can't add response, edit response in HeRAMS YEM as you are receiving the error in the attached screenshot.

<img width="1680" alt="Screen Shot 2020-08-30 at 3 18 57 PM" src="https://user-images.githubusercontent.com/50957748/91653523-5350ec00-ead4-11ea-855d-f85d46a3942a.png">

**Comment by luna404** [comment]
@JeffDotingco I close this one as it has been resolved.
