### ISSUE TITLE
Translate dashbaords

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#602]
It should be possible to display the dashboard in any language in which the questionnaire is available.

**Comment by luna404** [comment]
@jeremiehelme I assigned to you but I assume this is something you will need support from @SamMousa. So feel free to reassign it if needed.

**Comment by luna404** [comment]
Obviously this would also mean the filters would have to be translated...

**Comment by SamMousa** [comment]
Ideally this should be implemented after #570
