### ISSUE TITLE
Response picker: Remove blue plus sign

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#603]
Can we remove the first column displaying the blue plus sign? 

Apparently having a plus sign there and another one for adding a new response is confusing to users. I don't see any need for the blue plus sign used to indicated a HF container, so I think the easiest solution would be to remove the blue plus sign.

**Comment by jeremiehelme** [comment]
Let's see if it's obvious enough without a sign. The rollover animation should help understand that you you can click the row

**Comment by luna404** [comment]
I like the rollover animation 👍
