### ISSUE TITLE
Response picker: Only allow editing for the most recent record

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#604]
We've been having a lot of debates with our country focal point on whether or not end users should be allowed to edit a record. Neither solution provided through LS (full edit or no edit at all) seem satisfactory, so we would like to explore a new solution. As response are now ordered by HF and date of update, can we mask the edit button from all but the most recent record?

This would mean, if a user adds a new response, only the newly added response can be edited. If a user deletes the latest record, the second most recent would become the most recent record and thus should now be editable.

**Comment by jeremiehelme** [comment]
I like it, it helps understand that the responses are stacked and linked together

**Comment by luna404** [comment]
Great job, seems to be working really well. I was wondering if it might help to highlight the first record to make it ever more evident that a user edits only this one. Not entirely sure if it makes sense though.

**Comment by SamuelPetragallo** [comment]
Agree: whatever reinforces that visually is good to take I think. That added with the "New" label will really help

**Comment by jeremiehelme** [comment]
Sure, 
I added the view option back, and greyed the old results

**Comment by luna404** [comment]
Works, but but may create same process issues as explained here #605
