### ISSUE TITLE
Response picker: Add "new response" label

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#605]
A newly added response should be highlighted using a "new" label, similar the mock-up below. Ideally, the new label is shown both in the HF container and in the response itself (not shown in the mock-up).

The label should be based on the date of creation (available in LS) and only be shown for 48h (will have to figure out what a good time interval is). After the 48h have passed, the label should automatically disappear. 

![5 HeRAMs_admin_WorkspaceData](https://user-images.githubusercontent.com/18245059/91840798-91bfe580-ec51-11ea-90df-0f875326617c.jpg)

**Comment by jeremiehelme** [comment]
It's done on staging
For now I've remove the test, it displays on every row so you can see the result
https://ls.herams.org/618734?token=7iZdKx3RiQjzlMb1&newtest=Y&lang=en&test=ResponsePicker

**Comment by luna404** [comment]
Looks great. 

How do you determine which record is the the most recent record. I thought this was based on the data of update. In the example below the record that is editable is not the most recent one based on the date of update...

![image](https://user-images.githubusercontent.com/18245059/92226702-6f260a80-eea5-11ea-8137-42a43dda78c2.png)


@SamuelPetragallo using two different fields to determine whether a facility can be modified vs. which one gets the "new" label might raise an issue. If editing is determined by the date of of update, users could theoretically add a record which is not the most recent. This record would then be labelled as new but would not be editable.

**Comment by SamuelPetragallo** [comment]
Agree but that is an exceptional and fairly unlikely scenario - I think it's still valid as an approach but haven't thought through other options. Any suggestions there?

**Comment by jeremiehelme** [comment]
I order them by response id. So the last created is on top of the list
It would be the same order than with the creation date normally

That's why the date of update of the first record is not the most recent here

**Comment by luna404** [comment]
I think we should always order by date of update. Record id is a tricky thing as this might changes when we have to deactivate/reactivate the questionnaire to do some modificaitons.

> Agree but that is an exceptional and fairly unlikely scenario - I think it's still valid as an approach but haven't thought through other options. Any suggestions there?

I would say either we leave it as is and live with the fact that they could add a new response that is never editable, or we change the condition which decides which records is editable to "latest record or created within the last 48h. This might results in two records that are editable for the same HF, but it would give users an opportunity to correct an erroneous date.

**Comment by jeremiehelme** [comment]
- I ordered the records by date of update (most recent first)
- I allow editing of the most recent record only

let me know if it works for you that way

**Normal way** 
- a user add a new record
- he set the date of Update to a date after the most recent record for this HF
- the record he just created is editable because it's the most recent
- if the Update is less than 24h old, we show the "new" label

**What can cause an error**
- a user add a new record
- he set the date of Update to a date before the most recent record for this HF
- the record he just created is not editable because it's not the most recent

**Comment by luna404** [comment]
This is not working (see #617)
