### ISSUE TITLE
Response picker: Make add response button blue

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#606]
Users still seem to have issues understanding the add response button. To make it more obvious that his is a button they should press, can it be styled like an ordinary blue button?

**Comment by jeremiehelme** [comment]
To test 
https://ls.herams.org/survey/index/sid/391149/token/AfHsQ82ri7Pedn3/newtest/Y?test=ResponsePicker

**Comment by jeremiehelme** [comment]
We discussed that and removed the word "new", since we start from the last response, not a new empty questionnaire
Now if the users prefer "new" I can add it

**Comment by luna404** [comment]
I forgot about that whole discussion....

@SamuelPetragallo I leave the decision to you.

**Comment by SamuelPetragallo** [comment]
I don't remember that either to be honest, do we have that discussion on Git so I can go back and read how we got there before making a decision on this?

**Comment by jeremiehelme** [comment]
The discussion on the response picker is here, but there no mention of that 
https://github.com/HeRAMS-WHO/herams-backend/issues/321
You can see that the button is renamed at some point in the mockup, so we probably discussed that

The main point was the one I mentioned, that we start from the last response, not a new empty questionnaire.
There were a confusion between the edit and update actions
