### ISSUE TITLE
Response picker: date formating

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#607]
@jeremiehelme when you get the field names from LS, do you also get information on the filed type? We have one specific case where the country would like to display the month of update. For this we have created a specific field in the questionnaire. In LS with have a few display options for dates, including only showing mm-yyyy. However, LS saves it as a normal date-time field. Thus, it currently appears as a normal date field in the response picker. As the preferred display option is available in LS, we're wondering if the response picker could display date fields based on what is defined in LS?

![image](https://user-images.githubusercontent.com/18245059/91841633-fcbdec00-ec52-11ea-963f-5cd0704e72ed.png)
![image](https://user-images.githubusercontent.com/18245059/91841695-152e0680-ec53-11ea-9a81-80669eb492bd.png)

As this is very specific issue and we only have one use case, it's not worth spending a lot of time on this. If it is complected or not possible we can find a way to do this directly in the questionnaire by converting the field to a text field.

**Comment by jeremiehelme** [comment]
Yes, I found a way to get the advanced settings. I now apply the date format setting for the Date type questions, if it exists.
However, the date format specified here is in mysql format (**mm-yyyy**). PHP expect something like **Y-m-d**

Can you change the date format ? or will it impact the display in LS ?
If it's not possible to change it, I'll convert the mysql format on my side

Thanks,

**Comment by luna404** [comment]
We can only specify the display format in LS, so whatever we set will also be what the users sees when entering the data. As they have date picker I don't see too much of an issue to change the format though. I could change it yyyy-mm if that would help.

**Comment by jeremiehelme** [comment]
Ok, so it's not possible to specify a format like 'Y-m-d' in LS because it would break the datepicker in the questionnaire, which expect 'yyyy-mm-dd'

I convert the format to what php expect in the code. 
It works only for the years, months and days, not for the hours, minutes and seconds yet. I'll add it if you think we need it

To test 
https://ls.herams.org/survey/index/sid/618734/token/j7hzgczTmfERNBS1/newtest/Y?test=ResponsePicker

**Comment by luna404** [comment]
Cool, thanks a lot.
