### ISSUE TITLE
Add numeric questions to dashboards

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#609]
Related to issues #471, #472

Can we add numeric field types to the dashboard? I would suggest to either display them as simple cards showing the sum of the numeric fields or to have a bar chart where users can select the x axis variable which will be used to aggregated the data.

**Comment by SamMousa** [comment]
We can't do this with the current infrastructure, we do not know the type of open questions.

This should be implemented after we move to SurveyJS.
