### ISSUE TITLE
HF Popups : additional informations

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#610]
Display relevant informations :
CONDB, GEO1...

Later it would be great to add a button to download the HF report

**Comment by luna404** [comment]
I would suggest to start we use the "standard" fields GEO1, CONDB, CONDE, HFFUNCT, HFACC, and UPDATE. 

Yes to the option to download the HF report

**Comment by jeremiehelme** [comment]
Here is the popup with the informations 

![Capture d’écran 2020-10-09 à 15 26 53](https://user-images.githubusercontent.com/2345926/95589931-b4f66580-0a45-11eb-8aa5-4c8b801b4996.png)

I'll add the update too, under or next to the title

**Comment by luna404** [comment]
This is awesome. Great job!

Are these the only fields currently available to you? I think ideally we would also like to include UPDATE and MoSD3 (the type of health facility).

Question on the service availability map. It seems like the all services of all facilities that fall into an aggregate are combined and then evaluated. Would it be possible to treat HF as a categorical value and show them as pie charts like for the other questions? Right now if you zoom in the new aggregates might have a different value. 
https://herams-staging.org/project/24?page_id=290&parent_id=289
![image](https://user-images.githubusercontent.com/18245059/95596318-84b2c500-0a4d-11eb-9902-d65d8e5e4f35.png)
![image](https://user-images.githubusercontent.com/18245059/95596354-94320e00-0a4d-11eb-9185-a2a0621144ad.png)

**Comment by luna404** [comment]
Forgot to add, you don't seem to be using the marker radius input value anymore. I think that's fine but we should then remove the field from the dashboard settings. Can you confirm so I can raise a new issue for this.

**Comment by jeremiehelme** [comment]
It's ok for the marker radius, I use it now.

I've added MoSD3, but I'm still looking for how to add the UPDATE
I'm on the service availability map, thanks for the help !

**Comment by jeremiehelme** [comment]
Ok for the service availability map and the MoSD3

![Capture d’écran 2020-10-13 à 17 20 46](https://user-images.githubusercontent.com/2345926/95881082-7a0f6d00-0d78-11eb-85dc-030f9aeb2005.png)

I'm on the update

**Comment by jeremiehelme** [comment]
![Capture d’écran 2020-10-30 à 10 04 45](https://user-images.githubusercontent.com/2345926/97680679-5eee6e00-1a97-11eb-90f5-ae4721028cca.png)

I added the Update date to the popup, and adapted the style
It makes sense to me that the Update is visible first, just after the title.
Let me know if it's not that important

@SamMousa Did you remove the workspace button on purpose, or is it just the merge ?

Thanks,

**Comment by SamMousa** [comment]
I pinged you in another issue. The button destroys performance

**Comment by jeremiehelme** [comment]
Ok thanks !

I kept the link to the workspace, it doesn't require a test and should not impact the performance

**Comment by SamMousa** [comment]
Have you tested that? Specifically tested the number of queries run by your code?
The line you use could result in up to 3 queries per response... unless you are properly preloading all that data...

**Comment by luna404** [comment]
@jeremiehelme do you have an update on this issue. Is there a way you can add the "workspace" button again or is this out of scope for now?

**Comment by SamMousa** [comment]
IMO This should be out of scope until we get the abstract guidelines on navigation..

Also, if it is a distinct part of a bigger issue, it makes sense to close this and create a new smaller issue for just that button.

**Comment by luna404** [comment]
Fine with me. I'll open a new issue for the button. 

@jeremiehelme the "last updated" field seems to have been accidently removed together with the button. Can you add it back and then will release it together with issue #141. This will already be a huge improvement to the maps!

**Comment by jeremiehelme** [comment]
@SamMousa Update date has been removed. is it because it was causing too many request too, like the workspace button ?

**Comment by SamMousa** [comment]
For project level it doesn't work, updating takes longer than 1 hour

**Comment by luna404** [comment]
I think there is a misunderstanding. What @jeremiehelme meant is he added the variable "Update" to the pop-up which has been removed. This is just a variable within the questionnaire like any of the other variables displayed in the pop-up.

**Comment by jeremiehelme** [comment]
@SamMousa Sorry that was not clear

I'm talking about the update date shown under the title of a HF popup

I use this method to get the update date
`'update' => date_format($response->getDate(), 'Y-m-d'),`
I see it return a Carbon type, unlike the other method, so I guess it makes a request to LS to get the latest update date, and that is why you delete it

![97680679-5eee6e00-1a97-11eb-90f5-ae4721028cca](https://user-images.githubusercontent.com/2345926/99710229-95207b80-2aa0-11eb-81b5-f9ee647bc52b.png)

**Comment by SamMousa** [comment]
I don't think it does, you can just check the source to find if it does or doesn't right?

**Comment by jeremiehelme** [comment]
Looks good to me, there is not a big difference between the project popup and the dashboard in terms of number of requests

<img width="1439" alt="Capture d’écran 2020-11-24 à 17 50 10" src="https://user-images.githubusercontent.com/2345926/100205969-0e3b2b00-2f06-11eb-8b5c-881a9cc5d3d3.png">

I'd like to compare with and without the update date to be sure, but I have to find where to add the correct permissions to see the toolbar

**Comment by luna404** [comment]
`Looks good to me, there is not a big difference between the project popup and the dashboard in terms of number of requests`

Are you sure it won't slow down big projects such as the Philippines?

**Comment by luna404** [comment]
@jeremiehelme can you remove the space before the colon please. It's not common to have a space before colons in English and it would avoid issues like the one below. 

![image](https://user-images.githubusercontent.com/18245059/100208358-ee593680-2f08-11eb-87c0-060b8cdd2054.png)
