### ISSUE TITLE
Issue in registering to the platform using a yahoo email

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#612]
Some participants are not receiving verification email to create a HeRAMS account using a yahoo email. Also tried this now using jeffrey_upm2006@yahoo.com, successful in registering a yahoo email, but the verification to yahoo email is not received even in spam. Just to check, I registered my WHO email, and the verification email is working fine (received in SPAM).

Upon checking on staging, it is working fine using a yahoo email

<img width="1680" alt="Screen Shot 2020-09-18 at 4 45 25 PM" src="https://user-images.githubusercontent.com/50957748/93578315-c19c1680-f9cf-11ea-923e-df2d298a0397.png">

![Staging yahoo email notification ](https://user-images.githubusercontent.com/50957748/93579563-34f25800-f9d1-11ea-8726-9fff750bff28.png)

**Comment by SamuelPetragallo** [comment]
I've gotten this on herams@who.int in case of help:

This is the mail system at host mail-eu-west-mx-1.mailspot.info.

I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own text from the attached returned message.

                   The mail system

<sanantonio_amy@yahoo.com>: host mta7.am0.yahoodns.net[67.195.204.79] said: 554
    delivery error: dd Not a valid recipient - atlas110.free.mail.bf1.yahoo.com
    (in reply to end of DATA command)

**Comment by SamuelPetragallo** [comment]
@JeffDotingco the email doesn't exist (I can not sent an email to it from my account either). Not related to the platform

**Comment by JeffDotingco** [comment]
Verification emails are just delayed (by 2 hours using my yahoo email) using yahoo email
