### ISSUE TITLE
Hosting / Infra layout / Costing

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#615]
As mentioned we need to pick between Azur and Google. For that we need:

1. a layout of the infrastructure (to be shared with Nico)

Then

2. an answer to whether there are technical requirements that can only be fulfilled by one of the vendor amongst MS Azur and Google Cloud:
a. If yes specify which as a justification to choose one of the options
b. If no (most likely scenario): run calculations with online calculation tool and choose based on price/service (on that Nico can help if I understood correctly). Note we have a discount of 15% on MS Azur

**Comment by SamMousa** [comment]
I propose we do this incrementally.

First step for me would be moving the database, it's technically simple but will immediately make sure that our data is no longer at risk.

![image](https://user-images.githubusercontent.com/547021/94781342-fb0a5400-03c9-11eb-8cbc-6536cf3595dd.png)


Note that Azure also has datacenters in Switzerland, but that's way more expensive.
If we get this we can use it to run the prod database (and maybe the staging database too, if we 're looking to cut costs).


We really should not go into a model where we "request" virtual hardware, this means we lack the control required and will be unable to scale up or down as needed.
It really should be a budgeting method not a manual, slow and inefficient way of requesting virtual machines.

Currently IT has no experience providing these services, but that's okay, no support is needed.

We need to get a separate HeRAMS subscription in the WHO organization: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/scale-subscriptions

**Comment by SamuelPetragallo** [comment]
Following up with admin now on payment of that service

**Comment by SamMousa** [comment]
@SamuelPetragallo I'm assuming you are following up on the email we received last? These are organizational issues that I cannot solve..

> Though, you will still need to go through the cybersecurity for the risk assessment,  penetration testing, etc.

> We need a valid PTAEO for the whole lifespan of the subscription. We receive monthly invoices, our administrative services will take care of the chargeback.

**Comment by SamuelPetragallo** [comment]
Yes, 99% complete, awaiting one last validation (we have very few budgetary lines that run beyond a year, we need to use somebody else's, and then reimburse, which is making the process a little more cumbersome)

**Comment by SamMousa** [comment]
We can simply choose not to do the reservations, or do 1 year reservations; you just pay a little extra but if that is simpler...
