### ISSUE TITLE
Response picker: "new" label not showing 

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#617]
@jeremiehelme the "new" label doesn't seem to show. I have added a new response this morning, but the label is not appearing. Could you please have a look at this.

related to #605

**Comment by jeremiehelme** [comment]
Sure, which survey did you add a response to ?

**Comment by luna404** [comment]
Yemen

**Comment by jeremiehelme** [comment]
Ok, that should be good now, let see tomorrow if it disappears

**Comment by luna404** [comment]
Seems to be working now
