### ISSUE TITLE
Export a VV survey file, survey archive, results to application not working in LS for HeRAMS PHL

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#622]
Export a VV survey file, survey archive (.lsa), results to application not working in LS for HeRAMS PHL

<img width="1680" alt="Screen Shot 2020-10-02 at 12 09 26 AM" src="https://user-images.githubusercontent.com/50957748/94834904-8f64cd00-0443-11eb-873d-4a2f18b8b88f.png">
<img width="1680" alt="Screen Shot 2020-10-02 at 12 06 25 AM" src="https://user-images.githubusercontent.com/50957748/94834925-9ab7f880-0443-11eb-8acb-974dac7255ed.png">

**Comment by SamMousa** [comment]
I think the survey is broken; the table is missing columns.
This could indicate there are too many columns.

**Comment by SamMousa** [comment]
Selecting "old VV version" seems to work.

**Comment by JeffDotingco** [comment]
Hi @SamMousa, selecting "old VV version" seems not to work from my end

**Comment by JeffDotingco** [comment]
Hi @SamMousa, the export a VV survey file is still not working for HeRAMS PHL. I am preparing a backup before the implementation of HeRAMS in Mindanao. Export results to application and export .lsa is also not working.

**Comment by JeffDotingco** [comment]
Hi @SamMousa, export a VV survey file (either old or last VV version) is still not working for HeRAMS PHL. Export results to application and export .lsa are also not working as well. I am trying to create a back up before the implementation in Mindanao.

**Comment by JeffDotingco** [comment]
export VV survey file and export results to application (even if selecting only some variables and limiting the number of records) are 
<img width="777" alt="Screen Shot 2020-12-08 at 7 23 04 PM" src="https://user-images.githubusercontent.com/50957748/101477942-e9759780-398a-11eb-8983-92dc786d8650.png">
still not working

**Comment by JeffDotingco** [comment]
I will be using the backend to update / replace the GPS coordinates of Workspaces in a region of HeRAMS PHL using the **import VV survey file /  replace answers in file in the existing record**. The GPS coordinates were missing in the responses of HFs, and was just provided by the MOH yesterday. In need of support if this can be sorted. Otherwise, I'll be manually encoding about 1000 records in the backend.
