### ISSUE TITLE
Error in HeRAMS PHL data entry (some responses in basic amenities are not reflected in the platform and LS)

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#626]
Error in HeRAMS PHL data entry (some responses in basic amenities are not reflected in the platform and LS). Some of the records have no basic amenities responses, yet they were classified as "completed". Please find screenshot of the error after basic amenities section.

<img width="1680" alt="Screen Shot 2020-10-07 at 11 27 59 AM" src="https://user-images.githubusercontent.com/50957748/95284692-5e482a80-0891-11eb-8f45-02a4765df4e4.png">

**Comment by SamMousa** [comment]
I think that table is broken, you have to deactivate and reactivate the survey. (This is something I also noted when testing the export problems.)

**Comment by JeffDotingco** [comment]
Hi @SamMousa, bit afraid of deactivating it as I can't export a vv survey file as a back up. the workspaces are also a lot to be manually refreshed.

**Comment by SamuelPetragallo** [comment]
@SamMousa helpful if we get someone ls quickly to help sort that out? (thinking of Denis)
@JeffDotingco we're on it

**Comment by luna404** [comment]
@SamMousa as @JeffDotingco can't make a manual back-up can you make one just to be save. I know we should not need it as it should be possible to import the data from a deactivated response table, but given all the issues we have with the PHL questionnaire I would prefer if we don't have to take any risks.

Also if we deactivate the survey, we would need you to sync all workspaces for us. There are too many to do this manually!

**Comment by SamMousa** [comment]
I'm doing an export now, but if the table structure changes too much re-importing might take longer. 

@JeffDotingco please go ahead and deactivate then reactivate the survey.

**Comment by JeffDotingco** [comment]
Done deactivating and reactivating HeRAMS PHL. For support of manually refreshing all the WSs @SamMousa. Thanks!
