### ISSUE TITLE
Data not sent to survey admin if user encounters error

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#628]
related to #626

The error message states that the data is not lost but sent to the survey admin. Survey admin is herams@who.int but we do not get any notifications of errors.

**Comment by luna404** [comment]
If we can't fixt the underlying issue could we change the message displayed to users so they don't work under the assumption that we can recover their data?

**Comment by SamMousa** [comment]
I'd recommend using a non WHO email for that.. WHO is kind of careless and just discards mails it might suspect are maybe spam.


I imagine that's what is happening. Regardless, even if you do receive the emails manual data recovery will be a tiresome process...

**Comment by SamMousa** [comment]
I have now disabled the message.

Add to workflow: test survey via data entry screen after reactivation.
