### ISSUE TITLE
Verification email not received instantly

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#636]
We have users reporting that the verification email upon registration takes several hours to appear. Apparently it only happens to yahoo users. 

I would have that this is an issue with yahoo but wanted if you have any ideas what could be the reason for this delay.

**Comment by SamMousa** [comment]
We don't do anything asynchronously, so we either send the mail directly or not at all. 
We send outbound mail via a service called mailspot (mailspot.info) so it is probably on their end.

We should probably switch to a provider like SendGrid, they offer a free plan of 100mails/day and provided advanced analytics.
The paid plans start at ~$15 / month and we'll be able to send ~ 40.000 mails a month.

Note that as most SaaS offers this requires a credit card. 

Other than that, there is nothing we can do; I'm closing this for now and we can create a new issue if we decide we want to move to a professional mail service provider. It won't be very relevant until we are able to issue creditcard payments.
