### ISSUE TITLE
Data sync does not include manual updates in LS

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#637]
If a user makes edits directly in LS these changes are not updated in HeRAMS as part of the nightly sync. I thought the nightly sync has the same effect as manually syncing a workspace. Could this be changed?

**Comment by SamMousa** [comment]
Nightly sync has been disabled since the server problems. I'm not confident re-enabling it will not bring it down. It is currently going down several times a day whenever there is a spike in the load

**Comment by luna404** [comment]
Now that the database has been moved, can we re-enable the nightly sync?

**Comment by SamMousa** [comment]
I'm skeptical, the sync takes a very long time, could take up to 12 hours meaning we'd be syncing half the time 
For now I think it's safer to leave it disabled
