### ISSUE TITLE
Breadcrumbs missing on favorites page

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#641]
The favorites pages has no breadcrumbs or any other option to return back to the worldmap.

https://herams.org/user/favorites
![image](https://user-images.githubusercontent.com/18245059/96697691-7c7f5180-138c-11eb-9dcd-9dd63427cb8a.png)

**Comment by jeremiehelme** [comment]
Added the breadcrumb with the link to the world map
Also clicking on the herams logo brings back to the map, but it's not obvious

**Comment by luna404** [comment]
I don't see the breadcrumbs. 
![image](https://user-images.githubusercontent.com/18245059/96724654-5e2b4d00-13b0-11eb-80ad-37244c098a1e.png)


`Also clicking on the herams logo brings back to the map, but it's not obvious`
I need to learn to remember this one :)
