### ISSUE TITLE
LimeSurvey: Improve date picker for RTL layout

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#642]
In the Arabic versions of the questionnaires the data picker is displayed on top of the question making difficult to select a date. Any chance this could be improved a little?

![image](https://user-images.githubusercontent.com/18245059/96698592-98372780-138d-11eb-85fd-677a75f1a978.png)

**Comment by jeremiehelme** [comment]
Sure,

Yemen use the Herams-multilingual theme. Herams-multilingual-New has better styling for the elements
Can I switch to it ?

In the meantime I copied the style for the date picker, so it displays well now

**Comment by luna404** [comment]
Thanks, I've changed it myself.
Looks much better wit the multilingual-new template.
