### ISSUE TITLE
PHL dashboard not loading reliably

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#648]
The dashboard for the Philippines seems to take especially long to load on prod and times out on staging.

If the loading time is related to the number of HF, we could temporarily remove some of the HF, but we would need help deleting the 1000+ workspaces.

staging: https://herams-staging.org/project/23
prod: https://herams.org/project/23

**Comment by SamMousa** [comment]
@jeremiehelme 

https://github.com/HeRAMS-WHO/herams-backend/blob/master/protected/widgets/map/DashboardMap.php#L83

That line does a query for every response used in the map; that's what causing the big slow down.

I'm going to remove the button from the popup.

**Comment by SamMousa** [comment]
@luna404 can you test on staging?

**Comment by luna404** [comment]
I still get time-out errors sometimes, but this might just be because staging in general is super slow. It worked yesterday but when I tried today I got a time-out error for YEM and PHL. Also, PHL project only has about 600 (~6000 HF) out of the 1600 workspace (30K HF) imported on staging.

**Comment by luna404** [comment]
@JeffDotingco I think this has been resolved with the new hosting environment, hasn't it?
