### ISSUE TITLE
Merge create and import workspace buttons

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#652]
Related to issue #303 

@jeremiehelme as part of the new layout of the admin pages, can we find a way to merge the import and create workspace button into a single button? Instead of the current option, we would prefer if there is only one button to create workspace and once the user is on the "create workspace" page/tab they can choose whether to import or to create tokens. 

We can further discuss the best way of doing this once we have a clearer picture of how the new admin page work...

**Comment by jeremiehelme** [comment]
Sure, 
It would look something like this

Then on the creation page, we either use tabs, or adapt the form for the different scenarios

![4-2-Project](https://user-images.githubusercontent.com/2345926/97705568-97507500-1ab4-11eb-8e5a-a15df6ab71a2.jpg)
