### ISSUE TITLE
Projects to be included in nightly sync

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#654]
List of projects to be included in nightly sync.

id: 34 (Yemen)
id: 39 (Sudan COVID)
id: 41 (Somalia)

**Comment by JeffDotingco** [comment]
HeRAMS PHL workspace IDs:
695-724
2197-2722
6295- 6738




[Uploading HeRAMS PHL WS IDs.xlsx…]()

**Comment by SamMousa** [comment]
This should now run every 24 hours.
