### ISSUE TITLE
Discussion on the HF layer (MFL)

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#655]
Just resetting the scene before diving into "details": I think this discussion started with 2 main (possibly separate) objectives in mind:

1. reinforce the management of MFL-like variables in HeRAMS (a subset of HeRAMS variables that would characterize an HF and potentially vary less often than other variables

2. allow a 1-n relationship between this MFL and multiple responses of multiple (different) survey

This discussion therefore started based on the assumption that: HeRAMS = MFL + additional variables. I now question that assumption strongly and believe that this distinction is mostly theoretical and largely not applicable.

With that in mind, we could still aim for 1. and 2. with HeRAMS being the MFL

Objective 1. would bring benefits in terms of data quality and could probably be achieved  without all of the headaches associated with objective 2. . I would therefore set that as upmost priority

Objective 2. would not bring immediate benefits on HeRAMS core work (provided we can address 1.). Potential benefits would come with the possibility of covering new use cases. But that bears huge challenges imo (which is essentially why such a system does not exist yet) 

Bottom line: I think we should not contemplate 2. before 1. is rock solid (incl. identified POs, PAs, WOs; access and change requests systems in place; comments/discussion system in place (on HFs and dashboards/dash items); configurable API), and I don't foresee that happening in the near future

Here are some detailed consideration I wrote which brought me to the above conclusion. Up for discussion

Potential benefits and related issues of a "built-in MFL" include :

A.	Possibility in the short term to integrate an external MFL source
i.	Benefit in theory is clear: we don’t need to manage “signature domain variables” and lonely add HeRAMS specific variables
ii.	Issues
1.	very few instances where such a source exists (if any)
2.	when it exists, questions around quality and particularly the capacity of the existing processes to keep these MFLs up to date (convoluted administrative processes)
3.	challenges related to a potential dependency to an inefficient source and challenges in ensuring a seamless workflow between both (when changes are detected through HeRAMS back to the external MFL), with possibly distinct management silos in countries
4.	questions around the relevance and feasibility of maintaining an MFL, separately from other key metrics / growing confidence that HeRAMS structure is largely the best compromise to have an MFL in place / related question on where such a responsibility sits best within a given country

B.	Possibility to serve the MFL to external systems
i.	Benefits: ensure HeRAMS is well integrated and contributes positively to the entire HIS
ii.	Issues: none foreseen unless we tie that to the creation of an internal MFL (could be addressed with a configurable API)

C.	Possibility, in the longer run, to attach different datasets/surveys to a single MFL
i.	Benefit: possibility to articulate different processes on the same list
ii.	Issues:
1.	No major issues conceptually speaking as long as A.a.ii.4. is covered (meaning HeRAMS as currently is constitutes (99%) the MFL and we allow for other processes to relate information to that MFL 
2.	Challenges in determining separate workflows and ensuring seamless connections between both. I think basically that this is beyond scope and not willing to dive into this until we can cover the first piece 200% (HeRAMS as MFL without further breakdown within the platform, including: identified POs, PAs and WOs; change request mechanisms, opened communications on items (HF data or visualization items), etc.

D.	Reinforce the management of the MFL component (though undefined and country specific, we mean by that some of the “root variables” in HeRAMS (incl. name, location, type)
i.	Benefit: this normally changes less often than other variables and hence reinforcing the management of these variables improves overall data quality
ii.	Challenges: none if we are able to implement safeguards, and allow for a differentiated process (on a WS to WS basis) without imposing a distinct process (e.g. a separate project)

**Comment by SamMousa** [comment]
I mostly agree, I do think there is confusion about what I meant with the HF layer.

For me a Health Facility in the platform would be the minimum amount of data which constitutes a health facility, essentially it need not be more than a unique identifier.

Currently this is incorrectly implemented inside the HeRAMS survey via the UOID question / expression. 
Looking at objective 1 it doesn't matter if we gather those variables via the HeRAMS survey (or any other survey or process), the technical structure in the system would be the same.
Currently we the way we are reporting is by grouping responses in a workspace to identify series of responses belonging to a HF. All I want to do with the HF layer is move that from the response picker to the platform.

One simple and technically very sound way to do this, (could collide with currently implemented processes), assuming that the platform will be the MFL. Is to not offer any inputs for a user when a HF is added, instead when adding a HF the system would generate a unique ID that is used for the HF for all of its lifecycle. We could even decide to have such an ID for internal use, while allowing country specific IDs to be in use within surveys as they are now.

I think ignoring objective 2, which from a purely technical point of view is not that complicated, is not the best way to go. Designing the database to be ready for this isn't that much extra work and we don't need to support, or even make it visible in the graphical interface at all.

**Comment by SamuelPetragallo** [comment]
Agree with that. If we're talking about implementing a robust unique ID system (to replace our little workaround), that's a clear yes. It can be done with no consideration to nor impact on the current process. It will also take some of the other elements I mentioned around process to really solidify that.

Those include:
- identifiable POs, PAs, WOs
- access and change request systems in place
- comments/discussion system in place (on HFs and dashboards/dash items)
- configurable API
- and I'll add: reinforced management (with possibly dedicated permissions) of a subset of the variables in each response (beyond the unique ID)

I'm not against 2., simply feel it would require a lot of heavy lifting if only "conceptually" (in terms of workflows between MFL and other potential surveys), but probably also structurally (currently 1 project = 1 survey (and 1 set of WSs, 1 admin structure, etc.)

**Comment by SamMousa** [comment]
@luna404 if we were to implement facility ID generation in the platform (ie phasing out the response picker), do you have any insights regarding the processes impacted?

For now let's assume, for simplicity that a facility already has a unique ID, but that we do not want to use that one. So instead we'll need to support a flow where we generate a new platform ID that we own and link it to an external ID.


Processes:
1. Bulk data import
2. Creation of new facility

Below are some possible workflows, based on my lacking knowledge of the actual processes.

## Bulk data import

### Single workspace 

1. Go to the platform
2. Go to / create the workspace
3. Click import
4. Select CSV file
5. Select columns that are combined unique for each facility. This is used to determine which responses belong to the same facility 
6. Start the data import

### Multiple workspaces

1. Go to the platform
2. Go to / create the project
3. Click import
4. Select CSV file
5. Select column(s) uniquely identifying the workspace. The value of this column will be used as the name for the workspace.
6. Select columns that are combined unique for each facility. This is used to determine which responses belong to the same facility 
6. Start the data import

## Create facility

1. Go to the platform
2. Go to the workspace
3. Click create facility
4. Platform creates a facility, and takes you to the survey, which will be empty.

**Comment by SamuelPetragallo** [comment]
Consolidation of our last round(s!) of discussion with Caroline on this:

Objective 1: reinforce data management (assumption here is that each HeRAMS response = MFL + Service Monitoring responses)
1.	Ensure changes to MFL is reflected/consistent in all associated SM responses (based on the validity date)
2.	Update/submit new versions of MFL independently from update/submit new SM responses

Options HeRAMS questionnaire to be split into two forms (and 2 separate processes): MFL and SM
Proposed design
•	MFL and SM follow 2 different parallel processes, with distinct permission systems, and rules to ensure consistency across
•	Actions add new response (update) and edit remain the same and are available to both MFL and SM independently
•	Action “create new” remains the same but only applies to MFL only
•	In MFL, each HF has a UOID, version id (response id) and a validity date. HFs have multiple responses / can be versioned (see 1.)
•	SM responses are linked to HFs using the version id field and the validity date as follows: any given SM response is linked to the latest HF version that has a < validity date
•	When adding a new 
•	Need to discuss how we can ensure that the correct SM response is linked to the correct HF version
o	Anticipated challenge: when a new HF version is added, the system could dynamically re-assigns SM responses as needed (but synch/server resources issues, etc.)?
•	SM responses can only be added to HF versions that are marked as operational (vs. planned or closed) over the appropriate period. In the case of an HF being planned, no responses can be attached. In the case of an HF being closed responses can only be attached to periods where the HF was operational.
•	In the “SM monitoring response picker” only operational HFs are visible by default. However, there must be an option to view all HFs (including planned and closed). Ideally, there should be a visual difference between existing and closed/planned HF
•	Export: the same logic should be applied to the data export. By default, only SM responses for existing responses should be exported but users need the ability to export responses of planned/closed HF
•	MFL and SM responses need to have separate permission systems, both at the WS and project level (to ease assignment of responses, would be good to use permission groupings (in the forms of role – still need to be editable, so essentially just an initial copy/paste of default permissions)

Objective 2
Multiple project should use the same MFL. Assumption here is that HeRAMS (MFL + SM) is the MFL
Justification
Managing the MFL (which is meant to be authoritative and unique at country level) could provide an opportunity to articulate other data collection processes (e.g. event-specific projects such as COVID projects) in the platform, while ensuring the MFL is “authoritative and unique” across processes
Considering that HeRAMS (i.e. MFL + SM) may constitute the MFL
Challenges
•	Ability to add new HFs might have to be limited to the MFL project as we otherwise risk creating “orphan” health facilities. This raises the following challenges
o	Adding new HFs becomes significantly more complex if users of the event specific projects have to create new HFs in the regular project.
o	Users of project be might not have the appropriate access permissions nor would they know in which workspace the HF belongs
o	As the event specific project might only contain a small subset of the regular HeRAMS questionnaire which is not enough, how would they be able to complete the entire regular questionnaire

•	How are overlapping variables managed?
o	The event specific questionnaire might have overlapping questions. How can we avoid discrepancies of core variables (e.g. accessibility) between the two questionnaires?

**Comment by SamuelPetragallo** [comment]
We had a debriefing with @luna404 yesterday and compiled the following points/issues we still see:

Issue #1: inability to have project specific variables in the MFL (e.g. HF types)

Issue #2: inability to have versioning of MFL variables (e.g. HF or district names)

Because of #1 and #2 most variables would need to remain on the survey side, and hence the benefit of developing the HF layer is limited to the creation/management of a unique list of IDs platform side vs. a dynamically generated list of unique IDs from survey responses as we're currently doing

Though already an improvement, this does not tackle our primary objective of reinforcing the management of key variables of the MFL by applying specific validation and permissions (e.g. limit edit to certain users, etc.).

Would it then be possible to:
1. manage unique IDs on the platform
2. articulate 2 surveys: 1 for the MFL variables (e.g. type) and one for the “survey variables”, both with versioning, separate permission systems and with a set of relational rules (based on “update / validity date” and the fact that the MFL survey would have standard variables)

?

**Comment by SamMousa** [comment]
> Though already an improvement

I'd say let's go ahead with the identified MVP

**Comment by SamuelPetragallo** [comment]
Let's first get clarity on 

2. articulate 2 surveys: 1 for the MFL variables (e.g. type) and one for the “survey variables”, both with versioning, separate permission systems and with a set of relational rules (based on “update / validity date” and the fact that the MFL survey would have standard variables)

Or if that's not viable on any other option we have to actually address the initial need

**Comment by SamMousa** [comment]
First iteration of HF layer, we have very few fields:


- HF id (automated and readonly)
- workspace id (automated and readonly) 
- name (localizable)
- alternative name (localizable)

@SamuelPetragallo @luna404 this is what we discussed last time, correct?

**Comment by luna404** [comment]
Yes the variables are correct.

Regarding the workspace id, we will need a way to edit the workspace id of existing HFs.

If understand this correctly, there will be a one-to-one link between HFs and WSs. This means HFs are project specific and the idea of possible linking multiple projects to the same MHFL is definitely of the table.

**Comment by SamMousa** [comment]
This is how it is now right? Nobody mentioned anything about having a facility in multiple projects

**Comment by SamMousa** [comment]
We only discussed multiple surveys within a project, not multiple projects for a facility

**Comment by SamMousa** [comment]
This is a class diagram showing the entities in our domain: 
https://github.com/HeRAMS-WHO/herams-backend/blob/master/docs/HFLayer.png

This should aid in our discussion on how the relation and data modeling works.

**Comment by SamMousa** [comment]
- [ ] Add a code to HF, this is a free text field with no validation
- [ ] Title of HF must be unique unless it is inactive or deleted
- [ ] Add flags for deleted & inactive
- [ ] @luna404 will look into how cascading deletes (from project down) should work
- [ ] Import HF flow will use CSV import with column mapping, duplicate will cause the whole file to be rejected
- [ ] HFs will be soft deleted if they have responses, if they don't we can either hard delete or offer the user a choice

**Comment by SamMousa** [comment]
@luna404 Looking at the above requirements; what happens if I want to re-activate a facility but it has a duplicate name?
Should we look into not enforcing duplicate names, but instead offer guidance?
--> So if you have a name that is already in the list we make that visible so that you can verify that it is a different facility or something?

**Comment by matof-who** [comment]
We can close this ticket, what's discussed in here is covered by other issues
