### ISSUE TITLE
Develop system diagrams as requested by IMT

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#656]

**Comment by SamMousa** [comment]
https://github.com/HeRAMS-WHO/herams-backend/blob/master/docs/stack.md

**Comment by SamuelPetragallo** [comment]
Do you confirm I can  share with IMT?

**Comment by SamMousa** [comment]
Yeah, you can give them the link it should remain up to date, or alternatively send them just the image from that page.
