### ISSUE TITLE
Export form LS not working for Yemen

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#664]
Project 618734
https://ls.herams.org/admin/export/sa/exportresults/surveyid/618734

Exporting the full responses in Excel times out. This does not happen with other projects so I assume this is due to the size of this project. Any chance this could be fixed (easily)?

**Comment by SamMousa** [comment]
The export screen allows exporting in smaller batches; have you tried that?

**Comment by SamMousa** [comment]
Also, CSV export seems to work just fine... So there are 2 workarounds available.
