### ISSUE TITLE
Test failing when merging

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#675]
Just to summarize what I understand and tried

The error seem to be about the library xlswriter
It's downloaded but can't be found at the expected location

`Warning: PHP Startup: Unable to load dynamic library 'xlswriter' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20200930/xlswriter (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930/xlswriter: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20200930/xlswriter.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20200930/xlswriter.so: call_user_function_ex: symbol not found)) in Unknown on line 0
`
PHP 8 is used, the version as been published Dec  1 2020
I haven't seen any issues about xlswriter with php8

Usually when tests fail on staging 
- I pull the master branch and merge it with the branch I was working on
- I run those commands to update docker

1. docker-compose pull to pull any used images and docker-compose build to build any used images.
2. docker-compose down to remove all containers
3. Run the tests again

Should we now use PHP 8 ?

**Comment by SamMousa** [comment]
Fixed on master
