### ISSUE TITLE
Prevent dashboard elements from being split across pages

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#683]
When you export a dashboard, some elements are split across pages. Can this be fixed?

![image](https://user-images.githubusercontent.com/18245059/101337101-9234d180-387b-11eb-9b74-a7c1c5de4bf6.png)
https://herams-staging.org/project/30/pdf

**Comment by luna404** [comment]
@jeremiehelme this is for the next release

**Comment by luna404** [comment]
It's not cutting it off anymore, but it is still overlapping with the page header.

![image](https://user-images.githubusercontent.com/18245059/107334643-42f76100-6ab7-11eb-9736-70d5063bf189.png)

Also for subsequent page the header is overlapping with the blue line 

![image](https://user-images.githubusercontent.com/18245059/107334776-70440f00-6ab7-11eb-9243-b93c9b30ea08.png)

**Comment by SamMousa** [comment]
@jeremiehelme why did you use a table layout for the PDF view?

**Comment by luna404** [comment]
Response from Jeremie: "The layout for printing is really different depending on the browser. Embedding it in a table helps to have the same behavior everywhere."

**Comment by joester89** [comment]
@luna404 I've spent quite some time on this now. I managed to fix the overflowing of charts, but somehow broke the page breaks after each section. I added a sample of how it looks now.

I have no clue (yet) how to solve the page breaks. Could you take a look to the added pdf if this suffies?

[HeRAMS - Sudan.pdf](https://github.com/HeRAMS-WHO/herams-backend/files/6030079/HeRAMS.-.Sudan.pdf)

**Comment by luna404** [comment]
Was this example extracted from staging? The issue seems to depend a lot on the browser you're using. Your example looks much better, but when I go export another dashboard on staging using Chrome, it's a little messy and still splits some tables/maps. 

[HeRAMS - Ethiopia Tigray.pdf](https://github.com/HeRAMS-WHO/herams-backend/files/6035085/HeRAMS.-.Ethiopia.Tigray.pdf)

Side note, in your example, the icons in the header only export on the first page.

**Comment by joester89** [comment]
Sorry, I did not yet push it to staging. I just downloaded a report locally to show the status. I'll push it to staging in a few minutes.

I did not notice the problem with the icons in the header, I'll look in to that too.

**Comment by joester89** [comment]
The icons in the header do print in firefox...

There is somehow still some strange behavior every now and then, and it even differs between browsers. I hope the version that is on staging now is workable for now. I am a bit out of options how to "solve" the strange behavior.

**Comment by luna404** [comment]
I tried exporting a few different dashboards and I've also noticed some weird behaviour with some of the maps. Overall, I think the original issue has been fixed as much as is currently possible and we should not waste more time on this right now. I'm hoping we can do some more general overhaul/enhancements of the dashboards later this year and maybe we can further improve the export then.

**Comment by joester89** [comment]
I totally agree :)

**Comment by luna404** [comment]
Can we try the solution proposed by @SamMousa and render the pdfs using Chrome regardless of the browser the user is using. I check some of the dashboards and they seem to work well with Chrome.
