### ISSUE TITLE
Icon pack

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#684]
Here is the link to the icon pack
https://www.flaticon.com/packs/essential-4?word=1101937

I was looking for a pack with icons covering at least the one we already had, and with new icons if needed.
They are thinner, which is more elegant and closer to what Bruno had designed

### **Previous icons**

**Action icons**
The previous icons were intended to be used as buttons, without a label
![Capture d’écran 2020-12-07 à 17 13 20](https://user-images.githubusercontent.com/2345926/101375323-882cc600-38af-11eb-9f62-b4b0f1e42899.png)
They were a bit too small, too close, and some were very similar

**User menu icons**
In comparison, the ones in the user menu were a bit bigger and bolder, with a bigger area to click, which made them more easily identifiable as buttons
![Capture d’écran 2020-12-07 à 17 16 13](https://user-images.githubusercontent.com/2345926/101375645-efe31100-38af-11eb-9466-4042f4b26688.png)

### **New icons**

**User menu icons**
The **user menu icons** were already good, so I just updated them a bit
(There is two admin button to choose from) 
![Capture d’écran 2020-12-07 à 17 22 57](https://user-images.githubusercontent.com/2345926/101376548-0342ac00-38b1-11eb-9961-091dea5840fe.png)

**Action icons**
They are no longer used inside a table, instead they are at the top, on the right
To help identify them as buttons, I added a background and a label.
They help identify what can be done quickly
![Capture-d’écran-2020-12-07-à-17 23 49](https://user-images.githubusercontent.com/2345926/101381487-16f11100-38b7-11eb-91d6-5bfe3f653f1d.png)

Adding a label allow to reuse the same icon, for example to edit different types of elements
![edit](https://user-images.githubusercontent.com/2345926/101381471-122c5d00-38b7-11eb-9f21-7e64a3799a10.jpg)

**Comment by luna404** [comment]
Nice work, I vote for the current admin button.

For the share icon/button. The icon is definitely better than the previous one, but I'm wondering if we should rename it to "user management" in which case the icon might not be the most suitable. @SamuelPetragallo what do you think?
