### ISSUE TITLE
Admin pages: Project page

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#687]
- Tab headers should include stats (e.g. number of workspaces etc.)
- The "Survey administration" tab is missing
-  Can we harmonize the layout from one tab to another. Right now some tabs have a title others do not, some use paginations others are simple lists, etc.
- How will related pages be adjusted to the new layout? For example, if a user imports workspaces, will this remain in the "old" layout for now?
- Can we hide the tabs if a user has only access to the workspace tab? 
![image](https://user-images.githubusercontent.com/18245059/102113156-fa198800-3e38-11eb-9a59-6c0ec6a91b2c.png)

**Comment by jeremiehelme** [comment]
- Tab headers should include stats (e.g. number of workspaces etc.)
OK
- The "Survey administration" tab is missing
OK, with a the new permission set by sam
- Can we harmonize the layout from one tab to another. Right now some tabs have a title others do not, some use paginations others are simple lists, etc.
OK
- How will related pages be adjusted to the new layout? For example, if a user imports workspaces, will this remain in the "old" layout for now?
Yes, there is some screens left that I'll adapt
- Can we hide the tabs if a user has only access to the workspace tab?
OK

**Comment by luna404** [comment]
`Can we harmonize the layout from one tab to another. Right now some tabs have a title others do not, some use paginations others are simple lists, etc.`
Is this still in the cards or is it out of scope to harmonize the the tables/lists across the tabs?

`How will related pages be adjusted to the new layout? For example, if a user imports workspaces, will this remain in the "old" layout for now?
Yes, there is some screens left that I'll adapt`
Here's a list of missing pages that I stumbled over while testing today.
-	https://herams-staging.org/project/create
-	https://herams-staging.org/admin/share
-	https://herams-staging.org/user/index
-	https://herams-staging.org/page/create?project_id=34
-	https://herams-staging.org/project/34/import-dashboard
-	https://herams-staging.org/workspace/4893/share
-	https://herams-staging.org/workspace/4893/update
-	https://herams-staging.org/workspace/4893/limesurvey

**Comment by jeremiehelme** [comment]
Thanks Caroline for the testing,

All pages have been converted now

I create a separate issue for harmonizing the content. I tried to keep the same structure for the content, but there is still improvements to do

**Comment by luna404** [comment]
Looks like I forgot one page. 

https://herams-staging.org/project/40/export

**Comment by luna404** [comment]
`I create a separate issue for harmonizing the content. I tried to keep the same structure for the content, but there is still improvements to do`
That's fine, we can address this further at a later stage.

**Comment by luna404** [comment]
Sorry one more...
https://herams-staging.org/user/favorites

**Comment by jeremiehelme** [comment]
I think the last issue was this page not having the correct layout, it is fixed now
https://herams-staging.org/project/40/export

**Comment by SamMousa** [comment]
All pages have tabs now, closing this. Create new specific issues if you find any errors.
