### ISSUE TITLE
Admin pages: workspaces tab

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#688]
-	Sort icon in column headers is not displaying correctly
-	If you sort by facility count or response count the title splits across two rows
-	Could we add the ability to sort by the favorites column and have this as default?
-	I assume the action column is still there because you haven’t done the workspace page yet, correct?
-	Can we add the "showing x - y out of z workspaces" like it is done on the dashboard tab?
- Can we change the date format of the "last update" column into a more human readable format. (e.g. update x min ago, updated x days ago, etc.)
- Remove "Count" from the column headers (e.g. change `Facility count` to `Health facilities`)
- Add title "Workspaces"

**Comment by luna404** [comment]
- None of the buttons is currently working

**Comment by jeremiehelme** [comment]
I created separate issues for these points 
- Could we add the ability to sort by the favorites column and have this as default?
- Can we change the date format of the "last update" column into a more human readable format. (e.g. update x min ago, updated x days ago, etc.)

The others should be good now
