### ISSUE TITLE
Admin pages: Dashboard

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#689]
- Change tab name to `Dashboard settings`	
- Add header `Dashboard pages`
-	Change order of buttons to create, import, export. 
-	Export and import are opposite functions and should not have the same color 
- Subpages need to be updated to new layout.

**Comment by luna404** [comment]
-	Permission error: Tab is not appearing if user is granted permissions. 
-	Project dashboard button is not working
-	Delete confirmation appears on the button. This should remain a pop-up (see prod for comparison)
-	Edit element icon is missing (https://herams-staging.org/page/351/update). 
-	Create elements buttons are not working
-	Rename "Pages" to "Dashboard pages" in breadcrumbs

**Comment by SamMousa** [comment]
Adding the header would make it inconsistent, currently we don't show a header for the block if it is the only block.
It makes more sense to rename the tab to `dashboard pages` if that makes it more usable.

So for example in project settings, we have 2 blocks so we show headers:
![image](https://user-images.githubusercontent.com/547021/107334541-23f8cf00-6ab7-11eb-9532-040afa277efd.png)

But in workspaces we have no header  since it is just one block:
![image](https://user-images.githubusercontent.com/547021/107334599-32df8180-6ab7-11eb-8047-60790dc88e53.png)

**Comment by luna404** [comment]
`Adding the header would make it inconsistent, currently we don't show a header for the block if it is the only block.` 
Why are we not just always showing a header? One could argue that only showing a header if it's more than one content block is also inconsistent. If it's to avoid "wasting" space than I'm fine with it.

If we don't add titles can we make the headers in the tables more explicit? Meaning instead of calling in the column `Title` we could call it `Dashboard pages`. This would apply to both the dashboard pages and the workspace table.
![image](https://user-images.githubusercontent.com/18245059/107340970-b650a100-6abe-11eb-8700-cf7ff647242d.png)

**Comment by SamMousa** [comment]
> Why are we not just always showing a header?

This was discussed a few weeks ago, and you agreed on not showing it in case we have 1 block.

https://github.com/HeRAMS-WHO/herams-backend/issues/760

**Comment by SamMousa** [comment]
>  One could argue that only showing a header if it's more than one content block is also inconsistent. 

No, consistency means is about rules vs exceptions. It doesn't mean the rule has to be "everything is like X".

We could have a caption in every table that shows what the table is listing, but usually it follows almost directly from the tab title.

**Comment by joester89** [comment]
I can't discover what remains to be done in this issue. Can anyone either list it or close the issue @SamMousa @luna404?
