### ISSUE TITLE
Admin pages: Share tab

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#690]
-	Rename tab to `user management` or `users`
-	Change `Add permissions` to `Add new user`
-	Change `View user permissions` to `View current users`
-	"Showing x-y out z items" is not very useful if there is only one page. Either remove or add pagination
-	Remove text labels of the permission slider and change colors to grey if off and blue if on. (see example below)
![image](https://user-images.githubusercontent.com/18245059/102114192-37324a00-3e3a-11eb-98aa-6ab2e3363a5d.png)

- Could the table be made sortable/filterable?
-	Change order of permissions. It should be:
    1. View dashboard
    2.	Edit data
    3.	Download data
    4.	Manage workspaces
    5.	Manage users
    6.	Configure dashboard
    7.	Edit settings
    8.	Grant admin permissions

**Comment by jeremiehelme** [comment]
- Rename tab to user management or users
OK
- Change Add permissions to Add new user
OK
- Change View user permissions to View current users
OK
- Change colors to grey if off and blue if on
OK

**Comment by luna404** [comment]
- Can you remove the labels (allowed/denied) as well? 

- The account of users in the tab is wrong. If you look at Yemen for example it shows 308 but there are only 2 users

**Comment by luna404** [comment]
Most importantly, the permissions to the tab is not working. A user granted permission to share doesn't see the tab. 
(PS same issue also exists for other tabs)

**Comment by jeremiehelme** [comment]
Created another issue about the table (labels, ordering...)

**Comment by jeremiehelme** [comment]
"Most importantly, the permissions to the tab is not working. A user granted permission to share doesn't see the tab."
Maybe this one is to double check ?
I use PERMISSION_SHARE, to me it's correct

**Comment by SamMousa** [comment]
Permissions should now work correctly

**Comment by luna404** [comment]
There's something wrong with the permissions. Regardless of what workspace permission is assigned to the user, they always get access to the response picker. But the tab name correctly displays the assigned permission.

In the example below, the user was assigned permission to export data only.

![image](https://user-images.githubusercontent.com/18245059/108036665-ce816c80-7038-11eb-80ed-28921ff900f5.png)

**Comment by SamMousa** [comment]
This is something you literally agreed on here: https://github.com/HeRAMS-WHO/herams-backend/issues/771

**Comment by joester89** [comment]
@luna404, could you check if the tab problem still arises?

I first tried to reproduce it locally, gave a user only download data permission on a project and I saw both tabs.
Next I logged in with the HeRAMS Tester on staging and went to https://herams-staging.org/workspace/5386/limesurvey and saw both tabs...
