### ISSUE TITLE
Token created in HeRAMS not valid

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#692]
If a user creates a new token in HeRAMS, the token is not valid. The date `valid from` is correctly set to today, but it seems  `date valid from` needs to be smaller than today rather than smaller/equal to today.

**Comment by SamMousa** [comment]
Can you check in LS for such a token to see if the valid from includes a time?
As far as I can tell the time is set to "now" and thus it could be a timezone difference between APP and LS.

Let me know.

**Comment by luna404** [comment]
Yes, workspaces created in HeRAMs are saved wit UTC time in LS.

If I change the timestamp to UTC -2h it works.

**Comment by SamMousa** [comment]
Updating the workspace properties (even without changes) should now always remove the validFrom date. (Also for new tokens it is not set at all)
