### ISSUE TITLE
User permission to access Survey administration

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#695]
The tab "Backend Administration" is accessible to all users with the PERMISSION_ADMIN for the project.
Only users which are given permission should be able to see it.
Can we create a permission for this tab, to allow to choose which user can access it ?

@SamMousa should I just create the permission in the Permission class, and display it in the user permission list, or is there more steps ?

![Capture d’écran 2020-12-18 à 14 46 17](https://user-images.githubusercontent.com/2345926/102621721-466a0e00-4140-11eb-988c-22a5a550caef.png)

Thanks,

**Comment by SamMousa** [comment]
@luna404 I thought we discussed a separate global LS Permission?
Because users need to be manually created on the LS side they are not project scoped.

**Comment by luna404** [comment]
I thought we create a "dummy" permissions which will make the tab visible at the project level while the actual permissions will continue to be managed in LS.

If we create it at the global level, where would the link to LS be?

**Comment by SamMousa** [comment]
I have added it to the project level, give it a try.

**Comment by luna404** [comment]
Can we restrict the ability of granting this permission to global admins only?

**Comment by SamMousa** [comment]
Confirmed that this works correclty.
