### ISSUE TITLE
Missing variable database/username

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#696]
I get an error saying that SECRET_database/username is missing

- It's defined in docker-compose.yml and has the value of DB_USER, 
- DB_USER is defined in the .env file, so I don't understand why it doesn't find it

Last thing I did was to pull from the master branch, and update Docker Desktop (3.0.2), if it can be related
It happens when I try to apply the migrations `docker-compose run --rm cli migrate`, or when I visit the site

```
Warning: assert(): assert(isset($env) && $env instanceof \prime\components\KubernetesSecretEnvironment) failed in /project/protected/config/common.php on line 23
Yii Migration Tool (based on Yii v2.0.39.3)

Exception 'yii\base\InvalidConfigException' with message 'Missing variable SECRET_database/username'

in /project/protected/components/InsecureSecretEnvironment.php:30
```

**Comment by SamMousa** [comment]
Will fix it in a min

**Comment by SamMousa** [comment]
Try pulling in master now

**Comment by jeremiehelme** [comment]
Thanks !

`docker-compose run --rm cli migrate` worked
`docker-compose up` works as well
`docker-compose up serve` seems that it doesn't exists anymore ?

I still have the same error when accessing the website though

**Comment by jeremiehelme** [comment]
There is some warnings when running the tests
<img width="489" alt="Capture d’écran 2020-12-21 à 11 09 37" src="https://user-images.githubusercontent.com/2345926/102765569-13608e00-437d-11eb-9a3a-f1c5f412192a.png">

**Comment by SamMousa** [comment]
Always run `docker-compose down` after issues like these, otherwise you're just reusing the old containers.

It's been changes to use the same stack as we use in prod, so use `docker-compose up -d nginx`. (You can easily inspect the yaml file to see which services are available)

**Comment by SamMousa** [comment]
Try updating your containers:
```
docker-compose down # Always shut everything down
docker-compose pull # Pull all images for services that use images
docker-compose build # Build all images for services that use dockerfiles

```

**Comment by jeremiehelme** [comment]
I did docker-compose down and pull

Build produce this error

```
docker-compose build
WARNING: The COOKIE_VALIDATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The RESPONSE_SUBMISSION_KEY variable is not set. Defaulting to a blank string.
devdb uses an image, skipping
testdb uses an image, skipping
phpmyadmin uses an image, skipping
mailcatcher uses an image, skipping
nginx uses an image, skipping
Building testcli
Step 1/8 : FROM alpine:edge
 ---> 003bcf045729
Step 2/8 : RUN apk add --update --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing   git   wait4ports   jq   npm   php7-ctype   php7-curl   php7-dom   php7-fpm   php7-gd   php7-intl   php7-json   php7-mbstring   php7-pdo_mysql   php7-phar   php7-posix   php7-session   php7-tokenizer   php7-xml   php7-simplexml   php7-xmlwriter   php7-zip   php7-pecl-xlswriter   php7-pecl-pcov   --
 ---> Using cache
 ---> 7fcfa6619953
Step 3/8 : RUN EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)" &&     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&     ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" &&     if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then exit 1; fi &&     php composer-setup.php --filename composer --install-dir /bin &&     php -r "unlink('composer-setup.php');"
 ---> Running in f50e2f45bd09
**wget: bad address 'composer.github.io'**
ERROR: Service 'testcli' failed to build : The command '/bin/sh -c EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)" &&     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&     ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" &&     if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then exit 1; fi &&     php composer-setup.php --filename composer --install-dir /bin &&     php -r "unlink('composer-setup.php');"' returned a non-zero code: 1
```


https://composer.github.io/installer.sig url is valid
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" works
ACTUAL_CHECKSUM has a value
Seems that wget is the problem

**Comment by SamMousa** [comment]
Just retry it.. it says in your comment "bad address" ... 
It is probably some intermittent network issue

**Comment by jeremiehelme** [comment]
No luck, it always fail with bad address
Seems related to github.io
I copied the installer.sig to my server and used the url instead and it works 
(https://jeremiehelme.fr/ext/composer/installer.sig)

It doesn't change the result, the tests still produce warnings and I have the same error when accessing the site

**Comment by SamMousa** [comment]
It works for me, this one you'll have to figure out for yourself

**Comment by SamMousa** [comment]
Closing this since you mentioned it is operational since this morning
