### ISSUE TITLE
Access to LS is broken

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#699]
It's not possible to login to LS at the moment. I tried both, through HeRAMS (backend administration) and using the direct link (https://ls.herams.org/admin/authentication/sa/login)

![image](https://user-images.githubusercontent.com/18245059/103138319-906b6a80-46d1-11eb-913a-2c4cc946cdc4.png)

**Comment by SamMousa** [comment]
Will fix it tonight or tomorrow morning

**Comment by luna404** [comment]
I told them they might have to wait until Monday, so take you're time.

**Comment by SamMousa** [comment]
Fixed.
