### ISSUE TITLE
Login page: Buttons are falling outside of the pop-up

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#703]
The `Log-in` and `Register` buttons are outside of the frame.

![image](https://user-images.githubusercontent.com/18245059/103344416-d25c2e00-4a8e-11eb-99de-feabccdebee3.png)

**Comment by SamMousa** [comment]
I'm aware of this, working on some of the templating issues, we need to clean up our views and move most if not all wrapper divs to the layouts @jeremiehelme.

**Comment by luna404** [comment]
The logo is missing and the white frame should be removed.
