### ISSUE TITLE
Weblate not accessible

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#708]
The link for weblate is not working.

https://weblate.herams-staging.org/

**Comment by luna404** [comment]
The link works, but I can't log in. Neither of my accounts is working anymore and the password reset email is not coming through.

**Comment by SamMousa** [comment]
Try again, I think it just blocked the IP, if it doesn't work please include the exact error message.

**Comment by comradekingu** [comment]
I tried registering, and I am not getting the e-mail. Will report back if I do. Got the regular "Look in your Inbox" message. How is it set up?

**Comment by SamMousa** [comment]
Mailing has not yet been set up for weblate.

**Comment by luna404** [comment]
Does this mean we no longer have the ability to invite users or reset passwords?

**Comment by SamMousa** [comment]
Until we resolve that, we don't. 
Will need to use an email sending service (like sendgrid) for transaction emails. 
This is something that we need to discuss with @SamuelPetragallo

**Comment by SamMousa** [comment]
Mailing from weblate works again.
