### ISSUE TITLE
Support in the manual syncing of all the workspaces of HeRAMS PHL (ID=23)

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#709]
Hi @SamMousa, for support in the manual syncing of all the workspaces of HeRAMS PHL (ID=23). Thanks! (Urgency is HIGH because data collection will start on Thursday 7 January 2021. There will also be trainings tomorrow)

**Comment by SamMousa** [comment]
It's busy now.
