### ISSUE TITLE
Error when trying to merge a PR via github

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#713]
I get this error when I try to merge a PR

<img width="1085" alt="Capture d’écran 2021-01-05 à 18 00 00" src="https://user-images.githubusercontent.com/2345926/103675241-fed8e400-4f7f-11eb-8742-bd7e20110f8b.png">

The recommended command is present in build.yml in the github workflows, but doesn't seem to be executed
- run: docker network create devproxy

<img width="1090" alt="Capture d’écran 2021-01-05 à 18 23 56" src="https://user-images.githubusercontent.com/2345926/103677920-3301d400-4f83-11eb-8ce6-0352b2701c28.png">

**Comment by SamMousa** [comment]
Check the yaml  used for releases, that version works, copy commands from there to the prs yaml

**Comment by jeremiehelme** [comment]
Thanks,
I copied 
`- run: docker network create devproxy`
to the prs yaml file, and it worked
