### ISSUE TITLE
Error refreshing workspaces

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#724]
https://herams-staging.org/workspace/5530/refresh

![image](https://user-images.githubusercontent.com/18245059/103772969-a4489200-502a-11eb-88ce-c91b45e9fdcf.png)

**Comment by SamMousa** [comment]
Fixed in https://github.com/HeRAMS-WHO/herams-backend/commit/3dc42468bd0d7f94bf097c809f50caa42d80a232

**Comment by luna404** [comment]
@SamMousa you seem to have removed the refresh button so it obviously can't give an error anymore.

Are we keeping a refresh button at the workspace level or will we just have the project level refresh (#761)?

**Comment by SamMousa** [comment]
The button was moved to settings, as agreed
