### ISSUE TITLE
Admin pages: Edit dashboard element

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#735]
There seems to be a little issue with the layout of the page. The color categories should be in two columns with the color right aligned (see pic from prod below)

![image](https://user-images.githubusercontent.com/18245059/103868244-ea543300-50c8-11eb-8b01-0bf464426a53.png)

Expected layout
![image](https://user-images.githubusercontent.com/18245059/103868475-3b642700-50c9-11eb-9825-d527613bf12f.png)

**Comment by jeremiehelme** [comment]
Fixed, but like the other form, I'll have to clean it later

**Comment by luna404** [comment]
Content not yet in sections error
https://herams-staging.org/page/351/update

**Comment by SamMousa** [comment]
> Content not yet in sections error
> https://herams-staging.org/page/351/update

This is fixed now, but also it wasn't related to this issue...
