### ISSUE TITLE
Admin pages: Download

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#736]
- The advanced settings used to be hidden by default (see screenshot from prod below). If this is difficult to recreate, I would suggest to just remove the "advance settings" label. 
- There seems to be some CSS missing on the page. There no spaces between the text and buttons
 
![image](https://user-images.githubusercontent.com/18245059/103869619-db6e8000-50ca-11eb-8b29-99ed9c133249.png)

**Comment by luna404** [comment]
Same solution should be used for both pages download pages
https://herams-staging.org/project/40/export
https://herams-staging.org/workspace/6468/export

**Comment by jeremiehelme** [comment]
I fixed it, but I'll have to do another pass on it later. It should be properly designed according to the new rules

**Comment by luna404** [comment]
The collapse is only working for the advanced settings but not the settings section

**Comment by luna404** [comment]
It's working, but the styling should be improved before we release this.

**Comment by jeremiehelme** [comment]
I agree, I'll need some time to design the component then

**Comment by SamMousa** [comment]
Remove collapsible

**Comment by luna404** [comment]
Project level data export tab still has a big red square.

https://herams-staging.org/project/40/export

**Comment by SamMousa** [comment]
Fixed
