### ISSUE TITLE
Share permission table

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#737]
Remove text labels of the permission slider and change colors to grey if off and blue if on. (see example below)
Could the table be made sortable/filterable?

Change order of permissions. It should be:
- View dashboard
- Edit data
- Download data
- Manage workspaces
- Manage users
- Configure dashboard
- Edit settings
- Grant admin permissions

**Comment by joester89** [comment]
Can be tested in https://feature-349-request-access.herams-staging.org

**Comment by luna404** [comment]
Can we move the permission "register new HFs" next to the "edit data" permission? Sorry, I created this issue before we had the "register new HF" permission.

**Comment by joester89** [comment]
@luna404 the testing environment is working again so it can be tested :) (https://feature-349-request-access.herams-staging.org)

**Comment by luna404** [comment]
Back to my comment above then, can we change the order of the permissions so that `register new HFs` is next to `edit data`?

**Comment by joester89** [comment]
Isn't this already the case 🙈 ?
![image](https://user-images.githubusercontent.com/9624366/124557643-05b2b780-de3a-11eb-9fb0-ba760f67b220.png)

**Comment by joester89** [comment]
Ahh @luna404 you meant at the Workspace Share page, this is now fixed as well.

**Comment by luna404** [comment]
I meant both, the project and workspace sharing pages. 

The order is fine at the workspace level but on the project level `Edit data` and `Register a new HF` should be next to each other. This is not the case in your screenshot above. 
If you look at the link below, the order should be 
- View dashboard
- Edit data
- Register new HF
- Export data
- ....
https://feature-349-request-access.herams-staging.org/project/10/share
