### ISSUE TITLE
User count in project is wrong

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#738]
The account of users in the project Users tab is wrong. If you look at Yemen for example it shows 308 but there are only 2 users

**Comment by luna404** [comment]
If this is difficult to resolve, I suggest to simply remove the count of users for now. We can fix this at a later stage.

**Comment by SamMousa** [comment]
Contributors are not the same as users. 
Contributors is defined as the minimum of count of workspaces and count of users with explicit permissions.
This is based on the business assumption that every workspace is managed by a different individual.

**Comment by jeremiehelme** [comment]
Removed the count for now (In project and workspaces to be consistent)

**Comment by luna404** [comment]
As we do still want to display the user count, this is just a temporary solution and the issue itself has not yet been addressed.

**Comment by SamMousa** [comment]
If we want to show a number here should we not show the number of explicit shares at the level?
Since we showing everyone who has any kind of access is weird.
If the user then opens the tab with title Users (15) he might only see 5 rows of other permissions are inherited.

Agreed?

**Comment by luna404** [comment]
It should display the number of users having been granted any specific permission at that level. So in your example it should show 5.
