### ISSUE TITLE
Admin pages: Backend administration

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#739]
- The full screen button is not working.
- If you click the backend administration tab, the user is prompted to login again. Is this just staging issue or is this the expected behavior?

**Comment by jeremiehelme** [comment]
ok for the full screen button

For the backend administration tab, it's not the expected behavior, it should be like on prod
I'll look into it

**Comment by jeremiehelme** [comment]
@SamMousa Do you have an idea on this one ?
"If you click the backend administration tab, the user is prompted to login again. Is this just staging issue or is this the expected behavior?"

https://herams-staging.org/admin/limesurvey

**Comment by SamMousa** [comment]
Staging issue. Full screen is a separate issue

**Comment by jeremiehelme** [comment]
Full screen is fixed

**Comment by jeremiehelme** [comment]
One precision 
Now that the backend administration is accessible at the project level, it has two routes 
https://herams-staging.org/admin/limesurvey
https://herams-staging.org/project/28/limesurvey

**Comment by luna404** [comment]
There's an error when you try accessing the backend administration
![image](https://user-images.githubusercontent.com/18245059/106263033-22601900-6224-11eb-9b0c-ea2e7701c458.png)

**Comment by SamMousa** [comment]
Fixed
