### ISSUE TITLE
Admin pages: Breadcrumbs workspace link not working

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#749]
There is a mistake in the bread crumbs url for workspaces. If you click on the workspace name in the breadcrumbs the url uses workspace**s** instead of workspace

https://herams-staging.org/workspaces/6471/limesurvey
should be
https://herams-staging.org/workspace/6471/limesurvey

![image](https://user-images.githubusercontent.com/18245059/103898214-e63e0a80-50f4-11eb-8ec2-f5ecb9702be0.png)

**Comment by SamMousa** [comment]
This works now, but for lots of tabs the breadcrumbs are inconsistent (#773)
