### ISSUE TITLE
Error: CSRF token could not be verified

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#753]
It's not possible to advance to the next page of a survey on staging. 

![image](https://user-images.githubusercontent.com/18245059/104002722-bef14700-51a1-11eb-8820-976108a8c3f8.png)

**Comment by SamMousa** [comment]
That could be due to third party tokens, it depends on your browser.
There is nothing we can do about it since staging is on a different domain.

**Comment by luna404** [comment]
As long we are sure that this is just an issue on staging and won't reproduce on prod once we release, we can live with the error.
