### ISSUE TITLE
Project level sync function

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#761]

**Comment by SamMousa** [comment]
- Checkboxes for workspaces
- Check / uncheck all
- Sync selected workspaces (synchronously)

**Comment by SamMousa** [comment]
@luna404 you can test here: https://herams-staging.org/project/[[project-id]]/sync-workspaces

Will add navigation to it soon, but that's unrelated to the functionality.

**Comment by luna404** [comment]
It works fine but it seems to not include all workspaces of a project.

If you look at the page for Yemen https://herams-staging.org/project/34/sync-workspaces it shows less than 100 workspaces but according to the workspace page there should be 368 (https://herams-staging.org/project/34/workspaces?sort=latestUpdate)

**Comment by SamMousa** [comment]
Did you see the horizontal scrollbar?

**Comment by luna404** [comment]
I don't see any scrollbars 

![image](https://user-images.githubusercontent.com/18245059/109025981-878e1980-76bf-11eb-9418-a4553a5e12f5.png)

**Comment by SamMousa** [comment]
Can you give this another shot? I am  seeing the full list and can scroll down properly. Could be a CSS cache issue...

**Comment by SamMousa** [comment]
Have also added a feature to resume sync if 1 of the requests fail for any reason.

**Comment by luna404** [comment]
The resume didn't work for me, I had to manually restart the sync. Other than it's awesome.

**Comment by SamMousa** [comment]
How did you test the resume?
If a sync fails the line turns red and you can click the `>>` in the line to continue. 
What did you try?

**Comment by luna404** [comment]
I thought it resumes automatically after a given time. Didn't realize I had to use the `>>` .  Works as designed.
