### ISSUE TITLE
Response picker: grey background returns upon changing the language

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#769]
When you switch the language in the response picker, the grey background is coming back. 

https://herams-staging.org/workspace/6084/limesurvey

When you first load the page it looks like this:
![image](https://user-images.githubusercontent.com/18245059/106015505-d6e02a80-60be-11eb-9580-dcc89d33cd75.png)

After switching the language the background is back to grey
![image](https://user-images.githubusercontent.com/18245059/106015710-08f18c80-60bf-11eb-8dfd-ddd76bb6b6ec.png)

**Comment by SamMousa** [comment]
Fixed
