### ISSUE TITLE
Breadcrumbs change depending on the tab

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#773]
The breadcrumb structure is not the same for each tab

For workspaces, dashboard settings and project settings it is
`Administration > Yemen`

For export data it is:
`Administration > Yemen > Export data from project Yemen`

For users and backend administration it is:
`Administration > Yemen > Yemen`

Also, If the list of projects is `Administration > Projects`, shouldn't project themselves be  `Administration > Projects > Yemen`

Similar inconsistencies also exists at the workspace level.

**Comment by SamMousa** [comment]
I'm not sure what the consensus is on your last point...

But you are right about some of the inconsistencies, will have a look

**Comment by luna404** [comment]
I would keep it simple and have just one breadcrumb for all tabs. So `Administration > project` for project level and  `Administration > project > workspace` for workspaces

**Comment by SamMousa** [comment]
We keep going around in circles. The breadcrumbs need to end in the page title otherwise it is just a partial path.

**Comment by SamMousa** [comment]
https://github.com/HeRAMS-WHO/herams-backend/blob/master/docs/ui/Breadcrumbs.md

Let's discuss the underlying concepts separate from the implementation. After we agree on the concepts we can then make sure the implementation conforms to it.

**Comment by luna404** [comment]
Breadcrumbs for Favorites also needs to be corrected 

![image](https://user-images.githubusercontent.com/18245059/107340093-a4223300-6abd-11eb-9863-6fc614293327.png)
