### ISSUE TITLE
Exporting individual charts

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#779]
Does our currently charting library support exports of charts as highcharts used to?

https://a----.github.io/highcharts-export-clientside/

Would be very useful for users to export individual charts to be reused in reports, presentations, etc.

(Same question goes for maps)

**Comment by SamMousa** [comment]
ChartJS renders on a Canvas and we can easily export those to images on modern browsers.

**Comment by SamMousa** [comment]
Add reference / watermark to exported image
