### ISSUE TITLE
Dashboard element heights vary

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#783]
If you look at screenshot below, maps are always set to a height of 2 but the actual height differs. Same issue with the table. Also if you add more than 2 maps on a page they won't all load fully.

![image](https://user-images.githubusercontent.com/18245059/107844657-9e865f00-6dd5-11eb-981a-a4bd0ba6223a.png)

**Comment by SamMousa** [comment]
Please add a link to the project / dashboard pages where this happens.

**Comment by luna404** [comment]
https://herams.org/project/46?parent_id=454&page_id=458

I increased the height of the last map to 3 to match the heights of the others (which are all 2) https://herams.org/element/1668/update

I had to remove the tables for now, this is currently the most looked at dashboard we have :)

**Comment by luna404** [comment]
@joester89 this is still an issue. Have a look here (https://herams-staging.org/project/46?page_id=428)
All maps have a height of 2 but the last one is smaller than the others. 

![image](https://user-images.githubusercontent.com/18245059/108694896-f1f85b80-74ff-11eb-977c-7d7833179231.png)

**Comment by joester89** [comment]
@luna404, this is happening because the chart "Stabilization centre for SAM" has a height of 2 🙈

**Comment by luna404** [comment]
Fair enough, the chart should not have a height of 2 in this case. But it's still bizarre that the chart height influences the map height. If I change the heights of the charts to one, the map also changes the height even though it still has a height of 2.  

![image](https://user-images.githubusercontent.com/18245059/108817270-e8cac580-75b7-11eb-9d30-af1e6046a0e5.png)

If you look at other pages, we don't have this issue (e.g. https://herams-staging.org/project/46?page_id=419)

**Comment by luna404** [comment]
Same issue also for tables. In the example below both map and table have a height of 2 

![image](https://user-images.githubusercontent.com/18245059/108817861-cf764900-75b8-11eb-9b8f-6244c69e58dc.png)
https://herams-staging.org/project/46?page_id=428

Here's an example with fewer elements on a page where the table renders correctly.
https://herams-staging.org/project/46?page_id=418

**Comment by joester89** [comment]
New attempt haha

**Comment by luna404** [comment]
Sorry, I'm a pain with this one, but if you check  out the table and map here, they still don't have the correct height (https://herams-staging.org/project/46?parent_id=426&page_id=428) [elements 1543 and 1567]

Same with the map (Post-exposure prophylaxis) here (https://herams-staging.org/project/46?page_id=429&parent_id=426, element 1543) It should have the same height as previous maps regardless of the number and size of the charts next to it.

**Comment by joester89** [comment]
I am not getting what is wrong... This is what I see:

1st example:
![image](https://user-images.githubusercontent.com/9624366/108838915-9ea40d00-75d4-11eb-96f9-66d84dd66acf.png)

2nd example:
![image](https://user-images.githubusercontent.com/9624366/108838878-8df39700-75d4-11eb-9c32-4a8583fb3bbb.png)

**Comment by luna404** [comment]
Looks like we don't get the same. This is what I get

![image](https://user-images.githubusercontent.com/18245059/108839329-3d306e00-75d5-11eb-8a84-54fb1b2f81b2.png)

**Comment by joester89** [comment]
Could you try a `Shift + F5` (force refresh)?

There were only some minor css changes and it could be that the browser caches the css file.

**Comment by luna404** [comment]
I cleared my cache, this solved it. Sorry, I should this more often...

**Comment by joester89** [comment]
No problem :)

**Comment by luna404** [comment]
We shouldn't close this issue as this is a proper issue on Prod.

**Comment by joester89** [comment]
Yes, discussed it with Sam. If you tested it on staging and we release it to production it should give the same result. Thats why we close them. You agree with closing?

**Comment by luna404** [comment]
How do you know what is in the milestone if all issues are closed before they are being released? I was under the assumption issues are closed if it's a staging issue only or once they were released.

**Comment by joester89** [comment]
Within the milestone page (https://github.com/HeRAMS-WHO/herams-backend/milestone/6) you can click the `closed` button in the header of the issue link that shows all closed issues in the milestone (https://github.com/HeRAMS-WHO/herams-backend/milestone/6?closed=1) ;)

**Comment by luna404** [comment]
Thanks, I'll close the issue then.
