### ISSUE TITLE
Dashboard - show expected service level in chart legend

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#784]
We need a way to include the level at which services are expected for chart/maps depicting individual services.  I currently see three option how we could achieve this

1. Add the level to the question title in LS: I don't think this is a long term solution as it will make the question titels unnecessarily long. 
2. Manually overwrite the title: Other then being extremely time consuming, this wouldn't work for maps and will pose an issue once we have the multi-language capability implemented. 
3. Adding a separate field where expected service levels can be selected. This would be my preferred option.

**Comment by SamMousa** [comment]
This should really be solved in the survey engine. Essentially for every HF in a project you'll need to answer this separately, right?

One thing that we could do when we move to SurveyJS is make some questions admin only, but still this is a wider discussion.
@SamuelPetragallo should be included in it as well..

This issue has been discussed several times and is hard to solve:

- Is it always known in advance for every HF what the expected service level is?
- Is it dependent on HF type (historically there has been a lot of discussion and this would make it very complex and still project dependent)
- Can it change over time? If a wing of my HF has flooded and it has been decided that we're not going to rebuild it, from that point on the expected service level essentially changes...


Take into account that I haven't fully thought this out.. It seems to me that the expected service level is a datapoint just as much as the current datapoint. It can change in both directions as can the real service level. 
Alternatively if the expected service level of a service changes it might conceptually become a new HF, this is always muddy terrain...

We used to have an answer that read `not normally provided` which essentially indicated that the expected service level was `none`..  Could you elaborate a bit more on why this is needed and maybe add some examples of how you'd use that in charts?

**Comment by luna404** [comment]
`Could you elaborate a bit more on why this is needed and maybe add some examples of how you'd use that in charts?` 
We have to take into account that users accessing the dashboard might be less familiar with our use of "not normally provided".  Also if you look at the Tigray dashboard  (https://herams.org/project/46?parent_id=454&page_id=458) where we created charts for individual services, it's impossible to know at which level this service is expected and I highly doubt any HeRAMS user has memorized the service checklist to know this on the fly. 

`Is it always known in advance for every HF what the expected service level is?` - Yes 
`Is it dependent on HF type (historically there has been a lot of discussion and this would make it very complex and still project dependent)` 
Yes but we're kinda ignoring this at the moment as we don't apply any conditioning. 
`Can it change over time? If a wing of my HF has flooded and it has been decided that we're not going to rebuild it, from that point on the expected service level essentially changes...`
Theoretically yes, but if it does I would suggest we create a new question. 

`This should really be solved in the survey engine. Essentially for every HF in a project you'll need to answer this separately, right?`  
For each HF we need to define whether a service should be provided. However, the expected service levels are not tight to the HF but the question itself. For example, MUAC screening will always be a community level service. Thus, all HF providing community level services should provide this service.
