### ISSUE TITLE
Project settings: edit permission setting

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#785]
todo

**Comment by SamMousa** [comment]
You can now enable or disable the setting in the project settings tab.
![image](https://user-images.githubusercontent.com/547021/109475777-65591a80-7a76-11eb-980b-6445410f66b8.png)


Furthermore on the workspace and project level there is a new permission:
![image](https://user-images.githubusercontent.com/547021/109475889-8a4d8d80-7a76-11eb-8f97-017a56599b3c.png)

**Comment by luna404** [comment]
The permission to register health facilities is visible regardless of whether the permission to create is included in the edit permission. Is this is on purpose?

**Comment by SamMousa** [comment]
Yes, this was actually previously discussed as well.
The explicit granting of permissions wouldn't be affected. If you ever wanted to change the setting to not include, you could do this without interruption of service by first giving the explicit permission and only then flipping the switch.
