### ISSUE TITLE
Project dashboards to pdf: print a full report

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#8]
Allow users pdf-print a report that mimics all the dashboard pages (incl. a list of the filters applied, etc.). Discuss with Bruno

**Comment by SamMousa** [comment]
Needs #332 

Need to find a good way to render the PDF; could use something like an HTML to PDF tool that supports JS. (PhantomJS?)

**Comment by SamMousa** [comment]
First step would be to create a single page version of the dashboard.

**Comment by jeremiehelme** [comment]
I've added a layout without the menus, taking the whole width, and a 'print' action to the project controller :

![Capture d’écran 2020-03-05 à 15 51 40](https://user-images.githubusercontent.com/2345926/75993151-58542a80-5ef9-11ea-8e86-2f0afc8b6362.png)

I can use a print only css to organize the content on a A4 format for example 

So the steps to export a dashboard as a pdf would be 
- click on a print button on the dashboard page
- choose some filters
- print the page as pdf

Can it be a first approach ?

**Comment by SamuelPetragallo** [comment]
@jeremiehelme great if filters can be added amended after having pressed the print - but we need to make sure that filters selected prior to clicking "print" should be kept and reflected in the report

So it would be:

- navigate dashboard, apply filters 
- click on a print button on the dashboard page (if filters have been selected they are maintained)
- amend filters (if needed)
- print the page as pdf

**Comment by SamMousa** [comment]
Let's not do amended filters, they are not intuitive

**Comment by SamMousa** [comment]
I have made a selection and want to print it; we can load the all in one page in the background and when it has been loaded open the print dialog. It will be one button that activates the browsers print / save to pdf

**Comment by jeremiehelme** [comment]
@SamMousa that's a better solution for now yes, we wouldn't have to navigate to another page

Actually, you can go to the pdf page even after having selected filters, 
So later we could use a pdf generation library and do it that way :
- choose some filters
- click on a print button on the dashboard page
It would then generate the pdf page directly in the browser

The url would be something like this 
https://herams.org/project/1/pdf?filter=eNqrVkpMKUvMS05NUbKqVnJ39TdUsopWcjRSitVR8s0PdjFB5ZqCucZKsbU6SimJJalKVkpGBkYGugbGukYmIQYGVmCkZwAGUUq1AMoZF-MA

**Comment by SamuelPetragallo** [comment]
> Let's not do amended filters, they are not intuitive

I agree, normally filter selection happens before printing

**Comment by jeremiehelme** [comment]
Here is what I did so far

When you click on the pdf button on the project dashboard

<img width="1680" alt="Capture d’écran 2020-03-06 à 17 09 43" src="https://user-images.githubusercontent.com/2345926/76100682-5eb3d680-5fcd-11ea-9efc-e1ce21142ee7.png">

You arrive on this page, with the filters you selected and you can print it

<img width="1680" alt="Capture d’écran 2020-03-06 à 17 07 56" src="https://user-images.githubusercontent.com/2345926/76100530-0d0b4c00-5fcd-11ea-9cfb-353c141ae534.png">

**Comment by jeremiehelme** [comment]
@SamMousa I added that the PR #372, if we can discuss that when you are available

**Comment by SamMousa** [comment]
Let's do tomorrow after meeting.

**Comment by jeremiehelme** [comment]
So, I tried multiples libraries, and this one in particular, which create a canvas from the page and export it to pdf :
https://github.com/eKoopmans/html2pdf.js#html

It works on simple html pages, but doesn't when it includes complex elements, like we have on the dashboard.

The other option would be to create a PDF layout, and fill it with the data. 
The downside is that we would need to create a layout for each page we would like to export in the future

**Comment by SamMousa** [comment]
We don't need custom libraries. We can just trigger the built-in browser functionality.

**Comment by jeremiehelme** [comment]
Here how it is for now.
If you select filters on the dashboard, they are kept on the print page

<img width="1680" alt="Capture d’écran 2020-03-18 à 17 16 54" src="https://user-images.githubusercontent.com/2345926/76982544-55672a00-693c-11ea-87c7-f81b2f54c51b.png">
<img width="1680" alt="Capture d’écran 2020-03-18 à 17 17 04" src="https://user-images.githubusercontent.com/2345926/76982560-59934780-693c-11ea-92bc-ec1164dcec5c.png">
<img width="1680" alt="Capture d’écran 2020-03-18 à 17 17 12" src="https://user-images.githubusercontent.com/2345926/76982569-5c8e3800-693c-11ea-98d6-3c60c132f2f9.png">

**Comment by SamMousa** [comment]
Does it show all pages?

**Comment by jeremiehelme** [comment]
Not yet, I had to battle against the canvas so that they render nicely on the print page
I'll check how to add the other pages

**Comment by jeremiehelme** [comment]
ok @SamMousa, all the charts from all the page now appear on the printable page. Pushed to #372

**Comment by jeremiehelme** [comment]
To continue on this, a few questions have been raised during the last meeting 


**- Applying the filters to the pdf export**
Done

**- Map ratio : should we keep the same ratio than on the dashboard (Square)**
I've made them full width so that they act as a separator between groups of charts, and because they are present on top of each page on the dashboard.
The main concern was that they then don't display exactly the same part of the map, (all the markers are still visible though).
Should I display them the same way than on the dashboard ?

**- Colors :  suggestions have been made to change colors so that they display well in black and white**
I can make sure that the colors have enough contrast for printing.
Do we have rules or recommendations on the colors ?


Thank you,

**Comment by jeremiehelme** [comment]
- Map height x2
- Add page title to separate charts
- Some charts have specific layout option (full width...)
- List filters used in the PDF
- Colors : check which charts don't display well in black & white

**Comment by jeremiehelme** [comment]
Here it is, with bigger maps, pages titles, and specific layout options for charts 
Each page from the dashboard displays on it's own page when printing

I just need to add the list of filters used 

![Capture d’écran 2020-04-16 à 17 54 24](https://user-images.githubusercontent.com/2345926/79478190-5ce92400-800b-11ea-9fa3-4c9f8211467d.png)

![Capture d’écran 2020-04-16 à 17 53 42](https://user-images.githubusercontent.com/2345926/79478065-3dea9200-800b-11ea-86de-70ae7f705dae.png)

**Comment by SamuelPetragallo** [comment]
Is that already visible on staging? (seems not)

**Comment by jeremiehelme** [comment]
@SamuelPetragallo Not yet, I'm adding the list of filter used, then Sam will be able to push it to staging

**Comment by jeremiehelme** [comment]
Merged in #389

**Comment by luna404** [comment]
This is absolutely great and will be very useful. F

I have few comments, some which are just wishes and might be pushed to a later release.

- It seems sub-pages are not included in the report. If you look at these two sample, the service availability page is missing and for Chad also some of basic amenities sub pages. [Chad](https://herams-staging.org/project/18/pdf), [Nigeria](https://herams-staging.org/project/30/pdf)
- Some of the table (and map legends) have a scroll bar, which means they will be cut off in the export. Could the tables be made a little bigger to make sure the entire content is always included?
![image](https://user-images.githubusercontent.com/18245059/80689171-33310200-8acd-11ea-8c6b-c58c7752dc84.png)

- Is it possible that the map zoom level has a padding applied? The default zoom level doesn't seem optimal 
![image](https://user-images.githubusercontent.com/18245059/80689030-041a9080-8acd-11ea-80de-06affb35f90f.png)

- Not sure whether this is possible, what in the print view, you can adjust the zoom level of the maps. Would it be possible that map zoom levels are always the same for all maps. Meaning if a user changes the zoom level for one map all the others will use the new zoom level?

- I'm curious what others think, but I would suggest to repeat the applied filter text on each page to make sure users are always aware which filters are applied.

For me only the first point (including sub pages) is crucial for the next release. The other point could also be addressed in a future release.

'

**Comment by jeremiehelme** [comment]
Great thanks @luna404,
I've added these points :
- including sub pages
- repeat the applied filter text, as well as page title and statistics

Opening a new Issue for the map and the tables

**Comment by luna404** [comment]
@jeremiehelme  can we add the page title for the sub-pages? No need to repeat the entire header, just the name of the page?

**Comment by SamuelPetragallo** [comment]
@jeremiehelme @luna404 thinking about the upcoming release: since we're mostly discussing tweaks to the layout I guess we can pause that work at any time and push to prod, can you confirm?

**Comment by SamuelPetragallo** [comment]
Also regarding the way the map is centered: the legend is not taken into account. Now, looking at the prints, it seems it's even delinked from the map in the pdf.

Wondering whether we could actually make that standard: 2 thirds for the map, 1 third for the legend

**Comment by SamuelPetragallo** [comment]
Should we systematically check whether 2 report sections can actually fit on 1 A4 (it's the case for the smallest sections) and "merge" them when feasible?

(More generally wondering how we should discuss issues/suggestions on this as it's likely that more refinements will be made along the way and using a single thread may become messy)

**Comment by jeremiehelme** [comment]
@SamuelPetragallo I agree, It works "ok" as it is and we will have time later to refine it

I've opened a new issue with the suggestion not taken into account yet 
#421
