### ISSUE TITLE
You can't click icons at the bottom of the questionnaire

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#814]
1. You can't click icons at the bottom of the questionnaire (i.e., resume later, previous, next, and submit)
2. Distance of these icons to the questions is also an issue
<img width="1680" alt="Screen Shot 2021-03-08 at 11 55 55 PM" src="https://user-images.githubusercontent.com/50957748/110346633-b2d31a00-806a-11eb-801a-48277f57d4e8.png">

**Comment by luna404** [comment]
@SamMousa  the buttons are jumping around making it impossible for a user to click?

https://user-images.githubusercontent.com/18245059/110352691-800f2e80-8036-11eb-82af-8fa2cc34a2fe.mp4

**Comment by JeffDotingco** [comment]
This is still not fixed upon checking

**Comment by JeffDotingco** [comment]
https://user-images.githubusercontent.com/50957748/110563630-8b716f80-8186-11eb-9b97-40b7ce64c500.mov
