### ISSUE TITLE
Users can't add new health facilities

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#817]
If a user tries to add a new health facility they get an error that the token is not valid.

The issue seems to the survey id in the link to create a new record. In the link to add a new HFs the survey id always default to Nigera (391149)

Here's an example from Mali COVID (survey id = 655873)

This is an example of the URL if you try adding a new HFs to workspace Tombouctou / Tombouctou (https://herams.org/workspace/9608/limesurvey)
https://ls.herams.org/391149?ResponsePicker=new&token=B9fzfoFUDG3Ea33&lang=en-US&newtest=Y

It should be:
https://ls.herams.org/655873?ResponsePicker=new&token=B9fzfoFUDG3Ea33&lang=en-US&newtest=Y

**Comment by SamMousa** [comment]
@luna404 I think this is fixed!

**Comment by luna404** [comment]
Seems to be working, thanks.
