### ISSUE TITLE
Managing our mailing list

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#823]
We're currently using a very old software to manage the list and share updates/newsletters.
Any idea of a soft/Service we could use for that that has built-in templates for example that don't look like Windows95?

**Comment by SamMousa** [comment]
How many people are on it and how often do you mail?

**Comment by SamMousa** [comment]
We use SendInBlue for platform mailing, they have campaigns as well (which is their term for mailing lists). This required a paid plan however and thus comes with the usual challenges.
