### ISSUE TITLE
Draft ToR for pivoting tool

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#827]
The goal is to create a new data analytics tool inspired by: https://pivottable.js.org/examples/

## Technical requirements
- Use web workers for asynchronous processing
- Modular design (1 module for processing, 1 module for UI, 1 module for charting)
- Charting should be implemented in such a way that other engines can be added later.
- Automated tests
- No unneeded large dependencies like jQuery
- Multiple charts should be able to use the same processing steps, think shared data, shared filters.

## Module: UI
The UI module will render a UI for configuring the processing steps, a suitable framework should be chosen and used here. This could be Vue or any other UI framework.
Note that the UI module can be tightly coupled to the other modules, but not the other way around

## Module: Processing
Research usage of indexedDB (https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) possibly using an abstraction library like:
https://dexie.org/
https://github.com/erikolson186/zangodb
https://pouchdb.com/

When / if we decide to use IndexedDB with an optional wrapper library we should implement data synchronisation & persistence, this will increase loading speeds and reduce server load.

## Module: Charting / rendering
Results can be rendered in several ways, the rendering can have configuration (think colors in charts or fonts in tables).
The rendering step may do simple calculations for example adding row / column totals in a table view.

**Comment by SamuelPetragallo** [comment]
Think we can soon get going on this and hear "offers" from potential candiates.

I will start circulating these requirements in the Info Management / Info Systems networks I'm connected to. Could you all @luna404 @SamMousa @joester89 and @Lucianna (?) circulate that on your side in any relevant networks? We're essentially after offers now to get this work done that include timeline/workload/cost
