### ISSUE TITLE
Permission to create HFs no longer bundeled with edit permission

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#829]
If the project setting "Manage data implies creating facilities" is enabled permission to create a new health facility is no longer included, but has to be explicitly granted. Can we change this back? 

@SamMousa is this related to the changes you made in issue #819?

**Comment by SamMousa** [comment]
I didn't make any changes I just added tests to confirm that it does work.

**Comment by SamMousa** [comment]
I don't think there is a bug here... is there a different behavior on PROD vs STAGING? If not then this works as expected.
