### ISSUE TITLE
View response is missing a scroll bar 

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#835]
In the response picker, if you click the view button, it only displays the first few questions, the rest is cut off.

This is basically the same issue as we had for the questionnaire but for the view response.
![image](https://user-images.githubusercontent.com/18245059/114712133-a6a44180-9d27-11eb-94fb-dac860554b98.png)

**Comment by joester89** [comment]
Can be tested in https://feature-843-newsletter-subscription.herams-staging.org
