### ISSUE TITLE
Email confirmations are not sent

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#839]
Confirmation emails upon registering, inviting new users, etc. are not sent. A confirmation that the email has been sent is shown on the platform, but the recipient doesn't receive the email.

**Comment by SamMousa** [comment]
This is probably due to the quota limits we keep hitting.

**Comment by luna404** [comment]
Is this a monthly or weekly quota?

We have two training sessions planned for next week and if users can't register we have a problem.

**Comment by SamMousa** [comment]
Hourly; I shared the screenshot with you that mentioned it.

@SamuelPetragallo this can be resolved by simply purchasing some prepaid mail credits via SendInBlue.

**Comment by luna404** [comment]
Based on the message, it says the emails should be sent with the next hourly quota. I haven't received emails from yesterday so this means we either have a huge backlog or something is not working as expected.

**Comment by SamMousa** [comment]
Looking into it now.

**Comment by SamMousa** [comment]
Okay, took some digging but there is some kind of backlog.
Currently there are 86 mails in the queue waiting to be sent.

**Comment by luna404** [comment]
Do you know what our current hourly limit is or how long it would take for this to resolve itself?

**Comment by SamMousa** [comment]
I have contacted their support, I'm not sure how long it'll take or how it'll work.

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/115723626-75a7ba80-a380-11eb-87b3-99b8c2331a7e.png)

Our quota is 0, this can only be manually resolved by their support team.

**Comment by SamMousa** [comment]
Fixed by moving to sendgrid.
