### ISSUE TITLE
Add option to subscribe to newsletter when users create new account

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#843]
To be a little more GDPR compliant, can we add an option to subscribe to the newsletter to the sign-up page and add an option to manage "subscriptions" to the user profile?

 We would also need a process to easily extract this info from the database and merge this with the list in MC or whatever we end up using. @LuciannaFG could you work on a workflow for the second part (i.e how to update MC)?

**Comment by LuciannaFG** [comment]
Yes @luna404. Of course. I'll dig in.

**Comment by joester89** [comment]
@luna404 @LuciannaFG this feature is ready to be tested :)

The link to test: https://feature-843-newsletter-subscription.herams-staging.org

What to test:
When:
- creating an account yourself
- being invited
You can now check the newsletter subscription checkbox.
Also at your profile there now is a checkbox with which you can change your subscription status.

In Mailchimp I created a new audience for testing purposes. Here you can find the newly subscribed user. If you unsubscribe in Mailchimp (i.e. you can unsubscribe someone from the admin panel), this will also be passed to HeRAMS.

Important note: Do test everything in one go, when I push changes, the database will be reset and I'll be writing tests and adding production keys so this will happen probably Thursday.
