### ISSUE TITLE
Hyperlinks in system emails are wrong

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#844]
The two hyperlinks marked in the screenshot below are wrong. This is why users were experiencing a privacy error.

![image](https://user-images.githubusercontent.com/18245059/116578991-dcd9e780-a909-11eb-8959-fd6a2c8d3892.png)

**Comment by SamMousa** [comment]
Where are they pointing?

**Comment by luna404** [comment]
http://url4802.herams.org/ls/click?upn=vDFSG7FXjpchZtqBR8tt6QzewE8TZxq4V2lfzdwpl5nVS9b00S3hvKtrI2komNkdox88c8aUhnhrV6HfSqo0Pz5quPY-2FpiOfeLXsUX9InHzkp6R-2BWwU-2BNlwQgbmAzpgZZ5JWKqWf3km2vaweBe8zbTZYXaRnRbRGe0QIpKs6UJU3qlTyyQdGjG3niGCJSXLJZ7-z_teUpoUEouv1PFf-2BShOzaayfd4s5K5XmiWs6ofNlO5XCi0qi5wQwv1wig4EN9g7e-2FsnwiWlrGZzGFZDFhIYeq-2FgegTl70FUd-2BklTCgnQ4RRdngAn2-2FV01FPr2GyHBzgz7B2Hfgec-2Bvwx-2BbzanzRZNQd1At3qYMhkajYF9WSL0GComRpMDOuQgs1NKagtucZLVhE2a3PGejopss9FgJ1n7INOKya20QHNMLE8NjBGTmh4-3D

**Comment by SamMousa** [comment]
That looks good to me, it works

**Comment by luna404** [comment]
![Screenshot_20210429-183551](https://user-images.githubusercontent.com/18245059/116594135-ccca0400-a919-11eb-8df8-f8c8c04f2e07.png)

**Comment by SamMousa** [comment]
That's a browser issue... The link is not https, the browser seems to be trying https for it for some reason.

**Comment by SamMousa** [comment]
I have disabled click tracking so now links shouldn't get replaced and they are all https to our primary domain. Now it should work even for bad browsers.

**Comment by SamMousa** [comment]
@luna404 please confirm that it works now. I deleted the link you posted just so people don't create an account in your test mail.

**Comment by luna404** [comment]
Thanks, it's working.
