### ISSUE TITLE
Alert user that they already have an account

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#845]
Could we add a message stating that users already have an account and should log in or reset their password?

Currently, if you try creating an account with an already existing email, you won't get any messages or alerts that you're already registered.  While you get a success message when a confirmation email is sent out, new users might not know that they should see the success message and hence think that the registration is not working properly.

**Comment by joester89** [comment]
Would this be a fine solution:

![image](https://user-images.githubusercontent.com/9624366/117792358-7dee6980-b24b-11eb-8ea3-48a7d2cf7bd6.png)

If so it can be included with #843 ;)
