### ISSUE TITLE
Staging access - privacy error

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#849]
I'm having the same issue trying to access weblate as I had a few weeks ago with the email confirmation links #844. See error message below.

![image](https://user-images.githubusercontent.com/18245059/119369149-240e8a80-bcb4-11eb-822f-ae867a42537e.png)

**Comment by luna404** [comment]
![image](https://user-images.githubusercontent.com/18245059/119371328-997b5a80-bcb6-11eb-87a9-3d39a3e89fc5.png)

**Comment by SamMousa** [comment]
This is now fixed for staging, looking into prod still..

**Comment by SamMousa** [comment]
Fixed for prod as well.
