### ISSUE TITLE
SurveyJS - Ranking questions

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#850]
related to #590

@SamMousa can we discuss the feasibility of developing a custom widget for ranking questions that has the same behaviour as in LS?

**Comment by SamMousa** [comment]
https://github.com/surveyjs/survey-creator

They have a new ranking question now; please see if the issues are still there / relevant.

**Comment by luna404** [comment]
The generic ranking question they have only allows to reorder all answer option. In LS we can limit the number of responses users can select (i.e. select your top 3 priorities and rank them based on your priorities). I can't see this functionality anywhere in SurveyJS. 


@SamuelPetragallo we could achieve a similar behaviour by having 3 single select questions. Using conditioning, we can remove an answer option once it was selected to prevent users from selecting the same reason multiple times.
![image](https://user-images.githubusercontent.com/18245059/119509506-fb989600-bd70-11eb-9b70-f3bb11fdd5c7.png)

**Comment by SamMousa** [comment]
> we could achieve a similar behaviour 

Wouldn't it be better to make it a multiple choice instead? And then after the user picks which ones are available and if it is more than 1 source you show the ranking question?

That way they only see options that are relevant in the ranking.

**Comment by SamMousa** [comment]
It turns out this requirement was already solved by the original SortableList in SurveyJS.
On this page you can create a SortableList and set `maxAnswerCount`

https://surveyjs.io/Examples/Survey-Creator?id=customwidgets&theme=bootstrap

**Comment by SamMousa** [comment]
@luna404 I think this can be closed. The sortablelist question solves this by having a maximum number of answers.

I'd personally still avoid ranking questions if at all possible, they are very hard to analyse.
