### ISSUE TITLE
User registration error

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#852]
If you try to register or invite a new user you get the below error message

![image](https://user-images.githubusercontent.com/18245059/121486428-6bde2300-c9d1-11eb-93cd-ddaee90fcd85.png)

**Comment by SamMousa** [comment]
Is this on prod or staging?

**Comment by luna404** [comment]
Both

**Comment by SamMousa** [comment]
Can you retry? Could have been an intermittent error from sendgrid

**Comment by luna404** [comment]
Seems to be working again
