### ISSUE TITLE
Prepare for SurveyJS

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#853]
- [ ] Create a survey (db) model
- [ ] Integrate SurveyJS creator 
- [ ] Research if we need an update / create form, or if the SurveyJS creator suffices
- [ ] Research asset uploading in SurveyJS creator (for survey specific assets like images, if applicable)
- [ ] Research asset storage (DigitalOcean Spaces S3?)

**Comment by joester89** [comment]
Duplicate of #885
