### ISSUE TITLE
Dashboard page translation not working in dashboards

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#866]
The standard dashboard pages are not translated in the dashboard itself.

For example, I've updated the three pages marked in red so that they use a page title from the drop-down list. When I change the language to French, this works fine in the dashboard settings but in the dashboard itself, the names still show in English. 

https://herams.org/project/31

Dashboard settings            |  Dashboard
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/18245059/124237951-61b6cc80-db18-11eb-9fe7-8c7874301234.png)  |  ![](https://user-images.githubusercontent.com/18245059/124238264-a5113b00-db18-11eb-8d52-32173a867eb8.png)

**Comment by SamMousa** [comment]
Confirm that `Yii::t` is used.

**Comment by joester89** [comment]
Can be tested at https://feature-866-fix-dashboard-title-translation.herams-staging.org
