### ISSUE TITLE
Causes of unavailability chart not displaying all text labels 

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#868]
I'm having an issue with the "causes of unavailability" chart in project 39. The chart aggregates the data correctly, but it's not displaying all text labels. 
https://herams.org/project/31

![image](https://user-images.githubusercontent.com/18245059/124240529-1c47ce80-db1b-11eb-8087-589eeb396ced.png)

When you open the settings for the chart, it doesn't show all categories.
https://herams.org/element/1167/update
![image](https://user-images.githubusercontent.com/18245059/124240701-47322280-db1b-11eb-8bd9-958c7e9d2e86.png)

I exported the data and aggregated it elsewhere and there doesn't seem to be an issue with the data. This perfectly matches the data in the chart. 
![image](https://user-images.githubusercontent.com/18245059/124240989-9f692480-db1b-11eb-84a7-96880ecf48f7.png)

**Comment by joester89** [comment]
It was quite a search to find out that in the questionnaire there are only 2 answer options: https://ls.herams.org/admin/questions/sa/answeroptions/surveyid/341175/gid/648/qid/9567#tabpage_fr
