### ISSUE TITLE
Dashboard sub-pages do not respect the sort index

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#869]
Dashboard sub-pages are shown in order of id and not in order of the sort index.
The example below is from project 39, but the issue affects all dashboards. 

![image](https://user-images.githubusercontent.com/18245059/124243435-2cad7880-db1e-11eb-847e-79cbc3d8817b.png)

Order of sub-pages in the dashboard
![image](https://user-images.githubusercontent.com/18245059/124243527-464ec000-db1e-11eb-86c0-57e73eabf051.png)

**Comment by SamMousa** [comment]
Project 39 has only 1 page as far as I can tell

**Comment by SamMousa** [comment]
Please provide a link to the actual page showing the incorrect behavior.
By omitting the link I have to do a linear search for projects that fit your description.

**Comment by luna404** [comment]
https://herams.org/project/31

**Comment by luna404** [comment]
This is not working.

Here's an example.

The nutrition sub-page as sort index 1 
https://herams.org/project/24/pages
![image](https://user-images.githubusercontent.com/18245059/130131250-1b91e3d9-2a2b-44fa-8a36-1a119ea15da3.png)

But in the dashboard, it appears as the 5th sub-page
https://herams.org/project/24
![image](https://user-images.githubusercontent.com/18245059/130131396-8788db29-f65c-4d63-ba85-caf94a93cbb4.png)
