### ISSUE TITLE
Dashboards multi-language support

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#870]
We discussed this a few weeks ago in one of our meetings. Dashboard elements currently only show the default language of the survey regardless of what language the user has chosen in their profile. @SamMousa you mentioned that this might be easy to resolve. Can we look into this as a priority, please?

**Comment by SamMousa** [comment]
Please see https://github.com/HeRAMS-WHO/herams-backend/pull/878

**Comment by luna404** [comment]
I can't change the language to French or Arabic, this makes testing this a little difficult

Error : Getting unknown property: prime\models\ar\read\Project::i18n

**Comment by SamMousa** [comment]
Where do you change the language?

**Comment by luna404** [comment]
Yes, but I thought it picks up the language the user has defined in their profile. 
So if a survey is available in en and fr and I have fr selected in my profile I should see it fr and vice versa.

**Comment by luna404** [comment]
I can't change the language in my profile on staging.

**Comment by SamMousa** [comment]
> I can't change the language in my profile on staging.

I could do it when impersonating you, if that issue persists please create a new issue.
