### ISSUE TITLE
Display refresh workspace button for workspace owners

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#875]
Users with permissions to "Manage workspaces" should have the permission to refresh a single workspace.

**Comment by SamMousa** [comment]
@luna404 it helps a lot if you add a link to the page where the button is shown.

**Comment by SamMousa** [comment]
Should `MANAGE_WORKSPACES` give all permissions from `SURVEY_DATA`?

Because currently we check if the user is allowed access to survey data (if not then refreshing a workspace doesn't make much sense).
What I think happened here is that we moved this button to the update page; so while any user who can manage data is authorized to refresh the workspace, they can't reach the page that has the button.

So another solve would be to add this sync button to the list page

**Comment by luna404** [comment]
The button is supposed to be on the workspace settings page https://herams.org/workspace/10599/update

![image](https://user-images.githubusercontent.com/18245059/124764198-fe240900-df34-11eb-8018-c6c3a2325d02.png)


What do you mean by all permissions from `SURVEY_DATA`? 

The issue was raised by a user that has the following permissions but still can't refresh a workspace. (This is the standard permission we grant to project admins.)
![image](https://user-images.githubusercontent.com/18245059/124764777-9cb06a00-df35-11eb-9830-be08a067e596.png)

**Comment by SamMousa** [comment]
Which user? If you give me more details I can actually go in and reproduce.

**Comment by luna404** [comment]
user id 10680, project 24. There's only one user with all permissions. I won't publish names here.

**Comment by SamMousa** [comment]
IDs are better than names anyway :)

**Comment by SamMousa** [comment]
Okay, found the issue, but there are actually 2 issues.

The reported issue is correct; the button wouldn't show even if the user had the `edit data` permission.

But there is a bigger issue: this page is only accessible when the user has `manage workspaces` permission on the project (or write permission on the individual workspace).

So in essence, `edit data` AND `manage workspaces` are required. This feels wrong to me.

Possible solutions:
1. Require just `manage workspaces` (ie: everyone who can access the settings page sees and can access the buttons)
2. Move the refresh button to the first tab, which actually is accessible with just `edit data` permission.

Which one do you prefer?

**Comment by luna404** [comment]
I thought there was a reason why option 2 is not possible, hence we put the button on the settings page. But I would prefer option 2 over option 1.

**Comment by SamMousa** [comment]
Maybe that was before we integrated the response picker in the new layout?

**Comment by SamMousa** [comment]
Moved it to the first screen.
