### ISSUE TITLE
Error loading dashboard on staging

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#887]
I'm getting the below error for some of the dashboards on staging. 

`trim(): Argument #1 ($string) must be of type string, bool given`

e.g. https://herams-staging.org/project/40

**Comment by luna404** [comment]
Fix seems to not work for all projects. There's still an issue with the dashboard for Mauritania (https://herams.org/project/57). The issue only arises if the user has English selected as profile language.

**Comment by joester89** [comment]
@luna404 does this problem still occur? Since I do not get a problem anymore on the mentioned link on production...

**Comment by luna404** [comment]
I think the fix for this was included in the last release.
