### ISSUE TITLE
Dashboard page name not translated everywhere

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#888]
- Name of the parent page is not translated (see basic amenities in column 3) (https://herams-staging.org/project/34/pages)
![image](https://user-images.githubusercontent.com/18245059/127991672-499b30fb-97df-43e9-b4c1-1f192870c5bd.png)

- Page title and breadcrumbs (https://herams-staging.org/page/357/update)
![image](https://user-images.githubusercontent.com/18245059/127991874-0b54d583-9e7e-418e-bd1b-541a295a365b.png)

- Title and dropdown list of parent page name (https://herams-staging.org/page/357/update)
![image](https://user-images.githubusercontent.com/18245059/127992240-e5fea3f8-f7bc-4684-a85a-38a67a252a41.png)

**Comment by luna404** [comment]
The second point, page title and breadcrumbs in the dashboard itself are still not translated. The rest is fine.

**Comment by joester89** [comment]
I believe this is working now.

**Comment by luna404** [comment]
It's not translated in the page title and the breadcrubs. The rest is fine. 

![image](https://user-images.githubusercontent.com/18245059/133453603-5a383e56-6bcf-4745-9a34-885f82a91cf5.png)

**Comment by joester89** [comment]
Please add urls when adding in examples
