### ISSUE TITLE
View response only available in English only

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#889]
If you view a response, it always displays it in English regardless of the language selected by the user or the base language of the survey. Could this be changed to use the same language as used for the response picker?

eg. https://herams-staging.org/workspace/5386/limesurvey
-> user selcted french
![image](https://user-images.githubusercontent.com/18245059/127993564-9c4842b3-cdf0-4e97-9895-ce160ba10b48.png)

-> reponse displayed in english (should be french as well)
![image](https://user-images.githubusercontent.com/18245059/127993683-3f6dedcb-b3a7-4ee1-9e73-b239d2afb540.png)

**Comment by SamMousa** [comment]
You can test this on prod.
