### ISSUE TITLE
Project settings - I18n Title display issue

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#892]
The fields for the translation overlap with other fields on prod.

![image](https://user-images.githubusercontent.com/18245059/128485011-2e46238f-380e-4712-8aa6-b9bf296281b3.png)
https://herams.org/project/31/update

It's fine on staging if you use chrome. But in firefox the fields don't show at all (both on staging and prod)
https://herams-staging.org/project/40/update
![image](https://user-images.githubusercontent.com/18245059/128485311-f1d716d7-4928-40f7-833c-9aa35e6d3129.png)

**Comment by SamMousa** [comment]
Hmm, turns out firefox doesn't actually support custom form elements yet. This is not something we can easily fix; we might have to use a different appraoch.

**Comment by SamMousa** [comment]
@SamuelPetragallo @luna404 do we need to support anything besides chrome for the admin side of things? If not we could close this and leave it for another day.

**Comment by luna404** [comment]
As long as it's just for the project settings, we can live with only Chrome.

**Comment by SamMousa** [comment]
In that case, closing this for now.
