### ISSUE TITLE
Develop HF reports

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#9]
As an extension to HFs "popups" available from the map, users with access to the detailed data (i.e. with access to the WS within which this HF is managed) can access a full report of then HF. That report can be pdf-printed. Bruno to design that report.

**Comment by SamMousa** [comment]
Next step is a rough sketch of what info you want in that report. After that assign it to Novel-T so they can make a design.

**Comment by jeremiehelme** [comment]
@SamuelPetragallo We discussed about this point when we met, and we had to ask Bruno about the mockup he had for that screen. 
Can I contact him directly ?

**Comment by SamuelPetragallo** [comment]
That's a very important one. We're stuck because of design. @luna404 any idea who we could mobilize to propose a top notch HF report? (thinking whether we could ask some of the guys on the ground too? Daniel or others that have done some graphical work?

**Comment by luna404** [comment]
I think the bigger challenges is deciding what should be included in the report. Daniel would be good at a later stage. Once we have an initial draft someone with his profile would be good to make it "pretty". But the challenge then would be how to translate this into something that is generated automatically.

**Comment by SamuelPetragallo** [comment]
Ok - will start looking into this starting from the SDM

**Comment by SamuelPetragallo** [comment]
Let's start by looking at the list of core variables in the SDM. Have asked Fatma to provide that. We can then further boil  it down if needed and finally discuss visualizations

**Comment by FatmaGiha** [comment]
@SamuelPetragallo  here is excel-based SDM, where list of variables included down to the needed field of core/optional.
I didn’t include definitions and answer options... etc, but if you think that’s needed let me know.
 
 
[SDM_Variables.xlsx](https://github.com/HeRAMS-WHO/herams-backend/files/4751720/SDM_Variables.xlsx)
