### ISSUE TITLE
Syncing of projects

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#927]
Is the daily sync of projects (#654) still active? If yes could please add project 30 (Nigeria). It doesn't seem to be syncing correctly.
![image](https://user-images.githubusercontent.com/18245059/137298591-c1fb66de-b051-4082-a265-3a05098ee3ea.png)

**Comment by SamMousa** [comment]
This is fixed now, every 15 mins 100 workspaces are synced (based on the leastly recently synced response they contain).
Every hour all empty workspaces are synced.
