### ISSUE TITLE
Daily messaging limits

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#939]
What is our daily messaging limit? I was doing batch invitations for next week's training and apparently hit the limit. 

![image](https://user-images.githubusercontent.com/18245059/140663069-71660627-8a90-4369-80d2-25f089ea6bd9.png)

**Comment by luna404** [comment]
Any acting triggering an email to be sent to users generates the below error.

![image](https://user-images.githubusercontent.com/18245059/140705812-7e937b9d-c036-4bb7-95b5-58de538f32b2.png)

**Comment by luna404** [comment]
We have a big training tomorrow and will need to create accounts for each of these participants beforehand.

**Comment by SamMousa** [comment]
100 emails a day.  I've invited @SamuelPetragallo as an account admin for Sendgrid; he should be able to set up a billing method so we can purchase a plan.

**Comment by SamMousa** [comment]
https://app.sendgrid.com/account/billing/choose_plan
