### ISSUE TITLE
Data download for project 34 times out

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#940]
Downloading the entire data set with values as text keeps timing out for project 34.

https://herams.org/project/34/export

**Comment by SamMousa** [comment]
Can you export from LS? (as a workaround?)

**Comment by SamMousa** [comment]
Have increased the timeout to 300s

**Comment by luna404** [comment]
Still times out

**Comment by SamMousa** [comment]
Hmm, I tried this and got the csv... let me double check if i enabled answers as text.

**Comment by SamMousa** [comment]
Hmm, this seems harder to fix than expected. Won't be fixed today.

**Comment by SamMousa** [comment]
Fixed.
