### ISSUE TITLE
Error saving records

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#941]
I have an issue with questionnaire 322125 (https://ls.herams.org/admin/survey/sa/view/surveyid/322125).

I get the below error when trying to save a new record. Can you explain to me what this means? I checked the survey logic file and there is no apparent error there. 

![image](https://user-images.githubusercontent.com/18245059/140716095-f0d8ffe8-d7a2-46d6-a0f1-bdf2d189a261.png)

**Comment by SamMousa** [comment]
Fixed on prod, disabled the submission on staging.
