### ISSUE TITLE
Time series export for large projects

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#942]
Some of the larger projects are getting too big to export all historic data. The ability to only export the last version of data available is not sufficient for all cases  (e.g. trend analysis, completeness of reports (i.e. admin dashboard), etc.).

Possible strategies: 
1. Archive some of the older data
2. Allow for time frames to be specified in the export. E.g. extract all available data for the last 6 months.

**Comment by SamMousa** [comment]
Do we know if 2 would actually solve the current issues? (Isn't the bulk of the data actually from the last 6 months?)

1 could be implemented as a cap on the export date making it function just like 2.

**Comment by matof-who** [comment]
Closing this issue, will be covered  by #1017
