### ISSUE TITLE
Workspace mass syncing disabled

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#951]
The mass syncing of workspaces is not working. The button to sync workspaces has disappeared. 

![image](https://user-images.githubusercontent.com/18245059/143005293-ec9309b7-295e-4c61-9aa1-78a1691cb0c9.png)

**Comment by SamMousa** [comment]
Add the URL of the page please.

**Comment by luna404** [comment]
https://herams.org/project/59/sync-workspaces

**Comment by SamMousa** [comment]
This was a nasty one! Fixed it, the button is now visible again in PROD.
