### ISSUE TITLE
List of workspaces - workspaces are repeated if you move to the next page

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#955]
If you use the next buttons to advance to the next page, some workspaces are repeated. The issue was reported from multiple projects.

e.g. page 1:
https://herams.org/project/59/workspaces
![image](https://user-images.githubusercontent.com/18245059/143476937-c7e56815-4641-4408-8083-f04fe4b23084.png)

page 2: 
https://herams.org/project/59/workspaces?workspace-data-provider-page=2&workspace-data-provider-per-page=10
![image](https://user-images.githubusercontent.com/18245059/143477016-18213377-10e7-4198-8c4c-374b1f2b5ed6.png)

We had a similar issue with the dashboard pages earlier this year #902

**Comment by SamMousa** [comment]
This is probably due to undefined sorting order (ie latest update being the same). I'll add a secondary order on ID.

**Comment by SamMousa** [comment]
This is fixed in SurveyJS version because we do client side pagination.
