### ISSUE TITLE
Respond to access request not working for users without global admin permission

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#961]
Regular users expected to manage access requests get the below error when trying to open the page to manage access requests (https://herams.org/access-request/index) 

Error: `SamIT\abac\AuthManager::check(): Argument #2 ($target) must be of type object, null given, called in /project/protected/rules/RespondToAccessRequestRule.php on line 66`

It seems to work for global admins though as I don't get the error using my profile.

**Comment by SamMousa** [comment]
Fixed in PROD

**Comment by luna404** [comment]
This keeps happening to some users

**Comment by luna404** [comment]
Example: SamIT\abac\AuthManager::check(): Argument #2 ($target) must be of type object, null given, called in /project/protected/rules/RespondToAccessRequestRule.php on line 66
user id: 10948
link: https://herams.org/access-request/index
