### ISSUE TITLE
Portuguese translation of the dashboard

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#964]
We have a new project where the questionnaire is being translated to Portuguese. I've changed my browser language to Portuguese and set my language preference to Autodected, but the dashboard still only displays in English. Do we have to add Portuguese as a platform language for the dashboard to display in Portuguese?

PS: right now we only have a few words translated so the majority would still display in English. 

dashboard: https://herams.org/project/60
LS project: https://ls.herams.org/admin/survey/sa/view/surveyid/836356

**Comment by SamMousa** [comment]
Just FYI, I'm on break until February.

**Comment by SamMousa** [comment]
>  Do we have to add Portuguese as a platform language for the dashboard to display in Portuguese?

Yes this is required. The dashboard only supports platform languages.

**Comment by SamMousa** [comment]
@luna404 I've added Portugese to Weblate. Can you give me an ETA for when this translation is ready? That way I can plan a release to include the new language.

**Comment by luna404** [comment]
We're not aiming to translate the entire user interface at this stage. The focus, for now, is the ability for users to view the dashboard in Portuguese. The questionnaire has already been translated and I've added the strings needed for the dashboard pages. So it's good for an initial release.
In case you're not planning on doing the release this week, please let me know.

**Comment by SamMousa** [comment]
> We're not aiming to translate the entire user interface at this stage. 

This was discussed with @SamuelPetragallo. It's a clean way to put the burden off translations on the people pushing for localized versions. 
The platform does not support having the dashboard in a non-platform language at this time; releasing a language with only very little translation is just a bad UX. 
It'll look very disorganized with mixed content, lots of stuff will still be in English which will then lead to follow up requests from users and pushes for new releases containing translation updates.

> So it's good for an initial release.

I really disagree, we should not add a language to the platform while not really supporting it.

> In case you're not planning on doing the release this week, please let me know.

I hope to do one tomorrow, but am hesitant to include a partial language. If we do I want us to clearly agree on the fact that no follow up releases will follow with more translations.

**Comment by SamMousa** [comment]
This was released.
