### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#965]
- [x] Generate local ssh key
- [x] Add ssh key to github
- [x] Remove your personal fork
- [x] Clone the main repository using the SSH protocol
- [ ] `docker-compose pull`
- [ ] `docker-compose build`

**Comment by SamMousa** [comment]
The first set of "challenges" are to write some tests that improve the coverage of our code. Make sure to look at existing tests to figure out how to set up new ones.


- [ ] Figure out how to access code coverage in the browser
- [ ] Write a UNIT test to increase code coverage of `JobQueueProxy` and `ProposedGrant`
- [ ] Write a FUNCTIONAL test to confirm that the route `site/maintenance` returns a `503`.
- [ ] Setup a UNIT test for the `SessionController` 

Generic coding rules:
- Every file you change should be in strict mode, if it's not add it
- Every class is `final` by default
- Every class property and method is `private` by default
- Every method must have an explicit return type

The `by default` rules don't mean that a method can't be `public`, it just means that if it is `public` you should be able [logically] defend it.

**Comment by pgichuki** [comment]
@SamMousa is:

- `ProposedGrant` checks if the source has permission to access the target, right?
- `JobQueueProxy` any documentation on this?

**Comment by SamMousa** [comment]
> checks if the source has permission to access the target, right?

Not sure where you get that... it's a simple value object with just getters.

> `JobQueueProxy` any documentation on this?

It contains like 2 lines of executable code... I hope you can figure out what it does?

**Comment by SamMousa** [comment]
I will revert your commits on the `surveyjs-parser` branch. Instead you should create your own branch from the surveyjs-parser branch, implement your changes there and create a PR.

**Comment by pgichuki** [comment]
@SamMousa, the build gets a 403 when exporting image to GHCR. Could it because of no write access for my account?

**Comment by SamMousa** [comment]
Yes definitely. Can you see if you can disable the build only for PRs from other repositories?

**Comment by pgichuki** [comment]
> Yes definitely. Can you see if you can disable the build only for PRs from other repositories?

Need to add 
secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}

to the  docker/build-push-action since this is fork pull request. Can I add that the workflow?

**Comment by SamMousa** [comment]
No. Read my feedback again.

**Comment by pgichuki** [comment]
- Figure out how to access code coverage in the browser
- Write a UNIT test to increase code coverage of JobQueueProxy and ProposedGrant
- Write a FUNCTIONAL test to confirm that the route site/maintenance returns a 503.
- Setup a UNIT test for the SessionController

**Comment by pgichuki** [comment]
> Yes definitely. Can you see if you can disable the build only for PRs from other repositories?

I have added a check in the precondition in pr-preview. 

This is in a separate PR.
