### ISSUE TITLE
SJS Migration  - Import

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#981]
- [ ] Document requirements for baseline imports
- [ ] #988
- [ ] Batch move HFs to different WS
- [ ] Import baseline data (create HF, create admin record, optionally create data record)
- [ ] Batch facility update
- [ ] Batch data manipulation

**Comment by matof-who** [comment]
Requirements described in confluence: https://extranet.who.int/confluence/x/R4B9B
Separate issues created for the different imports, under the epic "Data Import"
